"""HSK vocabulary data for Mandarin Chinese typing practice.

Contains vocabulary for HSK Levels 1–3 based on the classic HSK standard
(pre-2021), organized by level.  Each entry includes simplified Chinese
characters (hanzi), pinyin romanization, and English translation.

The vocabulary covers the core words tested in HSK levels 1 through 3
and is suitable for building foundational Mandarin reading and typing skills.
"""

import random
from typing import Dict, List

# Each entry: {"hanzi": str, "pinyin": str, "english": str}
HSK_VOCAB: Dict[int, List[Dict[str, str]]] = {
    1: [
        # ── Pronouns & People ──
        {"hanzi": "我", "pinyin": "wǒ", "english": "I / me"},
        {"hanzi": "你", "pinyin": "nǐ", "english": "you"},
        {"hanzi": "他", "pinyin": "tā", "english": "he / him"},
        {"hanzi": "她", "pinyin": "tā", "english": "she / her"},
        {"hanzi": "我们", "pinyin": "wǒmen", "english": "we / us"},
        {"hanzi": "你们", "pinyin": "nǐmen", "english": "you (plural)"},
        {"hanzi": "他们", "pinyin": "tāmen", "english": "they / them"},
        {"hanzi": "这", "pinyin": "zhè", "english": "this"},
        {"hanzi": "那", "pinyin": "nà", "english": "that"},
        {"hanzi": "哪", "pinyin": "nǎ", "english": "which"},
        {"hanzi": "谁", "pinyin": "shéi", "english": "who"},
        {"hanzi": "什么", "pinyin": "shénme", "english": "what"},
        {"hanzi": "多少", "pinyin": "duōshao", "english": "how many / how much"},
        {"hanzi": "几", "pinyin": "jǐ", "english": "how many (small number)"},
        {"hanzi": "怎么", "pinyin": "zěnme", "english": "how"},
        {"hanzi": "怎么样", "pinyin": "zěnmeyàng", "english": "how about"},
        # ── Family ──
        {"hanzi": "人", "pinyin": "rén", "english": "person / people"},
        {"hanzi": "爸爸", "pinyin": "bàba", "english": "father / dad"},
        {"hanzi": "妈妈", "pinyin": "māma", "english": "mother / mom"},
        {"hanzi": "儿子", "pinyin": "érzi", "english": "son"},
        {"hanzi": "女儿", "pinyin": "nǚér", "english": "daughter"},
        {"hanzi": "朋友", "pinyin": "péngyou", "english": "friend"},
        {"hanzi": "同学", "pinyin": "tóngxué", "english": "classmate"},
        {"hanzi": "老师", "pinyin": "lǎoshī", "english": "teacher"},
        {"hanzi": "学生", "pinyin": "xuésheng", "english": "student"},
        {"hanzi": "医生", "pinyin": "yīshēng", "english": "doctor"},
        {"hanzi": "先生", "pinyin": "xiānsheng", "english": "Mr. / sir"},
        {"hanzi": "小姐", "pinyin": "xiǎojiě", "english": "Miss / young lady"},
        # ── Numbers & Quantity ──
        {"hanzi": "一", "pinyin": "yī", "english": "one"},
        {"hanzi": "二", "pinyin": "èr", "english": "two"},
        {"hanzi": "三", "pinyin": "sān", "english": "three"},
        {"hanzi": "四", "pinyin": "sì", "english": "four"},
        {"hanzi": "五", "pinyin": "wǔ", "english": "five"},
        {"hanzi": "六", "pinyin": "liù", "english": "six"},
        {"hanzi": "七", "pinyin": "qī", "english": "seven"},
        {"hanzi": "八", "pinyin": "bā", "english": "eight"},
        {"hanzi": "九", "pinyin": "jiǔ", "english": "nine"},
        {"hanzi": "十", "pinyin": "shí", "english": "ten"},
        {"hanzi": "百", "pinyin": "bǎi", "english": "hundred"},
        {"hanzi": "千", "pinyin": "qiān", "english": "thousand"},
        {"hanzi": "零", "pinyin": "líng", "english": "zero"},
        {"hanzi": "个", "pinyin": "gè", "english": "general measure word"},
        {"hanzi": "岁", "pinyin": "suì", "english": "year (of age)"},
        {"hanzi": "块", "pinyin": "kuài", "english": "unit of money (yuan)"},
        {"hanzi": "些", "pinyin": "xiē", "english": "some"},
        # ── Time & Date ──
        {"hanzi": "年", "pinyin": "nián", "english": "year"},
        {"hanzi": "月", "pinyin": "yuè", "english": "month / moon"},
        {"hanzi": "日", "pinyin": "rì", "english": "day / date"},
        {"hanzi": "号", "pinyin": "hào", "english": "number / date"},
        {"hanzi": "星期", "pinyin": "xīngqī", "english": "week"},
        {"hanzi": "点", "pinyin": "diǎn", "english": "o'clock / point"},
        {"hanzi": "分钟", "pinyin": "fēnzhōng", "english": "minute"},
        {"hanzi": "今天", "pinyin": "jīntiān", "english": "today"},
        {"hanzi": "明天", "pinyin": "míngtiān", "english": "tomorrow"},
        {"hanzi": "昨天", "pinyin": "zuótiān", "english": "yesterday"},
        {"hanzi": "时候", "pinyin": "shíhou", "english": "time / moment"},
        {"hanzi": "上午", "pinyin": "shàngwǔ", "english": "morning"},
        {"hanzi": "下午", "pinyin": "xiàwǔ", "english": "afternoon"},
        {"hanzi": "现在", "pinyin": "xiànzài", "english": "now"},
        # ── Verbs ──
        {"hanzi": "是", "pinyin": "shì", "english": "to be"},
        {"hanzi": "有", "pinyin": "yǒu", "english": "to have"},
        {"hanzi": "看", "pinyin": "kàn", "english": "to look / to see"},
        {"hanzi": "听", "pinyin": "tīng", "english": "to listen"},
        {"hanzi": "说", "pinyin": "shuō", "english": "to speak / to say"},
        {"hanzi": "读", "pinyin": "dú", "english": "to read"},
        {"hanzi": "写", "pinyin": "xiě", "english": "to write"},
        {"hanzi": "学习", "pinyin": "xuéxí", "english": "to study / to learn"},
        {"hanzi": "工作", "pinyin": "gōngzuò", "english": "to work / work"},
        {"hanzi": "住", "pinyin": "zhù", "english": "to live"},
        {"hanzi": "吃", "pinyin": "chī", "english": "to eat"},
        {"hanzi": "喝", "pinyin": "hē", "english": "to drink"},
        {"hanzi": "买", "pinyin": "mǎi", "english": "to buy"},
        {"hanzi": "去", "pinyin": "qù", "english": "to go"},
        {"hanzi": "来", "pinyin": "lái", "english": "to come"},
        {"hanzi": "回", "pinyin": "huí", "english": "to return"},
        {"hanzi": "做", "pinyin": "zuò", "english": "to do / to make"},
        {"hanzi": "坐", "pinyin": "zuò", "english": "to sit"},
        {"hanzi": "打电话", "pinyin": "dǎ diànhuà", "english": "to make a phone call"},
        {"hanzi": "想", "pinyin": "xiǎng", "english": "to think / to want"},
        {"hanzi": "喜欢", "pinyin": "xǐhuan", "english": "to like"},
        {"hanzi": "爱", "pinyin": "ài", "english": "to love"},
        {"hanzi": "叫", "pinyin": "jiào", "english": "to call / to be called"},
        {"hanzi": "开", "pinyin": "kāi", "english": "to open / to drive"},
        {"hanzi": "睡觉", "pinyin": "shuìjiào", "english": "to sleep"},
        {"hanzi": "认识", "pinyin": "rènshi", "english": "to know (someone)"},
        {"hanzi": "会", "pinyin": "huì", "english": "can / will"},
        {"hanzi": "能", "pinyin": "néng", "english": "can / able to"},
        # ── Adjectives ──
        {"hanzi": "好", "pinyin": "hǎo", "english": "good"},
        {"hanzi": "大", "pinyin": "dà", "english": "big"},
        {"hanzi": "小", "pinyin": "xiǎo", "english": "small"},
        {"hanzi": "多", "pinyin": "duō", "english": "many / much"},
        {"hanzi": "少", "pinyin": "shǎo", "english": "few / little"},
        {"hanzi": "冷", "pinyin": "lěng", "english": "cold"},
        {"hanzi": "热", "pinyin": "rè", "english": "hot"},
        {"hanzi": "高兴", "pinyin": "gāoxìng", "english": "happy"},
        {"hanzi": "漂亮", "pinyin": "piàoliang", "english": "pretty / beautiful"},
        # ── Nouns – Places & Objects ──
        {"hanzi": "中国", "pinyin": "Zhōngguó", "english": "China"},
        {"hanzi": "北京", "pinyin": "Běijīng", "english": "Beijing"},
        {"hanzi": "家", "pinyin": "jiā", "english": "home / family"},
        {"hanzi": "学校", "pinyin": "xuéxiào", "english": "school"},
        {"hanzi": "饭店", "pinyin": "fàndiàn", "english": "restaurant / hotel"},
        {"hanzi": "商店", "pinyin": "shāngdiàn", "english": "shop / store"},
        {"hanzi": "医院", "pinyin": "yīyuàn", "english": "hospital"},
        {"hanzi": "火车站", "pinyin": "huǒchē zhàn", "english": "train station"},
        {"hanzi": "飞机", "pinyin": "fēijī", "english": "airplane"},
        {"hanzi": "出租车", "pinyin": "chūzūchē", "english": "taxi"},
        {"hanzi": "电脑", "pinyin": "diànnǎo", "english": "computer"},
        {"hanzi": "电视", "pinyin": "diànshì", "english": "television"},
        {"hanzi": "电影", "pinyin": "diànyǐng", "english": "movie"},
        {"hanzi": "书", "pinyin": "shū", "english": "book"},
        {"hanzi": "桌子", "pinyin": "zhuōzi", "english": "table / desk"},
        {"hanzi": "椅子", "pinyin": "yǐzi", "english": "chair"},
        {"hanzi": "水", "pinyin": "shuǐ", "english": "water"},
        {"hanzi": "茶", "pinyin": "chá", "english": "tea"},
        {"hanzi": "米饭", "pinyin": "mǐfàn", "english": "rice"},
        {"hanzi": "水果", "pinyin": "shuǐguǒ", "english": "fruit"},
        {"hanzi": "苹果", "pinyin": "píngguǒ", "english": "apple"},
        {"hanzi": "菜", "pinyin": "cài", "english": "dish / vegetable"},
        {"hanzi": "天气", "pinyin": "tiānqì", "english": "weather"},
        {"hanzi": "钱", "pinyin": "qián", "english": "money"},
        {"hanzi": "猫", "pinyin": "māo", "english": "cat"},
        {"hanzi": "狗", "pinyin": "gǒu", "english": "dog"},
        {"hanzi": "衣服", "pinyin": "yīfu", "english": "clothes"},
        {"hanzi": "名字", "pinyin": "míngzi", "english": "name"},
        # ── Grammar & Particles ──
        {"hanzi": "的", "pinyin": "de", "english": "possessive / descriptive particle"},
        {"hanzi": "了", "pinyin": "le", "english": "completed action particle"},
        {"hanzi": "不", "pinyin": "bù", "english": "not / no"},
        {"hanzi": "没", "pinyin": "méi", "english": "not (have)"},
        {"hanzi": "在", "pinyin": "zài", "english": "at / in / (ongoing action)"},
        {"hanzi": "很", "pinyin": "hěn", "english": "very"},
        {"hanzi": "都", "pinyin": "dōu", "english": "all / both"},
        {"hanzi": "也", "pinyin": "yě", "english": "also"},
        {"hanzi": "和", "pinyin": "hé", "english": "and"},
        {"hanzi": "吗", "pinyin": "ma", "english": "question particle"},
        {"hanzi": "呢", "pinyin": "ne", "english": "question particle (and you?)"},
        {"hanzi": "太", "pinyin": "tài", "english": "too (excessive)"},
        # ── Prepositions & Location ──
        {"hanzi": "上", "pinyin": "shàng", "english": "above / on"},
        {"hanzi": "下", "pinyin": "xià", "english": "below / under"},
        {"hanzi": "前面", "pinyin": "qiánmiàn", "english": "front / ahead"},
        {"hanzi": "后面", "pinyin": "hòumiàn", "english": "behind"},
        {"hanzi": "里面", "pinyin": "lǐmiàn", "english": "inside"},
        {"hanzi": "对不起", "pinyin": "duìbuqǐ", "english": "sorry"},
        {"hanzi": "谢谢", "pinyin": "xièxie", "english": "thank you"},
        {"hanzi": "再见", "pinyin": "zàijiàn", "english": "goodbye"},
        {"hanzi": "请", "pinyin": "qǐng", "english": "please"},
        {"hanzi": "你好", "pinyin": "nǐ hǎo", "english": "hello"},
    ],
    2: [
        # ── Verbs ──
        {"hanzi": "准备", "pinyin": "zhǔnbèi", "english": "to prepare"},
        {"hanzi": "帮忙", "pinyin": "bāngmáng", "english": "to help"},
        {"hanzi": "告诉", "pinyin": "gàosu", "english": "to tell"},
        {"hanzi": "知道", "pinyin": "zhīdao", "english": "to know (a fact)"},
        {"hanzi": "觉得", "pinyin": "juéde", "english": "to feel / to think"},
        {"hanzi": "希望", "pinyin": "xīwàng", "english": "to hope / to wish"},
        {"hanzi": "开始", "pinyin": "kāishǐ", "english": "to begin / to start"},
        {"hanzi": "完", "pinyin": "wán", "english": "to finish"},
        {"hanzi": "给", "pinyin": "gěi", "english": "to give"},
        {"hanzi": "找", "pinyin": "zhǎo", "english": "to find / to look for"},
        {"hanzi": "到", "pinyin": "dào", "english": "to arrive"},
        {"hanzi": "等", "pinyin": "děng", "english": "to wait"},
        {"hanzi": "送", "pinyin": "sòng", "english": "to give (a gift) / to send"},
        {"hanzi": "让", "pinyin": "ràng", "english": "to let / to allow"},
        {"hanzi": "走", "pinyin": "zǒu", "english": "to walk"},
        {"hanzi": "跑", "pinyin": "pǎo", "english": "to run"},
        {"hanzi": "玩", "pinyin": "wán", "english": "to play / to have fun"},
        {"hanzi": "唱歌", "pinyin": "chànggē", "english": "to sing"},
        {"hanzi": "跳舞", "pinyin": "tiàowǔ", "english": "to dance"},
        {"hanzi": "旅游", "pinyin": "lǚyóu", "english": "to travel"},
        {"hanzi": "游泳", "pinyin": "yóuyǒng", "english": "to swim"},
        {"hanzi": "锻炼", "pinyin": "duànliàn", "english": "to exercise"},
        {"hanzi": "生病", "pinyin": "shēngbìng", "english": "to get sick"},
        {"hanzi": "穿", "pinyin": "chuān", "english": "to wear"},
        {"hanzi": "洗", "pinyin": "xǐ", "english": "to wash"},
        {"hanzi": "教", "pinyin": "jiāo", "english": "to teach"},
        {"hanzi": "笑", "pinyin": "xiào", "english": "to laugh / to smile"},
        {"hanzi": "哭", "pinyin": "kū", "english": "to cry"},
        {"hanzi": "关", "pinyin": "guān", "english": "to close / to turn off"},
        {"hanzi": "试", "pinyin": "shì", "english": "to try"},
        {"hanzi": "用", "pinyin": "yòng", "english": "to use"},
        {"hanzi": "拿", "pinyin": "ná", "english": "to take / to hold"},
        {"hanzi": "搬", "pinyin": "bān", "english": "to move (objects)"},
        {"hanzi": "回答", "pinyin": "huídá", "english": "to answer"},
        {"hanzi": "问", "pinyin": "wèn", "english": "to ask"},
        {"hanzi": "介绍", "pinyin": "jièshào", "english": "to introduce"},
        {"hanzi": "担心", "pinyin": "dānxīn", "english": "to worry"},
        {"hanzi": "了解", "pinyin": "liǎojiě", "english": "to understand"},
        {"hanzi": "相信", "pinyin": "xiāngxìn", "english": "to believe"},
        {"hanzi": "注意", "pinyin": "zhùyì", "english": "to pay attention"},
        # ── Adjectives ──
        {"hanzi": "长", "pinyin": "cháng", "english": "long"},
        {"hanzi": "短", "pinyin": "duǎn", "english": "short (length)"},
        {"hanzi": "新", "pinyin": "xīn", "english": "new"},
        {"hanzi": "旧", "pinyin": "jiù", "english": "old (things)"},
        {"hanzi": "快", "pinyin": "kuài", "english": "fast / quick"},
        {"hanzi": "慢", "pinyin": "màn", "english": "slow"},
        {"hanzi": "远", "pinyin": "yuǎn", "english": "far"},
        {"hanzi": "近", "pinyin": "jìn", "english": "near / close"},
        {"hanzi": "贵", "pinyin": "guì", "english": "expensive"},
        {"hanzi": "便宜", "pinyin": "piányi", "english": "cheap"},
        {"hanzi": "难", "pinyin": "nán", "english": "difficult"},
        {"hanzi": "容易", "pinyin": "róngyì", "english": "easy"},
        {"hanzi": "忙", "pinyin": "máng", "english": "busy"},
        {"hanzi": "累", "pinyin": "lèi", "english": "tired"},
        {"hanzi": "晴", "pinyin": "qíng", "english": "sunny / clear"},
        {"hanzi": "阴", "pinyin": "yīn", "english": "cloudy / overcast"},
        {"hanzi": "重要", "pinyin": "zhòngyào", "english": "important"},
        {"hanzi": "特别", "pinyin": "tèbié", "english": "special / especially"},
        {"hanzi": "安静", "pinyin": "ānjìng", "english": "quiet"},
        {"hanzi": "干净", "pinyin": "gānjìng", "english": "clean"},
        # ── Nouns ──
        {"hanzi": "眼睛", "pinyin": "yǎnjing", "english": "eye"},
        {"hanzi": "鼻子", "pinyin": "bízi", "english": "nose"},
        {"hanzi": "耳朵", "pinyin": "ěrduo", "english": "ear"},
        {"hanzi": "嘴", "pinyin": "zuǐ", "english": "mouth"},
        {"hanzi": "头", "pinyin": "tóu", "english": "head"},
        {"hanzi": "手", "pinyin": "shǒu", "english": "hand"},
        {"hanzi": "脚", "pinyin": "jiǎo", "english": "foot"},
        {"hanzi": "身体", "pinyin": "shēntǐ", "english": "body / health"},
        {"hanzi": "脸", "pinyin": "liǎn", "english": "face"},
        {"hanzi": "腿", "pinyin": "tuǐ", "english": "leg"},
        {"hanzi": "春天", "pinyin": "chūntiān", "english": "spring"},
        {"hanzi": "夏天", "pinyin": "xiàtiān", "english": "summer"},
        {"hanzi": "秋天", "pinyin": "qiūtiān", "english": "autumn"},
        {"hanzi": "冬天", "pinyin": "dōngtiān", "english": "winter"},
        {"hanzi": "花", "pinyin": "huā", "english": "flower"},
        {"hanzi": "树", "pinyin": "shù", "english": "tree"},
        {"hanzi": "鸟", "pinyin": "niǎo", "english": "bird"},
        {"hanzi": "鱼", "pinyin": "yú", "english": "fish"},
        {"hanzi": "牛奶", "pinyin": "niúnǎi", "english": "milk"},
        {"hanzi": "鸡蛋", "pinyin": "jīdàn", "english": "egg"},
        {"hanzi": "面条", "pinyin": "miàntiáo", "english": "noodles"},
        {"hanzi": "西瓜", "pinyin": "xīguā", "english": "watermelon"},
        {"hanzi": "药", "pinyin": "yào", "english": "medicine"},
        {"hanzi": "颜色", "pinyin": "yánsè", "english": "color"},
        {"hanzi": "红", "pinyin": "hóng", "english": "red"},
        {"hanzi": "黑", "pinyin": "hēi", "english": "black"},
        {"hanzi": "白", "pinyin": "bái", "english": "white"},
        {"hanzi": "绿", "pinyin": "lǜ", "english": "green"},
        {"hanzi": "蓝", "pinyin": "lán", "english": "blue"},
        {"hanzi": "黄", "pinyin": "huáng", "english": "yellow"},
        {"hanzi": "教室", "pinyin": "jiàoshì", "english": "classroom"},
        {"hanzi": "图书馆", "pinyin": "túshūguǎn", "english": "library"},
        {"hanzi": "公园", "pinyin": "gōngyuán", "english": "park"},
        {"hanzi": "银行", "pinyin": "yínháng", "english": "bank"},
        {"hanzi": "超市", "pinyin": "chāoshì", "english": "supermarket"},
        {"hanzi": "机场", "pinyin": "jīchǎng", "english": "airport"},
        {"hanzi": "地铁", "pinyin": "dìtiě", "english": "subway"},
        {"hanzi": "公共汽车", "pinyin": "gōnggòng qìchē", "english": "bus"},
        {"hanzi": "自行车", "pinyin": "zìxíngchē", "english": "bicycle"},
        {"hanzi": "地图", "pinyin": "dìtú", "english": "map"},
        {"hanzi": "护照", "pinyin": "hùzhào", "english": "passport"},
        {"hanzi": "手机", "pinyin": "shǒujī", "english": "mobile phone"},
        {"hanzi": "照片", "pinyin": "zhàopiàn", "english": "photo"},
        {"hanzi": "报纸", "pinyin": "bàozhǐ", "english": "newspaper"},
        {"hanzi": "故事", "pinyin": "gùshi", "english": "story"},
        {"hanzi": "生日", "pinyin": "shēngrì", "english": "birthday"},
        {"hanzi": "节日", "pinyin": "jiérì", "english": "festival / holiday"},
        {"hanzi": "礼物", "pinyin": "lǐwù", "english": "gift / present"},
        {"hanzi": "作业", "pinyin": "zuòyè", "english": "homework"},
        {"hanzi": "考试", "pinyin": "kǎoshì", "english": "exam / test"},
        {"hanzi": "成绩", "pinyin": "chéngjì", "english": "score / grade"},
        {"hanzi": "问题", "pinyin": "wèntí", "english": "question / problem"},
        {"hanzi": "办法", "pinyin": "bànfǎ", "english": "method / way"},
        {"hanzi": "经理", "pinyin": "jīnglǐ", "english": "manager"},
        {"hanzi": "邻居", "pinyin": "línjū", "english": "neighbor"},
        {"hanzi": "丈夫", "pinyin": "zhàngfu", "english": "husband"},
        {"hanzi": "妻子", "pinyin": "qīzi", "english": "wife"},
        {"hanzi": "爷爷", "pinyin": "yéye", "english": "grandfather (paternal)"},
        {"hanzi": "奶奶", "pinyin": "nǎinai", "english": "grandmother (paternal)"},
        {"hanzi": "哥哥", "pinyin": "gēge", "english": "older brother"},
        {"hanzi": "姐姐", "pinyin": "jiějie", "english": "older sister"},
        {"hanzi": "弟弟", "pinyin": "dìdi", "english": "younger brother"},
        {"hanzi": "妹妹", "pinyin": "mèimei", "english": "younger sister"},
        # ── Grammar & Adverbs ──
        {"hanzi": "已经", "pinyin": "yǐjīng", "english": "already"},
        {"hanzi": "一直", "pinyin": "yìzhí", "english": "always / all along"},
        {"hanzi": "还是", "pinyin": "háishi", "english": "or (in questions)"},
        {"hanzi": "或者", "pinyin": "huòzhě", "english": "or (in statements)"},
        {"hanzi": "虽然", "pinyin": "suīrán", "english": "although"},
        {"hanzi": "但是", "pinyin": "dànshì", "english": "but / however"},
        {"hanzi": "因为", "pinyin": "yīnwèi", "english": "because"},
        {"hanzi": "所以", "pinyin": "suǒyǐ", "english": "so / therefore"},
        {"hanzi": "如果", "pinyin": "rúguǒ", "english": "if"},
        {"hanzi": "可能", "pinyin": "kěnéng", "english": "possible / maybe"},
        {"hanzi": "一定", "pinyin": "yídìng", "english": "certainly / definitely"},
        {"hanzi": "必须", "pinyin": "bìxū", "english": "must / have to"},
        {"hanzi": "应该", "pinyin": "yīnggāi", "english": "should"},
        {"hanzi": "可以", "pinyin": "kěyǐ", "english": "may / can"},
        {"hanzi": "非常", "pinyin": "fēicháng", "english": "very / extremely"},
        {"hanzi": "比较", "pinyin": "bǐjiào", "english": "comparatively / fairly"},
        {"hanzi": "最", "pinyin": "zuì", "english": "most / -est"},
        {"hanzi": "比", "pinyin": "bǐ", "english": "compared to"},
        {"hanzi": "越来越", "pinyin": "yuè lái yuè", "english": "more and more"},
        {"hanzi": "马上", "pinyin": "mǎshàng", "english": "immediately / at once"},
        {"hanzi": "一起", "pinyin": "yìqǐ", "english": "together"},
        {"hanzi": "刚才", "pinyin": "gāngcái", "english": "just now"},
        {"hanzi": "经常", "pinyin": "jīngcháng", "english": "often"},
        {"hanzi": "总是", "pinyin": "zǒngshì", "english": "always"},
        {"hanzi": "终于", "pinyin": "zhōngyú", "english": "finally"},
        {"hanzi": "差不多", "pinyin": "chàbuduō", "english": "almost / about the same"},
        {"hanzi": "当然", "pinyin": "dāngrán", "english": "of course"},
        {"hanzi": "除了", "pinyin": "chúle", "english": "besides / except"},
        {"hanzi": "根据", "pinyin": "gēnjù", "english": "according to"},
        {"hanzi": "其实", "pinyin": "qíshí", "english": "actually / in fact"},
        {"hanzi": "只", "pinyin": "zhǐ", "english": "only"},
        {"hanzi": "才", "pinyin": "cái", "english": "only then / just"},
        {"hanzi": "就", "pinyin": "jiù", "english": "then / just / precisely"},
        {"hanzi": "又", "pinyin": "yòu", "english": "again (past)"},
        {"hanzi": "再", "pinyin": "zài", "english": "again (future)"},
        {"hanzi": "还", "pinyin": "hái", "english": "still / also"},
        {"hanzi": "从", "pinyin": "cóng", "english": "from"},
        {"hanzi": "离", "pinyin": "lí", "english": "away from"},
        {"hanzi": "向", "pinyin": "xiàng", "english": "toward"},
        {"hanzi": "对", "pinyin": "duì", "english": "correct / toward"},
        {"hanzi": "把", "pinyin": "bǎ", "english": "object-moving particle (bǎ)"},
        {"hanzi": "被", "pinyin": "bèi", "english": "passive marker"},
        {"hanzi": "着", "pinyin": "zhe", "english": "ongoing action particle"},
        {"hanzi": "过", "pinyin": "guò", "english": "experiential particle"},
        {"hanzi": "得", "pinyin": "de", "english": "complement particle"},
        {"hanzi": "地", "pinyin": "de", "english": "adverbial particle"},
    ],
    3: [
        # ── Verbs (expanded) ──
        {"hanzi": "表示", "pinyin": "biǎoshì", "english": "to express / to indicate"},
        {"hanzi": "表演", "pinyin": "biǎoyǎn", "english": "to perform"},
        {"hanzi": "参加", "pinyin": "cānjiā", "english": "to participate"},
        {"hanzi": "迟到", "pinyin": "chídào", "english": "to be late"},
        {"hanzi": "出发", "pinyin": "chūfā", "english": "to set off / to depart"},
        {"hanzi": "打扫", "pinyin": "dǎsǎo", "english": "to clean up"},
        {"hanzi": "打算", "pinyin": "dǎsuàn", "english": "to plan / to intend"},
        {"hanzi": "发现", "pinyin": "fāxiàn", "english": "to discover"},
        {"hanzi": "放", "pinyin": "fàng", "english": "to put / to place"},
        {"hanzi": "改变", "pinyin": "gǎibiàn", "english": "to change"},
        {"hanzi": "感觉", "pinyin": "gǎnjué", "english": "to feel / feeling"},
        {"hanzi": "感谢", "pinyin": "gǎnxiè", "english": "to thank / to be grateful"},
        {"hanzi": "干", "pinyin": "gàn", "english": "to do / to work"},
        {"hanzi": "挂", "pinyin": "guà", "english": "to hang"},
        {"hanzi": "害怕", "pinyin": "hàipà", "english": "to be afraid"},
        {"hanzi": "合适", "pinyin": "héshì", "english": "suitable / appropriate"},
        {"hanzi": "花", "pinyin": "huā", "english": "to spend (money/time)"},
        {"hanzi": "获得", "pinyin": "huòdé", "english": "to obtain / to gain"},
        {"hanzi": "检查", "pinyin": "jiǎnchá", "english": "to inspect / to check"},
        {"hanzi": "减少", "pinyin": "jiǎnshǎo", "english": "to reduce / to decrease"},
        {"hanzi": "建议", "pinyin": "jiànyì", "english": "to suggest / suggestion"},
        {"hanzi": "解决", "pinyin": "jiějué", "english": "to solve / to resolve"},
        {"hanzi": "接", "pinyin": "jiē", "english": "to receive / to pick up"},
        {"hanzi": "借", "pinyin": "jiè", "english": "to borrow / to lend"},
        {"hanzi": "进步", "pinyin": "jìnbù", "english": "to improve / progress"},
        {"hanzi": "竞争", "pinyin": "jìngzhēng", "english": "to compete / competition"},
        {"hanzi": "举行", "pinyin": "jǔxíng", "english": "to hold (an event)"},
        {"hanzi": "决定", "pinyin": "juédìng", "english": "to decide"},
        {"hanzi": "考虑", "pinyin": "kǎolǜ", "english": "to consider"},
        {"hanzi": "拉", "pinyin": "lā", "english": "to pull"},
        {"hanzi": "留", "pinyin": "liú", "english": "to stay / to keep"},
        {"hanzi": "联系", "pinyin": "liánxì", "english": "to contact"},
        {"hanzi": "满意", "pinyin": "mǎnyì", "english": "to be satisfied"},
        {"hanzi": "梦", "pinyin": "mèng", "english": "to dream / dream"},
        {"hanzi": "弄", "pinyin": "nòng", "english": "to make / to handle"},
        {"hanzi": "排列", "pinyin": "páiliè", "english": "to arrange"},
        {"hanzi": "陪", "pinyin": "péi", "english": "to accompany"},
        {"hanzi": "批评", "pinyin": "pīpíng", "english": "to criticize"},
        {"hanzi": "骑", "pinyin": "qí", "english": "to ride (a bicycle/horse)"},
        {"hanzi": "请假", "pinyin": "qǐngjià", "english": "to ask for leave"},
        {"hanzi": "取", "pinyin": "qǔ", "english": "to take / to fetch"},
        {"hanzi": "缺少", "pinyin": "quēshǎo", "english": "to lack"},
        {"hanzi": "散步", "pinyin": "sànbù", "english": "to take a walk"},
        {"hanzi": "失败", "pinyin": "shībài", "english": "to fail / failure"},
        {"hanzi": "使用", "pinyin": "shǐyòng", "english": "to use"},
        {"hanzi": "收", "pinyin": "shōu", "english": "to receive / to collect"},
        {"hanzi": "输", "pinyin": "shū", "english": "to lose (a game)"},
        {"hanzi": "提高", "pinyin": "tígāo", "english": "to improve / to raise"},
        {"hanzi": "提供", "pinyin": "tígōng", "english": "to provide"},
        {"hanzi": "提醒", "pinyin": "tíxǐng", "english": "to remind"},
        {"hanzi": "讨论", "pinyin": "tǎolùn", "english": "to discuss"},
        {"hanzi": "通过", "pinyin": "tōngguò", "english": "to pass through"},
        {"hanzi": "推", "pinyin": "tuī", "english": "to push"},
        {"hanzi": "完成", "pinyin": "wánchéng", "english": "to complete"},
        {"hanzi": "误会", "pinyin": "wùhuì", "english": "to misunderstand"},
        {"hanzi": "吸引", "pinyin": "xīyǐn", "english": "to attract"},
        {"hanzi": "选择", "pinyin": "xuǎnzé", "english": "to choose"},
        {"hanzi": "要求", "pinyin": "yāoqiú", "english": "to require / requirement"},
        {"hanzi": "赢", "pinyin": "yíng", "english": "to win"},
        {"hanzi": "影响", "pinyin": "yǐngxiǎng", "english": "to influence / influence"},
        {"hanzi": "约", "pinyin": "yuē", "english": "to make an appointment"},
        {"hanzi": "允许", "pinyin": "yǔnxǔ", "english": "to allow"},
        {"hanzi": "增加", "pinyin": "zēngjiā", "english": "to increase"},
        {"hanzi": "占", "pinyin": "zhàn", "english": "to occupy"},
        {"hanzi": "值得", "pinyin": "zhídé", "english": "to be worth"},
        {"hanzi": "支持", "pinyin": "zhīchí", "english": "to support"},
        {"hanzi": "组织", "pinyin": "zǔzhī", "english": "to organize / organization"},
        {"hanzi": "尊重", "pinyin": "zūnzhòng", "english": "to respect"},
        # ── Adjectives (expanded) ──
        {"hanzi": "诚实", "pinyin": "chéngshí", "english": "honest"},
        {"hanzi": "聪明", "pinyin": "cōngmíng", "english": "smart / intelligent"},
        {"hanzi": "粗心", "pinyin": "cūxīn", "english": "careless"},
        {"hanzi": "大概", "pinyin": "dàgài", "english": "roughly / probably"},
        {"hanzi": "丰富", "pinyin": "fēngfù", "english": "rich / abundant"},
        {"hanzi": "复杂", "pinyin": "fùzá", "english": "complicated"},
        {"hanzi": "孤单", "pinyin": "gūdān", "english": "lonely"},
        {"hanzi": "合格", "pinyin": "hégé", "english": "qualified"},
        {"hanzi": "厚", "pinyin": "hòu", "english": "thick"},
        {"hanzi": "积极", "pinyin": "jījí", "english": "active / positive"},
        {"hanzi": "及时", "pinyin": "jíshí", "english": "timely"},
        {"hanzi": "简单", "pinyin": "jiǎndān", "english": "simple"},
        {"hanzi": "紧张", "pinyin": "jǐnzhāng", "english": "nervous / tense"},
        {"hanzi": "精彩", "pinyin": "jīngcǎi", "english": "wonderful / brilliant"},
        {"hanzi": "开心", "pinyin": "kāixīn", "english": "happy / joyful"},
        {"hanzi": "可爱", "pinyin": "kě'ài", "english": "cute / lovely"},
        {"hanzi": "可怜", "pinyin": "kělián", "english": "pitiful"},
        {"hanzi": "苦", "pinyin": "kǔ", "english": "bitter"},
        {"hanzi": "辣", "pinyin": "là", "english": "spicy"},
        {"hanzi": "甜", "pinyin": "tián", "english": "sweet"},
        {"hanzi": "酸", "pinyin": "suān", "english": "sour"},
        {"hanzi": "咸", "pinyin": "xián", "english": "salty"},
        {"hanzi": "浪漫", "pinyin": "làngmàn", "english": "romantic"},
        {"hanzi": "乐观", "pinyin": "lèguān", "english": "optimistic"},
        {"hanzi": "厉害", "pinyin": "lìhai", "english": "amazing / intense"},
        {"hanzi": "美丽", "pinyin": "měilì", "english": "beautiful"},
        {"hanzi": "耐心", "pinyin": "nàixīn", "english": "patient / patience"},
        {"hanzi": "暖和", "pinyin": "nuǎnhuo", "english": "warm"},
        {"hanzi": "胖", "pinyin": "pàng", "english": "fat / overweight"},
        {"hanzi": "瘦", "pinyin": "shòu", "english": "thin / slim"},
        {"hanzi": "轻", "pinyin": "qīng", "english": "light (weight)"},
        {"hanzi": "穷", "pinyin": "qióng", "english": "poor"},
        {"hanzi": "认真", "pinyin": "rènzhēn", "english": "serious / earnest"},
        {"hanzi": "深", "pinyin": "shēn", "english": "deep"},
        {"hanzi": "生气", "pinyin": "shēngqì", "english": "angry"},
        {"hanzi": "无聊", "pinyin": "wúliáo", "english": "bored / boring"},
        {"hanzi": "幸福", "pinyin": "xìngfú", "english": "happy / blessed"},
        {"hanzi": "严格", "pinyin": "yángé", "english": "strict"},
        {"hanzi": "勇敢", "pinyin": "yǒnggǎn", "english": "brave"},
        {"hanzi": "优秀", "pinyin": "yōuxiù", "english": "excellent"},
        {"hanzi": "有趣", "pinyin": "yǒuqù", "english": "interesting / fun"},
        {"hanzi": "正常", "pinyin": "zhèngcháng", "english": "normal"},
        {"hanzi": "正确", "pinyin": "zhèngquè", "english": "correct"},
        {"hanzi": "著名", "pinyin": "zhùmíng", "english": "famous"},
        {"hanzi": "自然", "pinyin": "zìrán", "english": "natural / nature"},
        # ── Nouns (expanded) ──
        {"hanzi": "爱好", "pinyin": "àihào", "english": "hobby"},
        {"hanzi": "安全", "pinyin": "ānquán", "english": "safety / safe"},
        {"hanzi": "包", "pinyin": "bāo", "english": "bag / package"},
        {"hanzi": "报名", "pinyin": "bàomíng", "english": "to register / sign up"},
        {"hanzi": "倍", "pinyin": "bèi", "english": "times / fold"},
        {"hanzi": "本来", "pinyin": "běnlái", "english": "originally"},
        {"hanzi": "标准", "pinyin": "biāozhǔn", "english": "standard"},
        {"hanzi": "饼干", "pinyin": "bǐnggān", "english": "cookie / biscuit"},
        {"hanzi": "博物馆", "pinyin": "bówùguǎn", "english": "museum"},
        {"hanzi": "材料", "pinyin": "cáiliào", "english": "material"},
        {"hanzi": "餐厅", "pinyin": "cāntīng", "english": "dining hall / restaurant"},
        {"hanzi": "厕所", "pinyin": "cèsuǒ", "english": "bathroom / toilet"},
        {"hanzi": "长城", "pinyin": "Chángchéng", "english": "Great Wall"},
        {"hanzi": "城市", "pinyin": "chéngshì", "english": "city"},
        {"hanzi": "窗户", "pinyin": "chuānghu", "english": "window"},
        {"hanzi": "词语", "pinyin": "cíyǔ", "english": "word / term"},
        {"hanzi": "大使馆", "pinyin": "dàshǐguǎn", "english": "embassy"},
        {"hanzi": "大学", "pinyin": "dàxué", "english": "university"},
        {"hanzi": "道理", "pinyin": "dàolǐ", "english": "reason / principle"},
        {"hanzi": "地方", "pinyin": "dìfang", "english": "place / location"},
        {"hanzi": "地球", "pinyin": "dìqiú", "english": "Earth"},
        {"hanzi": "调查", "pinyin": "diàochá", "english": "investigation / survey"},
        {"hanzi": "动物", "pinyin": "dòngwù", "english": "animal"},
        {"hanzi": "方法", "pinyin": "fāngfǎ", "english": "method"},
        {"hanzi": "方面", "pinyin": "fāngmiàn", "english": "aspect / respect"},
        {"hanzi": "方向", "pinyin": "fāngxiàng", "english": "direction"},
        {"hanzi": "房间", "pinyin": "fángjiān", "english": "room"},
        {"hanzi": "份", "pinyin": "fèn", "english": "measure word for portions"},
        {"hanzi": "风景", "pinyin": "fēngjǐng", "english": "scenery / landscape"},
        {"hanzi": "父母", "pinyin": "fùmǔ", "english": "parents"},
        {"hanzi": "感冒", "pinyin": "gǎnmào", "english": "cold (illness)"},
        {"hanzi": "功夫", "pinyin": "gōngfu", "english": "kung fu"},
        {"hanzi": "工资", "pinyin": "gōngzī", "english": "salary / wages"},
        {"hanzi": "共同", "pinyin": "gòngtóng", "english": "common / shared"},
        {"hanzi": "广告", "pinyin": "guǎnggào", "english": "advertisement"},
        {"hanzi": "广场", "pinyin": "guǎngchǎng", "english": "square / plaza"},
        {"hanzi": "规定", "pinyin": "guīdìng", "english": "rule / regulation"},
        {"hanzi": "国家", "pinyin": "guójiā", "english": "country / nation"},
        {"hanzi": "国际", "pinyin": "guójì", "english": "international"},
        {"hanzi": "海洋", "pinyin": "hǎiyáng", "english": "ocean"},
        {"hanzi": "汉字", "pinyin": "hànzì", "english": "Chinese character"},
        {"hanzi": "行李", "pinyin": "xíngli", "english": "luggage / baggage"},
        {"hanzi": "环境", "pinyin": "huánjìng", "english": "environment"},
        {"hanzi": "机会", "pinyin": "jīhuì", "english": "opportunity"},
        {"hanzi": "计划", "pinyin": "jìhuà", "english": "plan"},
        {"hanzi": "价格", "pinyin": "jiàgé", "english": "price"},
        {"hanzi": "交通", "pinyin": "jiāotōng", "english": "traffic / transportation"},
        {"hanzi": "结果", "pinyin": "jiéguǒ", "english": "result"},
        {"hanzi": "经济", "pinyin": "jīngjì", "english": "economy"},
        {"hanzi": "经验", "pinyin": "jīngyàn", "english": "experience"},
        {"hanzi": "句子", "pinyin": "jùzi", "english": "sentence"},
        {"hanzi": "距离", "pinyin": "jùlí", "english": "distance"},
        {"hanzi": "科学", "pinyin": "kēxué", "english": "science"},
        {"hanzi": "客人", "pinyin": "kèrén", "english": "guest / visitor"},
        {"hanzi": "空气", "pinyin": "kōngqì", "english": "air"},
        {"hanzi": "口", "pinyin": "kǒu", "english": "mouth / opening"},
        {"hanzi": "矿泉水", "pinyin": "kuàngquánshuǐ", "english": "mineral water"},
        {"hanzi": "困难", "pinyin": "kùnnan", "english": "difficulty / difficult"},
        {"hanzi": "垃圾", "pinyin": "lājī", "english": "garbage / trash"},
        {"hanzi": "历史", "pinyin": "lìshǐ", "english": "history"},
        {"hanzi": "力量", "pinyin": "lìliang", "english": "power / strength"},
        {"hanzi": "练习", "pinyin": "liànxí", "english": "to practice / exercise"},
        {"hanzi": "零食", "pinyin": "língshí", "english": "snack"},
        {"hanzi": "流行", "pinyin": "liúxíng", "english": "popular / fashionable"},
        {"hanzi": "旅行", "pinyin": "lǚxíng", "english": "to travel / trip"},
        {"hanzi": "律师", "pinyin": "lǜshī", "english": "lawyer"},
        {"hanzi": "民族", "pinyin": "mínzú", "english": "nation / ethnicity"},
        {"hanzi": "目的", "pinyin": "mùdì", "english": "purpose / goal"},
        {"hanzi": "内容", "pinyin": "nèiróng", "english": "content"},
        {"hanzi": "年龄", "pinyin": "niánlíng", "english": "age"},
        {"hanzi": "农村", "pinyin": "nóngcūn", "english": "countryside / rural area"},
        {"hanzi": "普通话", "pinyin": "pǔtōnghuà", "english": "Mandarin (standard Chinese)"},
        {"hanzi": "气候", "pinyin": "qìhòu", "english": "climate"},
        {"hanzi": "签证", "pinyin": "qiānzhèng", "english": "visa"},
        {"hanzi": "情况", "pinyin": "qíngkuàng", "english": "situation"},
        {"hanzi": "任务", "pinyin": "rènwu", "english": "task / mission"},
        {"hanzi": "日记", "pinyin": "rìjì", "english": "diary"},
        {"hanzi": "森林", "pinyin": "sēnlín", "english": "forest"},
        {"hanzi": "社会", "pinyin": "shèhuì", "english": "society"},
        {"hanzi": "世界", "pinyin": "shìjiè", "english": "world"},
        {"hanzi": "数学", "pinyin": "shùxué", "english": "mathematics"},
        {"hanzi": "速度", "pinyin": "sùdù", "english": "speed"},
        {"hanzi": "塑料袋", "pinyin": "sùliàodài", "english": "plastic bag"},
        {"hanzi": "态度", "pinyin": "tàidu", "english": "attitude"},
        {"hanzi": "条件", "pinyin": "tiáojiàn", "english": "condition / requirement"},
        {"hanzi": "同事", "pinyin": "tóngshì", "english": "colleague"},
        {"hanzi": "网站", "pinyin": "wǎngzhàn", "english": "website"},
        {"hanzi": "文化", "pinyin": "wénhuà", "english": "culture"},
        {"hanzi": "文章", "pinyin": "wénzhāng", "english": "article / essay"},
        {"hanzi": "习惯", "pinyin": "xíguàn", "english": "habit / to be used to"},
        {"hanzi": "信息", "pinyin": "xìnxī", "english": "information / message"},
        {"hanzi": "性格", "pinyin": "xìnggé", "english": "personality / character"},
        {"hanzi": "学期", "pinyin": "xuéqī", "english": "semester"},
        {"hanzi": "研究", "pinyin": "yánjiū", "english": "to research / research"},
        {"hanzi": "演员", "pinyin": "yǎnyuán", "english": "actor / performer"},
        {"hanzi": "意见", "pinyin": "yìjiàn", "english": "opinion"},
        {"hanzi": "意思", "pinyin": "yìsi", "english": "meaning"},
        {"hanzi": "语法", "pinyin": "yǔfǎ", "english": "grammar"},
        {"hanzi": "语言", "pinyin": "yǔyán", "english": "language"},
        {"hanzi": "原因", "pinyin": "yuányīn", "english": "reason / cause"},
        {"hanzi": "责任", "pinyin": "zérèn", "english": "responsibility"},
        {"hanzi": "植物", "pinyin": "zhíwù", "english": "plant"},
        {"hanzi": "中文", "pinyin": "zhōngwén", "english": "Chinese (language)"},
        {"hanzi": "重点", "pinyin": "zhòngdiǎn", "english": "key point / emphasis"},
        {"hanzi": "专业", "pinyin": "zhuānyè", "english": "major / specialty"},
        {"hanzi": "自己", "pinyin": "zìjǐ", "english": "oneself"},
        {"hanzi": "作者", "pinyin": "zuòzhě", "english": "author / writer"},
    ],
}

# All HSK levels available in this module
AVAILABLE_LEVELS = sorted(HSK_VOCAB.keys())


def get_words(level: int) -> List[Dict[str, str]]:
    """Return all vocabulary words for a given HSK level."""
    if level not in HSK_VOCAB:
        raise ValueError(
            f"HSK level {level} not available. Choose from: {AVAILABLE_LEVELS}"
        )
    return list(HSK_VOCAB[level])


def get_cumulative_words(level: int) -> List[Dict[str, str]]:
    """Return all vocabulary words up to and including the given HSK level."""
    if level not in HSK_VOCAB:
        raise ValueError(
            f"HSK level {level} not available. Choose from: {AVAILABLE_LEVELS}"
        )
    words: List[Dict[str, str]] = []
    for lvl in AVAILABLE_LEVELS:
        if lvl <= level:
            words.extend(HSK_VOCAB[lvl])
    return words


def get_random_words(level: int, count: int, cumulative: bool = True) -> List[Dict[str, str]]:
    """Return a random selection of words from the given HSK level.

    Args:
        level: HSK level (1, 2, or 3).
        count: Number of words to return.
        cumulative: If True, include words from all levels up to ``level``.
    """
    pool = get_cumulative_words(level) if cumulative else get_words(level)
    count = min(count, len(pool))
    return random.sample(pool, count)


def word_count(level: int, cumulative: bool = True) -> int:
    """Return the number of words available for a given HSK level."""
    pool = get_cumulative_words(level) if cumulative else get_words(level)
    return len(pool)
