"""HSK 1-3 vocabulary data for the Language Teacher CLI."""

HSK_BANDS = {1: "HSK Band 1 (Elementary)", 2: "HSK Band 2 (Basic)", 3: "HSK Band 3 (Intermediate)"}

CATEGORIES = [
    "noun", "verb", "adjective", "adverb", "pronoun", "conjunction",
    "preposition", "measure_word", "particle", "number", "phrase", "time_word",
]

HSK_VOCAB = [
    # =========================================================================
    # BAND 1 — Elementary
    # =========================================================================

    # --- Band 1: Pronouns ---
    {"hanzi": "我", "pinyin": "wo3", "english": "I; me", "band": 1, "category": "pronoun"},
    {"hanzi": "你", "pinyin": "ni3", "english": "you", "band": 1, "category": "pronoun"},
    {"hanzi": "他", "pinyin": "ta1", "english": "he; him", "band": 1, "category": "pronoun"},
    {"hanzi": "她", "pinyin": "ta1", "english": "she; her", "band": 1, "category": "pronoun"},
    {"hanzi": "它", "pinyin": "ta1", "english": "it", "band": 1, "category": "pronoun"},
    {"hanzi": "我们", "pinyin": "wo3 men5", "english": "we; us", "band": 1, "category": "pronoun"},
    {"hanzi": "你们", "pinyin": "ni3 men5", "english": "you (plural)", "band": 1, "category": "pronoun"},
    {"hanzi": "他们", "pinyin": "ta1 men5", "english": "they; them", "band": 1, "category": "pronoun"},
    {"hanzi": "这", "pinyin": "zhe4", "english": "this", "band": 1, "category": "pronoun"},
    {"hanzi": "那", "pinyin": "na4", "english": "that", "band": 1, "category": "pronoun"},
    {"hanzi": "哪", "pinyin": "na3", "english": "which; where", "band": 1, "category": "pronoun"},
    {"hanzi": "谁", "pinyin": "shei2", "english": "who; whom", "band": 1, "category": "pronoun"},
    {"hanzi": "什么", "pinyin": "shen2 me5", "english": "what", "band": 1, "category": "pronoun"},
    {"hanzi": "多少", "pinyin": "duo1 shao3", "english": "how many; how much", "band": 1, "category": "pronoun"},
    {"hanzi": "几", "pinyin": "ji3", "english": "how many; several", "band": 1, "category": "pronoun"},
    {"hanzi": "自己", "pinyin": "zi4 ji3", "english": "oneself", "band": 1, "category": "pronoun"},
    {"hanzi": "大家", "pinyin": "da4 jia1", "english": "everyone", "band": 1, "category": "pronoun"},
    {"hanzi": "这里", "pinyin": "zhe4 li3", "english": "here", "band": 1, "category": "pronoun"},
    {"hanzi": "那里", "pinyin": "na4 li3", "english": "there", "band": 1, "category": "pronoun"},
    {"hanzi": "哪里", "pinyin": "na3 li3", "english": "where", "band": 1, "category": "pronoun"},

    # --- Band 1: Numbers ---
    {"hanzi": "零", "pinyin": "ling2", "english": "zero", "band": 1, "category": "number"},
    {"hanzi": "一", "pinyin": "yi1", "english": "one", "band": 1, "category": "number"},
    {"hanzi": "二", "pinyin": "er4", "english": "two", "band": 1, "category": "number"},
    {"hanzi": "三", "pinyin": "san1", "english": "three", "band": 1, "category": "number"},
    {"hanzi": "四", "pinyin": "si4", "english": "four", "band": 1, "category": "number"},
    {"hanzi": "五", "pinyin": "wu3", "english": "five", "band": 1, "category": "number"},
    {"hanzi": "六", "pinyin": "liu4", "english": "six", "band": 1, "category": "number"},
    {"hanzi": "七", "pinyin": "qi1", "english": "seven", "band": 1, "category": "number"},
    {"hanzi": "八", "pinyin": "ba1", "english": "eight", "band": 1, "category": "number"},
    {"hanzi": "九", "pinyin": "jiu3", "english": "nine", "band": 1, "category": "number"},
    {"hanzi": "十", "pinyin": "shi2", "english": "ten", "band": 1, "category": "number"},
    {"hanzi": "百", "pinyin": "bai3", "english": "hundred", "band": 1, "category": "number"},
    {"hanzi": "千", "pinyin": "qian1", "english": "thousand", "band": 1, "category": "number"},
    {"hanzi": "万", "pinyin": "wan4", "english": "ten thousand", "band": 1, "category": "number"},
    {"hanzi": "两", "pinyin": "liang3", "english": "two (with measure words)", "band": 1, "category": "number"},

    # --- Band 1: Time Words ---
    {"hanzi": "今天", "pinyin": "jin1 tian1", "english": "today", "band": 1, "category": "time_word"},
    {"hanzi": "明天", "pinyin": "ming2 tian1", "english": "tomorrow", "band": 1, "category": "time_word"},
    {"hanzi": "昨天", "pinyin": "zuo2 tian1", "english": "yesterday", "band": 1, "category": "time_word"},
    {"hanzi": "现在", "pinyin": "xian4 zai4", "english": "now", "band": 1, "category": "time_word"},
    {"hanzi": "时候", "pinyin": "shi2 hou5", "english": "time; moment", "band": 1, "category": "time_word"},
    {"hanzi": "年", "pinyin": "nian2", "english": "year", "band": 1, "category": "time_word"},
    {"hanzi": "月", "pinyin": "yue4", "english": "month; moon", "band": 1, "category": "time_word"},
    {"hanzi": "日", "pinyin": "ri4", "english": "day; date", "band": 1, "category": "time_word"},
    {"hanzi": "号", "pinyin": "hao4", "english": "date; number", "band": 1, "category": "time_word"},
    {"hanzi": "星期", "pinyin": "xing1 qi1", "english": "week", "band": 1, "category": "time_word"},
    {"hanzi": "早上", "pinyin": "zao3 shang5", "english": "morning (early)", "band": 1, "category": "time_word"},
    {"hanzi": "上午", "pinyin": "shang4 wu3", "english": "morning", "band": 1, "category": "time_word"},
    {"hanzi": "中午", "pinyin": "zhong1 wu3", "english": "noon", "band": 1, "category": "time_word"},
    {"hanzi": "下午", "pinyin": "xia4 wu3", "english": "afternoon", "band": 1, "category": "time_word"},
    {"hanzi": "晚上", "pinyin": "wan3 shang5", "english": "evening; night", "band": 1, "category": "time_word"},
    {"hanzi": "小时", "pinyin": "xiao3 shi2", "english": "hour", "band": 1, "category": "time_word"},
    {"hanzi": "分钟", "pinyin": "fen1 zhong1", "english": "minute", "band": 1, "category": "time_word"},
    {"hanzi": "点", "pinyin": "dian3", "english": "o'clock; point", "band": 1, "category": "time_word"},
    {"hanzi": "今年", "pinyin": "jin1 nian2", "english": "this year", "band": 1, "category": "time_word"},
    {"hanzi": "去年", "pinyin": "qu4 nian2", "english": "last year", "band": 1, "category": "time_word"},

    # --- Band 1: Nouns (People & Family) ---
    {"hanzi": "人", "pinyin": "ren2", "english": "person; people", "band": 1, "category": "noun"},
    {"hanzi": "家", "pinyin": "jia1", "english": "home; family", "band": 1, "category": "noun"},
    {"hanzi": "爸爸", "pinyin": "ba4 ba5", "english": "father; dad", "band": 1, "category": "noun"},
    {"hanzi": "妈妈", "pinyin": "ma1 ma5", "english": "mother; mom", "band": 1, "category": "noun"},
    {"hanzi": "哥哥", "pinyin": "ge1 ge5", "english": "older brother", "band": 1, "category": "noun"},
    {"hanzi": "姐姐", "pinyin": "jie3 jie5", "english": "older sister", "band": 1, "category": "noun"},
    {"hanzi": "弟弟", "pinyin": "di4 di5", "english": "younger brother", "band": 1, "category": "noun"},
    {"hanzi": "妹妹", "pinyin": "mei4 mei5", "english": "younger sister", "band": 1, "category": "noun"},
    {"hanzi": "儿子", "pinyin": "er2 zi5", "english": "son", "band": 1, "category": "noun"},
    {"hanzi": "女儿", "pinyin": "nv3 er2", "english": "daughter", "band": 1, "category": "noun"},
    {"hanzi": "孩子", "pinyin": "hai2 zi5", "english": "child; children", "band": 1, "category": "noun"},
    {"hanzi": "先生", "pinyin": "xian1 sheng1", "english": "Mr.; sir; husband", "band": 1, "category": "noun"},
    {"hanzi": "小姐", "pinyin": "xiao3 jie3", "english": "Miss; young lady", "band": 1, "category": "noun"},
    {"hanzi": "朋友", "pinyin": "peng2 you5", "english": "friend", "band": 1, "category": "noun"},
    {"hanzi": "同学", "pinyin": "tong2 xue2", "english": "classmate", "band": 1, "category": "noun"},
    {"hanzi": "老师", "pinyin": "lao3 shi1", "english": "teacher", "band": 1, "category": "noun"},
    {"hanzi": "学生", "pinyin": "xue2 sheng1", "english": "student", "band": 1, "category": "noun"},

    # --- Band 1: Nouns (Food & Drink) ---
    {"hanzi": "米饭", "pinyin": "mi3 fan4", "english": "cooked rice", "band": 1, "category": "noun"},
    {"hanzi": "面条", "pinyin": "mian4 tiao2", "english": "noodles", "band": 1, "category": "noun"},
    {"hanzi": "水果", "pinyin": "shui3 guo3", "english": "fruit", "band": 1, "category": "noun"},
    {"hanzi": "苹果", "pinyin": "ping2 guo3", "english": "apple", "band": 1, "category": "noun"},
    {"hanzi": "菜", "pinyin": "cai4", "english": "dish; vegetable", "band": 1, "category": "noun"},
    {"hanzi": "鸡蛋", "pinyin": "ji1 dan4", "english": "egg", "band": 1, "category": "noun"},
    {"hanzi": "鱼", "pinyin": "yu2", "english": "fish", "band": 1, "category": "noun"},
    {"hanzi": "肉", "pinyin": "rou4", "english": "meat", "band": 1, "category": "noun"},
    {"hanzi": "牛奶", "pinyin": "niu2 nai3", "english": "milk", "band": 1, "category": "noun"},
    {"hanzi": "水", "pinyin": "shui3", "english": "water", "band": 1, "category": "noun"},
    {"hanzi": "茶", "pinyin": "cha2", "english": "tea", "band": 1, "category": "noun"},
    {"hanzi": "咖啡", "pinyin": "ka1 fei1", "english": "coffee", "band": 1, "category": "noun"},

    # --- Band 1: Nouns (Places) ---
    {"hanzi": "中国", "pinyin": "zhong1 guo2", "english": "China", "band": 1, "category": "noun"},
    {"hanzi": "北京", "pinyin": "bei3 jing1", "english": "Beijing", "band": 1, "category": "noun"},
    {"hanzi": "学校", "pinyin": "xue2 xiao4", "english": "school", "band": 1, "category": "noun"},
    {"hanzi": "医院", "pinyin": "yi1 yuan4", "english": "hospital", "band": 1, "category": "noun"},
    {"hanzi": "商店", "pinyin": "shang1 dian4", "english": "shop; store", "band": 1, "category": "noun"},
    {"hanzi": "饭店", "pinyin": "fan4 dian4", "english": "restaurant; hotel", "band": 1, "category": "noun"},
    {"hanzi": "公司", "pinyin": "gong1 si1", "english": "company", "band": 1, "category": "noun"},

    # --- Band 1: Nouns (Things & Misc) ---
    {"hanzi": "书", "pinyin": "shu1", "english": "book", "band": 1, "category": "noun"},
    {"hanzi": "桌子", "pinyin": "zhuo1 zi5", "english": "table; desk", "band": 1, "category": "noun"},
    {"hanzi": "椅子", "pinyin": "yi3 zi5", "english": "chair", "band": 1, "category": "noun"},
    {"hanzi": "电脑", "pinyin": "dian4 nao3", "english": "computer", "band": 1, "category": "noun"},
    {"hanzi": "电话", "pinyin": "dian4 hua4", "english": "telephone", "band": 1, "category": "noun"},
    {"hanzi": "手机", "pinyin": "shou3 ji1", "english": "mobile phone", "band": 1, "category": "noun"},
    {"hanzi": "电视", "pinyin": "dian4 shi4", "english": "television", "band": 1, "category": "noun"},
    {"hanzi": "钱", "pinyin": "qian2", "english": "money", "band": 1, "category": "noun"},
    {"hanzi": "车", "pinyin": "che1", "english": "car; vehicle", "band": 1, "category": "noun"},
    {"hanzi": "猫", "pinyin": "mao1", "english": "cat", "band": 1, "category": "noun"},
    {"hanzi": "狗", "pinyin": "gou3", "english": "dog", "band": 1, "category": "noun"},
    {"hanzi": "衣服", "pinyin": "yi1 fu5", "english": "clothes", "band": 1, "category": "noun"},
    {"hanzi": "东西", "pinyin": "dong1 xi5", "english": "thing; stuff", "band": 1, "category": "noun"},
    {"hanzi": "名字", "pinyin": "ming2 zi5", "english": "name", "band": 1, "category": "noun"},
    {"hanzi": "汉语", "pinyin": "han4 yu3", "english": "Chinese language", "band": 1, "category": "noun"},
    {"hanzi": "字", "pinyin": "zi4", "english": "character; word", "band": 1, "category": "noun"},
    {"hanzi": "门", "pinyin": "men2", "english": "door; gate", "band": 1, "category": "noun"},
    {"hanzi": "路", "pinyin": "lu4", "english": "road; way", "band": 1, "category": "noun"},
    {"hanzi": "飞机", "pinyin": "fei1 ji1", "english": "airplane", "band": 1, "category": "noun"},
    {"hanzi": "出租车", "pinyin": "chu1 zu1 che1", "english": "taxi", "band": 1, "category": "noun"},
    {"hanzi": "天气", "pinyin": "tian1 qi4", "english": "weather", "band": 1, "category": "noun"},
    {"hanzi": "雨", "pinyin": "yu3", "english": "rain", "band": 1, "category": "noun"},
    {"hanzi": "问题", "pinyin": "wen4 ti2", "english": "question; problem", "band": 1, "category": "noun"},
    {"hanzi": "事", "pinyin": "shi4", "english": "thing; matter", "band": 1, "category": "noun"},

    # --- Band 1: Verbs ---
    {"hanzi": "是", "pinyin": "shi4", "english": "to be", "band": 1, "category": "verb"},
    {"hanzi": "有", "pinyin": "you3", "english": "to have; there is", "band": 1, "category": "verb"},
    {"hanzi": "在", "pinyin": "zai4", "english": "to be at; to be in", "band": 1, "category": "verb"},
    {"hanzi": "去", "pinyin": "qu4", "english": "to go", "band": 1, "category": "verb"},
    {"hanzi": "来", "pinyin": "lai2", "english": "to come", "band": 1, "category": "verb"},
    {"hanzi": "吃", "pinyin": "chi1", "english": "to eat", "band": 1, "category": "verb"},
    {"hanzi": "喝", "pinyin": "he1", "english": "to drink", "band": 1, "category": "verb"},
    {"hanzi": "看", "pinyin": "kan4", "english": "to look; to see; to read", "band": 1, "category": "verb"},
    {"hanzi": "听", "pinyin": "ting1", "english": "to listen; to hear", "band": 1, "category": "verb"},
    {"hanzi": "说", "pinyin": "shuo1", "english": "to speak; to say", "band": 1, "category": "verb"},
    {"hanzi": "读", "pinyin": "du2", "english": "to read aloud", "band": 1, "category": "verb"},
    {"hanzi": "写", "pinyin": "xie3", "english": "to write", "band": 1, "category": "verb"},
    {"hanzi": "做", "pinyin": "zuo4", "english": "to do; to make", "band": 1, "category": "verb"},
    {"hanzi": "买", "pinyin": "mai3", "english": "to buy", "band": 1, "category": "verb"},
    {"hanzi": "卖", "pinyin": "mai4", "english": "to sell", "band": 1, "category": "verb"},
    {"hanzi": "想", "pinyin": "xiang3", "english": "to think; to want; to miss", "band": 1, "category": "verb"},
    {"hanzi": "要", "pinyin": "yao4", "english": "to want; to need; will", "band": 1, "category": "verb"},
    {"hanzi": "会", "pinyin": "hui4", "english": "can; will; to know how to", "band": 1, "category": "verb"},
    {"hanzi": "能", "pinyin": "neng2", "english": "can; to be able to", "band": 1, "category": "verb"},
    {"hanzi": "可以", "pinyin": "ke3 yi3", "english": "may; can", "band": 1, "category": "verb"},
    {"hanzi": "喜欢", "pinyin": "xi3 huan1", "english": "to like", "band": 1, "category": "verb"},
    {"hanzi": "爱", "pinyin": "ai4", "english": "to love", "band": 1, "category": "verb"},
    {"hanzi": "叫", "pinyin": "jiao4", "english": "to call; to be called", "band": 1, "category": "verb"},
    {"hanzi": "住", "pinyin": "zhu4", "english": "to live; to stay", "band": 1, "category": "verb"},
    {"hanzi": "工作", "pinyin": "gong1 zuo4", "english": "to work; work; job", "band": 1, "category": "verb"},
    {"hanzi": "学习", "pinyin": "xue2 xi2", "english": "to study; to learn", "band": 1, "category": "verb"},
    {"hanzi": "认识", "pinyin": "ren4 shi5", "english": "to know (a person); to recognize", "band": 1, "category": "verb"},
    {"hanzi": "知道", "pinyin": "zhi1 dao4", "english": "to know (a fact)", "band": 1, "category": "verb"},
    {"hanzi": "开", "pinyin": "kai1", "english": "to open; to drive; to turn on", "band": 1, "category": "verb"},
    {"hanzi": "关", "pinyin": "guan1", "english": "to close; to turn off", "band": 1, "category": "verb"},
    {"hanzi": "回", "pinyin": "hui2", "english": "to return; to go back", "band": 1, "category": "verb"},
    {"hanzi": "给", "pinyin": "gei3", "english": "to give", "band": 1, "category": "verb"},
    {"hanzi": "请", "pinyin": "qing3", "english": "to please; to invite; to treat", "band": 1, "category": "verb"},
    {"hanzi": "坐", "pinyin": "zuo4", "english": "to sit", "band": 1, "category": "verb"},
    {"hanzi": "走", "pinyin": "zou3", "english": "to walk; to go; to leave", "band": 1, "category": "verb"},
    {"hanzi": "跑", "pinyin": "pao3", "english": "to run", "band": 1, "category": "verb"},
    {"hanzi": "睡觉", "pinyin": "shui4 jiao4", "english": "to sleep", "band": 1, "category": "verb"},
    {"hanzi": "起床", "pinyin": "qi3 chuang2", "english": "to get up", "band": 1, "category": "verb"},
    {"hanzi": "打", "pinyin": "da3", "english": "to hit; to play; to make (a call)", "band": 1, "category": "verb"},
    {"hanzi": "找", "pinyin": "zhao3", "english": "to look for; to find", "band": 1, "category": "verb"},
    {"hanzi": "用", "pinyin": "yong4", "english": "to use", "band": 1, "category": "verb"},
    {"hanzi": "穿", "pinyin": "chuan1", "english": "to wear; to put on", "band": 1, "category": "verb"},
    {"hanzi": "等", "pinyin": "deng3", "english": "to wait", "band": 1, "category": "verb"},
    {"hanzi": "进", "pinyin": "jin4", "english": "to enter", "band": 1, "category": "verb"},
    {"hanzi": "出", "pinyin": "chu1", "english": "to go out; to exit", "band": 1, "category": "verb"},
    {"hanzi": "到", "pinyin": "dao4", "english": "to arrive; to reach", "band": 1, "category": "verb"},
    {"hanzi": "送", "pinyin": "song4", "english": "to send; to deliver; to give (a gift)", "band": 1, "category": "verb"},
    {"hanzi": "玩", "pinyin": "wan2", "english": "to play; to have fun", "band": 1, "category": "verb"},

    # --- Band 1: Adjectives ---
    {"hanzi": "大", "pinyin": "da4", "english": "big; large", "band": 1, "category": "adjective"},
    {"hanzi": "小", "pinyin": "xiao3", "english": "small; little", "band": 1, "category": "adjective"},
    {"hanzi": "多", "pinyin": "duo1", "english": "many; much", "band": 1, "category": "adjective"},
    {"hanzi": "少", "pinyin": "shao3", "english": "few; little", "band": 1, "category": "adjective"},
    {"hanzi": "好", "pinyin": "hao3", "english": "good; well", "band": 1, "category": "adjective"},
    {"hanzi": "高", "pinyin": "gao1", "english": "tall; high", "band": 1, "category": "adjective"},
    {"hanzi": "长", "pinyin": "chang2", "english": "long", "band": 1, "category": "adjective"},
    {"hanzi": "冷", "pinyin": "leng3", "english": "cold", "band": 1, "category": "adjective"},
    {"hanzi": "热", "pinyin": "re4", "english": "hot", "band": 1, "category": "adjective"},
    {"hanzi": "新", "pinyin": "xin1", "english": "new", "band": 1, "category": "adjective"},
    {"hanzi": "旧", "pinyin": "jiu4", "english": "old (things)", "band": 1, "category": "adjective"},
    {"hanzi": "远", "pinyin": "yuan3", "english": "far", "band": 1, "category": "adjective"},
    {"hanzi": "近", "pinyin": "jin4", "english": "near; close", "band": 1, "category": "adjective"},
    {"hanzi": "快", "pinyin": "kuai4", "english": "fast; quick", "band": 1, "category": "adjective"},
    {"hanzi": "慢", "pinyin": "man4", "english": "slow", "band": 1, "category": "adjective"},
    {"hanzi": "漂亮", "pinyin": "piao4 liang5", "english": "beautiful; pretty", "band": 1, "category": "adjective"},
    {"hanzi": "高兴", "pinyin": "gao1 xing4", "english": "happy; glad", "band": 1, "category": "adjective"},
    {"hanzi": "忙", "pinyin": "mang2", "english": "busy", "band": 1, "category": "adjective"},
    {"hanzi": "贵", "pinyin": "gui4", "english": "expensive", "band": 1, "category": "adjective"},
    {"hanzi": "便宜", "pinyin": "pian2 yi5", "english": "cheap; inexpensive", "band": 1, "category": "adjective"},
    {"hanzi": "对", "pinyin": "dui4", "english": "correct; right", "band": 1, "category": "adjective"},
    {"hanzi": "错", "pinyin": "cuo4", "english": "wrong; incorrect", "band": 1, "category": "adjective"},
    {"hanzi": "红", "pinyin": "hong2", "english": "red", "band": 1, "category": "adjective"},
    {"hanzi": "白", "pinyin": "bai2", "english": "white", "band": 1, "category": "adjective"},
    {"hanzi": "黑", "pinyin": "hei1", "english": "black", "band": 1, "category": "adjective"},

    # --- Band 1: Adverbs ---
    {"hanzi": "很", "pinyin": "hen3", "english": "very", "band": 1, "category": "adverb"},
    {"hanzi": "也", "pinyin": "ye3", "english": "also; too", "band": 1, "category": "adverb"},
    {"hanzi": "都", "pinyin": "dou1", "english": "all; both", "band": 1, "category": "adverb"},
    {"hanzi": "不", "pinyin": "bu4", "english": "not; no", "band": 1, "category": "adverb"},
    {"hanzi": "没", "pinyin": "mei2", "english": "not (have); did not", "band": 1, "category": "adverb"},
    {"hanzi": "太", "pinyin": "tai4", "english": "too (excessively)", "band": 1, "category": "adverb"},
    {"hanzi": "真", "pinyin": "zhen1", "english": "really; truly", "band": 1, "category": "adverb"},
    {"hanzi": "最", "pinyin": "zui4", "english": "most; -est", "band": 1, "category": "adverb"},
    {"hanzi": "已经", "pinyin": "yi3 jing1", "english": "already", "band": 1, "category": "adverb"},
    {"hanzi": "正在", "pinyin": "zheng4 zai4", "english": "in the process of; -ing", "band": 1, "category": "adverb"},
    {"hanzi": "还", "pinyin": "hai2", "english": "still; yet; also", "band": 1, "category": "adverb"},
    {"hanzi": "再", "pinyin": "zai4", "english": "again; then", "band": 1, "category": "adverb"},
    {"hanzi": "就", "pinyin": "jiu4", "english": "then; just; only", "band": 1, "category": "adverb"},
    {"hanzi": "别", "pinyin": "bie2", "english": "don't", "band": 1, "category": "adverb"},

    # --- Band 1: Measure Words ---
    {"hanzi": "个", "pinyin": "ge4", "english": "general measure word", "band": 1, "category": "measure_word"},
    {"hanzi": "本", "pinyin": "ben3", "english": "measure word for books", "band": 1, "category": "measure_word"},
    {"hanzi": "块", "pinyin": "kuai4", "english": "measure word for money; piece", "band": 1, "category": "measure_word"},
    {"hanzi": "杯", "pinyin": "bei1", "english": "measure word for cups/glasses", "band": 1, "category": "measure_word"},
    {"hanzi": "些", "pinyin": "xie1", "english": "some; measure word for plural", "band": 1, "category": "measure_word"},
    {"hanzi": "口", "pinyin": "kou3", "english": "measure word for family members", "band": 1, "category": "measure_word"},

    # --- Band 1: Particles ---
    {"hanzi": "了", "pinyin": "le5", "english": "particle for completion/change", "band": 1, "category": "particle"},
    {"hanzi": "的", "pinyin": "de5", "english": "possessive/attributive particle", "band": 1, "category": "particle"},
    {"hanzi": "吗", "pinyin": "ma5", "english": "yes/no question particle", "band": 1, "category": "particle"},
    {"hanzi": "呢", "pinyin": "ne5", "english": "question particle; and you?", "band": 1, "category": "particle"},
    {"hanzi": "吧", "pinyin": "ba5", "english": "suggestion particle", "band": 1, "category": "particle"},
    {"hanzi": "过", "pinyin": "guo5", "english": "particle for past experience", "band": 1, "category": "particle"},
    {"hanzi": "着", "pinyin": "zhe5", "english": "particle for ongoing state", "band": 1, "category": "particle"},
    {"hanzi": "得", "pinyin": "de5", "english": "complement particle", "band": 1, "category": "particle"},
    {"hanzi": "地", "pinyin": "de5", "english": "adverbial particle", "band": 1, "category": "particle"},

    # --- Band 1: Conjunctions ---
    {"hanzi": "和", "pinyin": "he2", "english": "and", "band": 1, "category": "conjunction"},
    {"hanzi": "但是", "pinyin": "dan4 shi4", "english": "but; however", "band": 1, "category": "conjunction"},
    {"hanzi": "因为", "pinyin": "yin1 wei4", "english": "because", "band": 1, "category": "conjunction"},
    {"hanzi": "所以", "pinyin": "suo3 yi3", "english": "so; therefore", "band": 1, "category": "conjunction"},
    {"hanzi": "如果", "pinyin": "ru2 guo3", "english": "if", "band": 1, "category": "conjunction"},
    {"hanzi": "或者", "pinyin": "huo4 zhe3", "english": "or", "band": 1, "category": "conjunction"},

    # --- Band 1: Prepositions ---
    {"hanzi": "从", "pinyin": "cong2", "english": "from", "band": 1, "category": "preposition"},
    {"hanzi": "向", "pinyin": "xiang4", "english": "towards", "band": 1, "category": "preposition"},
    {"hanzi": "比", "pinyin": "bi3", "english": "compared to; than", "band": 1, "category": "preposition"},
    {"hanzi": "离", "pinyin": "li2", "english": "away from; from", "band": 1, "category": "preposition"},

    # --- Band 1: Phrases ---
    {"hanzi": "你好", "pinyin": "ni3 hao3", "english": "hello", "band": 1, "category": "phrase"},
    {"hanzi": "谢谢", "pinyin": "xie4 xie5", "english": "thank you", "band": 1, "category": "phrase"},
    {"hanzi": "对不起", "pinyin": "dui4 bu4 qi3", "english": "sorry", "band": 1, "category": "phrase"},
    {"hanzi": "没关系", "pinyin": "mei2 guan1 xi5", "english": "it doesn't matter; never mind", "band": 1, "category": "phrase"},
    {"hanzi": "再见", "pinyin": "zai4 jian4", "english": "goodbye", "band": 1, "category": "phrase"},
    {"hanzi": "不客气", "pinyin": "bu4 ke4 qi4", "english": "you're welcome", "band": 1, "category": "phrase"},
    {"hanzi": "怎么", "pinyin": "zen3 me5", "english": "how; why", "band": 1, "category": "phrase"},
    {"hanzi": "为什么", "pinyin": "wei4 shen2 me5", "english": "why", "band": 1, "category": "phrase"},
    {"hanzi": "怎么样", "pinyin": "zen3 me5 yang4", "english": "how about; how is it", "band": 1, "category": "phrase"},

    # =========================================================================
    # BAND 2 — Basic
    # =========================================================================

    # --- Band 2: Nouns (Body Parts) ---
    {"hanzi": "头", "pinyin": "tou2", "english": "head; MW for large animals", "band": 2, "category": "noun"},
    {"hanzi": "眼睛", "pinyin": "yan3 jing1", "english": "eye", "band": 2, "category": "noun"},
    {"hanzi": "耳朵", "pinyin": "er3 duo5", "english": "ear", "band": 2, "category": "noun"},
    {"hanzi": "鼻子", "pinyin": "bi2 zi5", "english": "nose", "band": 2, "category": "noun"},
    {"hanzi": "嘴", "pinyin": "zui3", "english": "mouth", "band": 2, "category": "noun"},
    {"hanzi": "手", "pinyin": "shou3", "english": "hand", "band": 2, "category": "noun"},
    {"hanzi": "脚", "pinyin": "jiao3", "english": "foot", "band": 2, "category": "noun"},
    {"hanzi": "腿", "pinyin": "tui3", "english": "leg", "band": 2, "category": "noun"},
    {"hanzi": "身体", "pinyin": "shen1 ti3", "english": "body; health", "band": 2, "category": "noun"},
    {"hanzi": "脸", "pinyin": "lian3", "english": "face", "band": 2, "category": "noun"},

    # --- Band 2: Nouns (Weather & Nature) ---
    {"hanzi": "风", "pinyin": "feng1", "english": "wind", "band": 2, "category": "noun"},
    {"hanzi": "雪", "pinyin": "xue3", "english": "snow", "band": 2, "category": "noun"},
    {"hanzi": "春天", "pinyin": "chun1 tian1", "english": "spring", "band": 2, "category": "noun"},
    {"hanzi": "夏天", "pinyin": "xia4 tian1", "english": "summer", "band": 2, "category": "noun"},
    {"hanzi": "秋天", "pinyin": "qiu1 tian1", "english": "autumn; fall", "band": 2, "category": "noun"},
    {"hanzi": "冬天", "pinyin": "dong1 tian1", "english": "winter", "band": 2, "category": "noun"},
    {"hanzi": "太阳", "pinyin": "tai4 yang2", "english": "sun", "band": 2, "category": "noun"},
    {"hanzi": "月亮", "pinyin": "yue4 liang5", "english": "moon", "band": 2, "category": "noun"},

    # --- Band 2: Nouns (Transportation) ---
    {"hanzi": "火车", "pinyin": "huo3 che1", "english": "train", "band": 2, "category": "noun"},
    {"hanzi": "公共汽车", "pinyin": "gong1 gong4 qi4 che1", "english": "bus", "band": 2, "category": "noun"},
    {"hanzi": "地铁", "pinyin": "di4 tie3", "english": "subway; metro", "band": 2, "category": "noun"},
    {"hanzi": "自行车", "pinyin": "zi4 xing2 che1", "english": "bicycle", "band": 2, "category": "noun"},
    {"hanzi": "船", "pinyin": "chuan2", "english": "boat; ship", "band": 2, "category": "noun"},
    {"hanzi": "机场", "pinyin": "ji1 chang3", "english": "airport", "band": 2, "category": "noun"},
    {"hanzi": "火车站", "pinyin": "huo3 che1 zhan4", "english": "train station", "band": 2, "category": "noun"},

    # --- Band 2: Nouns (People & Professions) ---
    {"hanzi": "医生", "pinyin": "yi1 sheng1", "english": "doctor", "band": 2, "category": "noun"},
    {"hanzi": "护士", "pinyin": "hu4 shi5", "english": "nurse", "band": 2, "category": "noun"},
    {"hanzi": "司机", "pinyin": "si1 ji1", "english": "driver", "band": 2, "category": "noun"},
    {"hanzi": "服务员", "pinyin": "fu2 wu4 yuan2", "english": "waiter; server", "band": 2, "category": "noun"},
    {"hanzi": "经理", "pinyin": "jing1 li3", "english": "manager", "band": 2, "category": "noun"},
    {"hanzi": "邻居", "pinyin": "lin2 ju1", "english": "neighbor", "band": 2, "category": "noun"},
    {"hanzi": "客人", "pinyin": "ke4 ren2", "english": "guest; visitor", "band": 2, "category": "noun"},
    {"hanzi": "丈夫", "pinyin": "zhang4 fu1", "english": "husband", "band": 2, "category": "noun"},
    {"hanzi": "妻子", "pinyin": "qi1 zi3", "english": "wife", "band": 2, "category": "noun"},

    # --- Band 2: Nouns (Places) ---
    {"hanzi": "办公室", "pinyin": "ban4 gong1 shi4", "english": "office", "band": 2, "category": "noun"},
    {"hanzi": "教室", "pinyin": "jiao4 shi4", "english": "classroom", "band": 2, "category": "noun"},
    {"hanzi": "银行", "pinyin": "yin2 hang2", "english": "bank", "band": 2, "category": "noun"},
    {"hanzi": "超市", "pinyin": "chao1 shi4", "english": "supermarket", "band": 2, "category": "noun"},
    {"hanzi": "图书馆", "pinyin": "tu2 shu1 guan3", "english": "library", "band": 2, "category": "noun"},
    {"hanzi": "厕所", "pinyin": "ce4 suo3", "english": "toilet; bathroom", "band": 2, "category": "noun"},
    {"hanzi": "厨房", "pinyin": "chu2 fang2", "english": "kitchen", "band": 2, "category": "noun"},
    {"hanzi": "房间", "pinyin": "fang2 jian1", "english": "room", "band": 2, "category": "noun"},
    {"hanzi": "公园", "pinyin": "gong1 yuan2", "english": "park", "band": 2, "category": "noun"},

    # --- Band 2: Nouns (Things & Misc) ---
    {"hanzi": "电梯", "pinyin": "dian4 ti1", "english": "elevator; lift", "band": 2, "category": "noun"},
    {"hanzi": "报纸", "pinyin": "bao4 zhi3", "english": "newspaper", "band": 2, "category": "noun"},
    {"hanzi": "地图", "pinyin": "di4 tu2", "english": "map", "band": 2, "category": "noun"},
    {"hanzi": "护照", "pinyin": "hu4 zhao4", "english": "passport", "band": 2, "category": "noun"},
    {"hanzi": "行李", "pinyin": "xing2 li3", "english": "luggage; baggage", "band": 2, "category": "noun"},
    {"hanzi": "照片", "pinyin": "zhao4 pian4", "english": "photo; picture", "band": 2, "category": "noun"},
    {"hanzi": "信", "pinyin": "xin4", "english": "letter; mail", "band": 2, "category": "noun"},
    {"hanzi": "药", "pinyin": "yao4", "english": "medicine", "band": 2, "category": "noun"},
    {"hanzi": "花", "pinyin": "hua1", "english": "flower", "band": 2, "category": "noun"},
    {"hanzi": "树", "pinyin": "shu4", "english": "tree", "band": 2, "category": "noun"},
    {"hanzi": "鸟", "pinyin": "niao3", "english": "bird", "band": 2, "category": "noun"},
    {"hanzi": "裙子", "pinyin": "qun2 zi5", "english": "skirt; dress", "band": 2, "category": "noun"},
    {"hanzi": "裤子", "pinyin": "ku4 zi5", "english": "pants; trousers", "band": 2, "category": "noun"},
    {"hanzi": "鞋子", "pinyin": "xie2 zi5", "english": "shoes", "band": 2, "category": "noun"},
    {"hanzi": "帽子", "pinyin": "mao4 zi5", "english": "hat; cap", "band": 2, "category": "noun"},
    {"hanzi": "眼镜", "pinyin": "yan3 jing4", "english": "glasses; spectacles", "band": 2, "category": "noun"},
    {"hanzi": "伞", "pinyin": "san3", "english": "umbrella", "band": 2, "category": "noun"},
    {"hanzi": "筷子", "pinyin": "kuai4 zi5", "english": "chopsticks", "band": 2, "category": "noun"},
    {"hanzi": "碗", "pinyin": "wan3", "english": "bowl", "band": 2, "category": "noun"},
    {"hanzi": "盘子", "pinyin": "pan2 zi5", "english": "plate; dish", "band": 2, "category": "noun"},
    {"hanzi": "瓶子", "pinyin": "ping2 zi5", "english": "bottle", "band": 2, "category": "noun"},
    {"hanzi": "蛋糕", "pinyin": "dan4 gao1", "english": "cake", "band": 2, "category": "noun"},
    {"hanzi": "面包", "pinyin": "mian4 bao1", "english": "bread", "band": 2, "category": "noun"},
    {"hanzi": "西瓜", "pinyin": "xi1 gua1", "english": "watermelon", "band": 2, "category": "noun"},
    {"hanzi": "香蕉", "pinyin": "xiang1 jiao1", "english": "banana", "band": 2, "category": "noun"},
    {"hanzi": "啤酒", "pinyin": "pi2 jiu3", "english": "beer", "band": 2, "category": "noun"},
    {"hanzi": "作业", "pinyin": "zuo4 ye4", "english": "homework; assignment", "band": 2, "category": "noun"},
    {"hanzi": "黑板", "pinyin": "hei1 ban3", "english": "blackboard", "band": 2, "category": "noun"},
    {"hanzi": "地方", "pinyin": "di4 fang1", "english": "place; location", "band": 2, "category": "noun"},
    {"hanzi": "声音", "pinyin": "sheng1 yin1", "english": "sound; voice", "band": 2, "category": "noun"},
    {"hanzi": "故事", "pinyin": "gu4 shi5", "english": "story", "band": 2, "category": "noun"},

    # --- Band 2: Verbs ---
    {"hanzi": "帮助", "pinyin": "bang1 zhu4", "english": "to help", "band": 2, "category": "verb"},
    {"hanzi": "准备", "pinyin": "zhun3 bei4", "english": "to prepare", "band": 2, "category": "verb"},
    {"hanzi": "练习", "pinyin": "lian4 xi2", "english": "to practice", "band": 2, "category": "verb"},
    {"hanzi": "复习", "pinyin": "fu4 xi2", "english": "to review", "band": 2, "category": "verb"},
    {"hanzi": "考试", "pinyin": "kao3 shi4", "english": "to take an exam; exam", "band": 2, "category": "verb"},
    {"hanzi": "迟到", "pinyin": "chi2 dao4", "english": "to be late", "band": 2, "category": "verb"},
    {"hanzi": "担心", "pinyin": "dan1 xin1", "english": "to worry", "band": 2, "category": "verb"},
    {"hanzi": "生气", "pinyin": "sheng1 qi4", "english": "to be angry", "band": 2, "category": "verb"},
    {"hanzi": "关心", "pinyin": "guan1 xin1", "english": "to care about", "band": 2, "category": "verb"},
    {"hanzi": "相信", "pinyin": "xiang1 xin4", "english": "to believe; to trust", "band": 2, "category": "verb"},
    {"hanzi": "了解", "pinyin": "liao3 jie3", "english": "to understand; to find out", "band": 2, "category": "verb"},
    {"hanzi": "决定", "pinyin": "jue2 ding4", "english": "to decide; decision", "band": 2, "category": "verb"},
    {"hanzi": "记得", "pinyin": "ji4 de5", "english": "to remember", "band": 2, "category": "verb"},
    {"hanzi": "忘记", "pinyin": "wang4 ji4", "english": "to forget", "band": 2, "category": "verb"},
    {"hanzi": "同意", "pinyin": "tong2 yi4", "english": "to agree", "band": 2, "category": "verb"},
    {"hanzi": "需要", "pinyin": "xu1 yao4", "english": "to need", "band": 2, "category": "verb"},
    {"hanzi": "希望", "pinyin": "xi1 wang4", "english": "to hope; hope", "band": 2, "category": "verb"},
    {"hanzi": "换", "pinyin": "huan4", "english": "to change; to exchange", "band": 2, "category": "verb"},
    {"hanzi": "搬", "pinyin": "ban1", "english": "to move (house)", "band": 2, "category": "verb"},
    {"hanzi": "借", "pinyin": "jie4", "english": "to borrow; to lend", "band": 2, "category": "verb"},
    {"hanzi": "教", "pinyin": "jiao1", "english": "to teach", "band": 2, "category": "verb"},
    {"hanzi": "洗", "pinyin": "xi3", "english": "to wash", "band": 2, "category": "verb"},
    {"hanzi": "笑", "pinyin": "xiao4", "english": "to laugh; to smile", "band": 2, "category": "verb"},
    {"hanzi": "哭", "pinyin": "ku1", "english": "to cry", "band": 2, "category": "verb"},
    {"hanzi": "唱歌", "pinyin": "chang4 ge1", "english": "to sing", "band": 2, "category": "verb"},
    {"hanzi": "跳舞", "pinyin": "tiao4 wu3", "english": "to dance", "band": 2, "category": "verb"},
    {"hanzi": "爬山", "pinyin": "pa2 shan1", "english": "to climb a mountain", "band": 2, "category": "verb"},
    {"hanzi": "游泳", "pinyin": "you2 yong3", "english": "to swim", "band": 2, "category": "verb"},
    {"hanzi": "旅游", "pinyin": "lv3 you2", "english": "to travel; tourism", "band": 2, "category": "verb"},
    {"hanzi": "参加", "pinyin": "can1 jia1", "english": "to participate; to attend", "band": 2, "category": "verb"},
    {"hanzi": "完成", "pinyin": "wan2 cheng2", "english": "to complete; to finish", "band": 2, "category": "verb"},
    {"hanzi": "检查", "pinyin": "jian3 cha2", "english": "to check; to examine", "band": 2, "category": "verb"},
    {"hanzi": "注意", "pinyin": "zhu4 yi4", "english": "to pay attention to", "band": 2, "category": "verb"},
    {"hanzi": "解决", "pinyin": "jie3 jue2", "english": "to solve; to resolve", "band": 2, "category": "verb"},
    {"hanzi": "介绍", "pinyin": "jie4 shao4", "english": "to introduce", "band": 2, "category": "verb"},
    {"hanzi": "发现", "pinyin": "fa1 xian4", "english": "to discover; to find", "band": 2, "category": "verb"},
    {"hanzi": "带", "pinyin": "dai4", "english": "to bring; to carry; to lead", "band": 2, "category": "verb"},
    {"hanzi": "放", "pinyin": "fang4", "english": "to put; to place; to release", "band": 2, "category": "verb"},
    {"hanzi": "拿", "pinyin": "na2", "english": "to take; to hold", "band": 2, "category": "verb"},
    {"hanzi": "画", "pinyin": "hua4", "english": "to draw; to paint", "band": 2, "category": "verb"},
    {"hanzi": "种", "pinyin": "zhong4", "english": "to plant; to grow; (zhong3) kind; type", "band": 2, "category": "verb"},

    # --- Band 2: Adjectives ---
    {"hanzi": "干净", "pinyin": "gan1 jing4", "english": "clean", "band": 2, "category": "adjective"},
    {"hanzi": "脏", "pinyin": "zang1", "english": "dirty", "band": 2, "category": "adjective"},
    {"hanzi": "方便", "pinyin": "fang1 bian4", "english": "convenient", "band": 2, "category": "adjective"},
    {"hanzi": "简单", "pinyin": "jian3 dan1", "english": "simple; easy", "band": 2, "category": "adjective"},
    {"hanzi": "难", "pinyin": "nan2", "english": "difficult; hard", "band": 2, "category": "adjective"},
    {"hanzi": "容易", "pinyin": "rong2 yi4", "english": "easy", "band": 2, "category": "adjective"},
    {"hanzi": "重要", "pinyin": "zhong4 yao4", "english": "important", "band": 2, "category": "adjective"},
    {"hanzi": "特别", "pinyin": "te4 bie2", "english": "special; especially", "band": 2, "category": "adjective"},
    {"hanzi": "有趣", "pinyin": "you3 qu4", "english": "interesting; fun", "band": 2, "category": "adjective"},
    {"hanzi": "安静", "pinyin": "an1 jing4", "english": "quiet; peaceful", "band": 2, "category": "adjective"},
    {"hanzi": "聪明", "pinyin": "cong1 ming2", "english": "smart; clever", "band": 2, "category": "adjective"},
    {"hanzi": "奇怪", "pinyin": "qi2 guai4", "english": "strange; odd", "band": 2, "category": "adjective"},
    {"hanzi": "年轻", "pinyin": "nian2 qing1", "english": "young", "band": 2, "category": "adjective"},
    {"hanzi": "老", "pinyin": "lao3", "english": "old (person)", "band": 2, "category": "adjective"},
    {"hanzi": "胖", "pinyin": "pang4", "english": "fat; overweight", "band": 2, "category": "adjective"},
    {"hanzi": "瘦", "pinyin": "shou4", "english": "thin; slim", "band": 2, "category": "adjective"},
    {"hanzi": "甜", "pinyin": "tian2", "english": "sweet", "band": 2, "category": "adjective"},
    {"hanzi": "苦", "pinyin": "ku3", "english": "bitter", "band": 2, "category": "adjective"},
    {"hanzi": "辣", "pinyin": "la4", "english": "spicy; hot", "band": 2, "category": "adjective"},
    {"hanzi": "咸", "pinyin": "xian2", "english": "salty", "band": 2, "category": "adjective"},
    {"hanzi": "饿", "pinyin": "e4", "english": "hungry", "band": 2, "category": "adjective"},
    {"hanzi": "渴", "pinyin": "ke3", "english": "thirsty", "band": 2, "category": "adjective"},
    {"hanzi": "累", "pinyin": "lei4", "english": "tired", "band": 2, "category": "adjective"},
    {"hanzi": "舒服", "pinyin": "shu1 fu5", "english": "comfortable", "band": 2, "category": "adjective"},
    {"hanzi": "蓝", "pinyin": "lan2", "english": "blue", "band": 2, "category": "adjective"},
    {"hanzi": "绿", "pinyin": "lv4", "english": "green", "band": 2, "category": "adjective"},
    {"hanzi": "黄", "pinyin": "huang2", "english": "yellow", "band": 2, "category": "adjective"},

    # --- Band 2: Adverbs ---
    {"hanzi": "一直", "pinyin": "yi1 zhi2", "english": "always; all along; straight", "band": 2, "category": "adverb"},
    {"hanzi": "经常", "pinyin": "jing1 chang2", "english": "often; frequently", "band": 2, "category": "adverb"},
    {"hanzi": "有时候", "pinyin": "you3 shi2 hou5", "english": "sometimes", "band": 2, "category": "adverb"},
    {"hanzi": "突然", "pinyin": "tu1 ran2", "english": "suddenly", "band": 2, "category": "adverb"},
    {"hanzi": "马上", "pinyin": "ma3 shang4", "english": "immediately; right away", "band": 2, "category": "adverb"},
    {"hanzi": "一起", "pinyin": "yi1 qi3", "english": "together", "band": 2, "category": "adverb"},
    {"hanzi": "只", "pinyin": "zhi3", "english": "only; just; (zhi1) MW for animals", "band": 2, "category": "adverb"},
    {"hanzi": "可能", "pinyin": "ke3 neng2", "english": "maybe; possibly", "band": 2, "category": "adverb"},
    {"hanzi": "非常", "pinyin": "fei1 chang2", "english": "very; extremely", "band": 2, "category": "adverb"},
    {"hanzi": "几乎", "pinyin": "ji1 hu1", "english": "almost; nearly", "band": 2, "category": "adverb"},
    {"hanzi": "终于", "pinyin": "zhong1 yu2", "english": "finally; at last", "band": 2, "category": "adverb"},
    {"hanzi": "一定", "pinyin": "yi1 ding4", "english": "certainly; definitely", "band": 2, "category": "adverb"},
    {"hanzi": "当然", "pinyin": "dang1 ran2", "english": "of course; certainly", "band": 2, "category": "adverb"},

    # --- Band 2: Measure Words ---
    {"hanzi": "件", "pinyin": "jian4", "english": "measure word for clothes/matters", "band": 2, "category": "measure_word"},
    {"hanzi": "条", "pinyin": "tiao2", "english": "measure word for long thin things", "band": 2, "category": "measure_word"},
    {"hanzi": "双", "pinyin": "shuang1", "english": "pair; measure word for pairs", "band": 2, "category": "measure_word"},
    {"hanzi": "张", "pinyin": "zhang1", "english": "measure word for flat things", "band": 2, "category": "measure_word"},
    {"hanzi": "把", "pinyin": "ba3", "english": "measure word for things with handles", "band": 2, "category": "measure_word"},
    {"hanzi": "座", "pinyin": "zuo4", "english": "measure word for buildings/mountains", "band": 2, "category": "measure_word"},
    {"hanzi": "辆", "pinyin": "liang4", "english": "measure word for vehicles", "band": 2, "category": "measure_word"},
    {"hanzi": "位", "pinyin": "wei4", "english": "measure word for people (polite)", "band": 2, "category": "measure_word"},
    {"hanzi": "节", "pinyin": "jie2", "english": "measure word for classes/sections", "band": 2, "category": "measure_word"},
    {"hanzi": "套", "pinyin": "tao4", "english": "measure word for sets", "band": 2, "category": "measure_word"},
    {"hanzi": "次", "pinyin": "ci4", "english": "time (occurrence); measure word", "band": 2, "category": "measure_word"},
    {"hanzi": "段", "pinyin": "duan4", "english": "section; measure word for paragraphs", "band": 2, "category": "measure_word"},

    # --- Band 2: Conjunctions ---
    {"hanzi": "虽然", "pinyin": "sui1 ran2", "english": "although; even though", "band": 2, "category": "conjunction"},
    {"hanzi": "而且", "pinyin": "er2 qie3", "english": "moreover; and also", "band": 2, "category": "conjunction"},
    {"hanzi": "不但", "pinyin": "bu4 dan4", "english": "not only", "band": 2, "category": "conjunction"},
    {"hanzi": "还是", "pinyin": "hai2 shi4", "english": "or (in questions); still", "band": 2, "category": "conjunction"},
    {"hanzi": "要是", "pinyin": "yao4 shi4", "english": "if; in case", "band": 2, "category": "conjunction"},

    # --- Band 2: Prepositions ---
    {"hanzi": "除了", "pinyin": "chu2 le5", "english": "except; besides", "band": 2, "category": "preposition"},
    {"hanzi": "关于", "pinyin": "guan1 yu2", "english": "about; regarding", "band": 2, "category": "preposition"},
    {"hanzi": "根据", "pinyin": "gen1 ju4", "english": "according to; based on", "band": 2, "category": "preposition"},

    # --- Band 2: Time Words ---
    {"hanzi": "后天", "pinyin": "hou4 tian1", "english": "day after tomorrow", "band": 2, "category": "time_word"},
    {"hanzi": "前天", "pinyin": "qian2 tian1", "english": "day before yesterday", "band": 2, "category": "time_word"},
    {"hanzi": "刚才", "pinyin": "gang1 cai2", "english": "just now; a moment ago", "band": 2, "category": "time_word"},
    {"hanzi": "以前", "pinyin": "yi3 qian2", "english": "before; previously", "band": 2, "category": "time_word"},
    {"hanzi": "以后", "pinyin": "yi3 hou4", "english": "after; later", "band": 2, "category": "time_word"},
    {"hanzi": "最近", "pinyin": "zui4 jin4", "english": "recently; lately", "band": 2, "category": "time_word"},
    {"hanzi": "周末", "pinyin": "zhou1 mo4", "english": "weekend", "band": 2, "category": "time_word"},
    {"hanzi": "平时", "pinyin": "ping2 shi2", "english": "usually; normally", "band": 2, "category": "time_word"},

    # --- Band 2: Phrases ---
    {"hanzi": "没问题", "pinyin": "mei2 wen4 ti2", "english": "no problem", "band": 2, "category": "phrase"},

    # =========================================================================
    # BAND 3 — Intermediate
    # =========================================================================

    # --- Band 3: Nouns (Abstract & Education) ---
    {"hanzi": "经验", "pinyin": "jing1 yan4", "english": "experience", "band": 3, "category": "noun"},
    {"hanzi": "机会", "pinyin": "ji1 hui4", "english": "opportunity; chance", "band": 3, "category": "noun"},
    {"hanzi": "关系", "pinyin": "guan1 xi4", "english": "relationship; connection", "band": 3, "category": "noun"},
    {"hanzi": "文化", "pinyin": "wen2 hua4", "english": "culture", "band": 3, "category": "noun"},
    {"hanzi": "社会", "pinyin": "she4 hui4", "english": "society", "band": 3, "category": "noun"},
    {"hanzi": "经济", "pinyin": "jing1 ji4", "english": "economy; economics", "band": 3, "category": "noun"},
    {"hanzi": "环境", "pinyin": "huan2 jing4", "english": "environment", "band": 3, "category": "noun"},
    {"hanzi": "科学", "pinyin": "ke1 xue2", "english": "science", "band": 3, "category": "noun"},
    {"hanzi": "技术", "pinyin": "ji4 shu4", "english": "technology; technique", "band": 3, "category": "noun"},
    {"hanzi": "网络", "pinyin": "wang3 luo4", "english": "network; internet", "band": 3, "category": "noun"},
    {"hanzi": "新闻", "pinyin": "xin1 wen2", "english": "news", "band": 3, "category": "noun"},
    {"hanzi": "教育", "pinyin": "jiao4 yu4", "english": "education", "band": 3, "category": "noun"},
    {"hanzi": "知识", "pinyin": "zhi1 shi2", "english": "knowledge", "band": 3, "category": "noun"},
    {"hanzi": "历史", "pinyin": "li4 shi3", "english": "history", "band": 3, "category": "noun"},
    {"hanzi": "数学", "pinyin": "shu4 xue2", "english": "mathematics", "band": 3, "category": "noun"},
    {"hanzi": "语言", "pinyin": "yu3 yan2", "english": "language", "band": 3, "category": "noun"},
    {"hanzi": "艺术", "pinyin": "yi4 shu4", "english": "art", "band": 3, "category": "noun"},
    {"hanzi": "音乐", "pinyin": "yin1 yue4", "english": "music", "band": 3, "category": "noun"},
    {"hanzi": "电影", "pinyin": "dian4 ying3", "english": "movie; film", "band": 3, "category": "noun"},
    {"hanzi": "节目", "pinyin": "jie2 mu4", "english": "program; show", "band": 3, "category": "noun"},
    {"hanzi": "比赛", "pinyin": "bi3 sai4", "english": "competition; match", "band": 3, "category": "noun"},
    {"hanzi": "成绩", "pinyin": "cheng2 ji4", "english": "grade; score; result", "band": 3, "category": "noun"},
    {"hanzi": "计划", "pinyin": "ji4 hua4", "english": "plan", "band": 3, "category": "noun"},
    {"hanzi": "方法", "pinyin": "fang1 fa3", "english": "method; way", "band": 3, "category": "noun"},
    {"hanzi": "答案", "pinyin": "da2 an4", "english": "answer; solution", "band": 3, "category": "noun"},
    {"hanzi": "原因", "pinyin": "yuan2 yin1", "english": "reason; cause", "band": 3, "category": "noun"},
    {"hanzi": "结果", "pinyin": "jie2 guo3", "english": "result; outcome", "band": 3, "category": "noun"},
    {"hanzi": "目的", "pinyin": "mu4 di4", "english": "purpose; goal", "band": 3, "category": "noun"},
    {"hanzi": "意见", "pinyin": "yi4 jian4", "english": "opinion; suggestion", "band": 3, "category": "noun"},
    {"hanzi": "态度", "pinyin": "tai4 du4", "english": "attitude", "band": 3, "category": "noun"},

    # --- Band 3: Nouns (Emotions & Life) ---
    {"hanzi": "感情", "pinyin": "gan3 qing2", "english": "feeling; emotion", "band": 3, "category": "noun"},
    {"hanzi": "心情", "pinyin": "xin1 qing2", "english": "mood", "band": 3, "category": "noun"},
    {"hanzi": "梦", "pinyin": "meng4", "english": "dream", "band": 3, "category": "noun"},
    {"hanzi": "压力", "pinyin": "ya1 li4", "english": "pressure; stress", "band": 3, "category": "noun"},
    {"hanzi": "健康", "pinyin": "jian4 kang1", "english": "health; healthy", "band": 3, "category": "noun"},
    {"hanzi": "安全", "pinyin": "an1 quan2", "english": "safety; safe", "band": 3, "category": "noun"},
    {"hanzi": "生活", "pinyin": "sheng1 huo2", "english": "life; to live", "band": 3, "category": "noun"},
    {"hanzi": "习惯", "pinyin": "xi2 guan4", "english": "habit; to be used to", "band": 3, "category": "noun"},
    {"hanzi": "兴趣", "pinyin": "xing4 qu4", "english": "interest", "band": 3, "category": "noun"},
    {"hanzi": "爱好", "pinyin": "ai4 hao4", "english": "hobby", "band": 3, "category": "noun"},
    {"hanzi": "性格", "pinyin": "xing4 ge2", "english": "character; personality", "band": 3, "category": "noun"},
    {"hanzi": "印象", "pinyin": "yin4 xiang4", "english": "impression", "band": 3, "category": "noun"},

    # --- Band 3: Nouns (Nature) ---
    {"hanzi": "空气", "pinyin": "kong1 qi4", "english": "air", "band": 3, "category": "noun"},
    {"hanzi": "地球", "pinyin": "di4 qiu2", "english": "earth; the globe", "band": 3, "category": "noun"},
    {"hanzi": "海", "pinyin": "hai3", "english": "sea; ocean", "band": 3, "category": "noun"},
    {"hanzi": "山", "pinyin": "shan1", "english": "mountain; hill", "band": 3, "category": "noun"},
    {"hanzi": "河", "pinyin": "he2", "english": "river", "band": 3, "category": "noun"},
    {"hanzi": "森林", "pinyin": "sen1 lin2", "english": "forest", "band": 3, "category": "noun"},
    {"hanzi": "动物", "pinyin": "dong4 wu4", "english": "animal", "band": 3, "category": "noun"},
    {"hanzi": "植物", "pinyin": "zhi2 wu4", "english": "plant", "band": 3, "category": "noun"},

    # --- Band 3: Nouns (Society & Work) ---
    {"hanzi": "传统", "pinyin": "chuan2 tong3", "english": "tradition; traditional", "band": 3, "category": "noun"},
    {"hanzi": "广告", "pinyin": "guang3 gao4", "english": "advertisement", "band": 3, "category": "noun"},
    {"hanzi": "市场", "pinyin": "shi4 chang3", "english": "market", "band": 3, "category": "noun"},
    {"hanzi": "价格", "pinyin": "jia4 ge2", "english": "price", "band": 3, "category": "noun"},
    {"hanzi": "法律", "pinyin": "fa3 lv4", "english": "law", "band": 3, "category": "noun"},
    {"hanzi": "规定", "pinyin": "gui1 ding4", "english": "regulation; rule", "band": 3, "category": "noun"},
    {"hanzi": "签证", "pinyin": "qian1 zheng4", "english": "visa", "band": 3, "category": "noun"},
    {"hanzi": "国际", "pinyin": "guo2 ji4", "english": "international", "band": 3, "category": "noun"},
    {"hanzi": "责任", "pinyin": "ze2 ren4", "english": "responsibility", "band": 3, "category": "noun"},
    {"hanzi": "信息", "pinyin": "xin4 xi1", "english": "information", "band": 3, "category": "noun"},
    {"hanzi": "材料", "pinyin": "cai2 liao4", "english": "material", "band": 3, "category": "noun"},
    {"hanzi": "效果", "pinyin": "xiao4 guo3", "english": "effect; result", "band": 3, "category": "noun"},
    {"hanzi": "标准", "pinyin": "biao1 zhun3", "english": "standard; criterion", "band": 3, "category": "noun"},
    {"hanzi": "条件", "pinyin": "tiao2 jian4", "english": "condition; requirement", "band": 3, "category": "noun"},
    {"hanzi": "水平", "pinyin": "shui3 ping2", "english": "level; standard", "band": 3, "category": "noun"},
    {"hanzi": "能力", "pinyin": "neng2 li4", "english": "ability; capability", "band": 3, "category": "noun"},
    {"hanzi": "速度", "pinyin": "su4 du4", "english": "speed", "band": 3, "category": "noun"},
    {"hanzi": "距离", "pinyin": "ju4 li2", "english": "distance", "band": 3, "category": "noun"},
    {"hanzi": "优点", "pinyin": "you1 dian3", "english": "advantage; merit", "band": 3, "category": "noun"},
    {"hanzi": "缺点", "pinyin": "que1 dian3", "english": "disadvantage; shortcoming", "band": 3, "category": "noun"},

    # --- Band 3: Verbs ---
    {"hanzi": "表示", "pinyin": "biao3 shi4", "english": "to express; to indicate", "band": 3, "category": "verb"},
    {"hanzi": "表演", "pinyin": "biao3 yan3", "english": "to perform; performance", "band": 3, "category": "verb"},
    {"hanzi": "保护", "pinyin": "bao3 hu4", "english": "to protect", "band": 3, "category": "verb"},
    {"hanzi": "改变", "pinyin": "gai3 bian4", "english": "to change", "band": 3, "category": "verb"},
    {"hanzi": "提高", "pinyin": "ti2 gao1", "english": "to improve; to raise", "band": 3, "category": "verb"},
    {"hanzi": "增加", "pinyin": "zeng1 jia1", "english": "to increase; to add", "band": 3, "category": "verb"},
    {"hanzi": "减少", "pinyin": "jian3 shao3", "english": "to reduce; to decrease", "band": 3, "category": "verb"},
    {"hanzi": "发展", "pinyin": "fa1 zhan3", "english": "to develop; development", "band": 3, "category": "verb"},
    {"hanzi": "影响", "pinyin": "ying3 xiang3", "english": "to influence; influence", "band": 3, "category": "verb"},
    {"hanzi": "讨论", "pinyin": "tao3 lun4", "english": "to discuss; discussion", "band": 3, "category": "verb"},
    {"hanzi": "交流", "pinyin": "jiao1 liu2", "english": "to exchange; to communicate", "band": 3, "category": "verb"},
    {"hanzi": "联系", "pinyin": "lian2 xi4", "english": "to contact; connection", "band": 3, "category": "verb"},
    {"hanzi": "申请", "pinyin": "shen1 qing3", "english": "to apply for; application", "band": 3, "category": "verb"},
    {"hanzi": "拒绝", "pinyin": "ju4 jue2", "english": "to refuse; to reject", "band": 3, "category": "verb"},
    {"hanzi": "接受", "pinyin": "jie1 shou4", "english": "to accept; to receive", "band": 3, "category": "verb"},
    {"hanzi": "证明", "pinyin": "zheng4 ming2", "english": "to prove; proof", "band": 3, "category": "verb"},
    {"hanzi": "代替", "pinyin": "dai4 ti4", "english": "to replace; to substitute", "band": 3, "category": "verb"},
    {"hanzi": "推迟", "pinyin": "tui1 chi2", "english": "to postpone; to delay", "band": 3, "category": "verb"},
    {"hanzi": "比较", "pinyin": "bi3 jiao4", "english": "to compare; relatively", "band": 3, "category": "verb"},
    {"hanzi": "适合", "pinyin": "shi4 he2", "english": "to suit; to fit", "band": 3, "category": "verb"},
    {"hanzi": "存在", "pinyin": "cun2 zai4", "english": "to exist; existence", "band": 3, "category": "verb"},
    {"hanzi": "包括", "pinyin": "bao1 kuo4", "english": "to include", "band": 3, "category": "verb"},
    {"hanzi": "属于", "pinyin": "shu3 yu2", "english": "to belong to", "band": 3, "category": "verb"},
    {"hanzi": "尊重", "pinyin": "zun1 zhong4", "english": "to respect", "band": 3, "category": "verb"},
    {"hanzi": "鼓励", "pinyin": "gu3 li4", "english": "to encourage", "band": 3, "category": "verb"},
    {"hanzi": "吸引", "pinyin": "xi1 yin3", "english": "to attract", "band": 3, "category": "verb"},
    {"hanzi": "获得", "pinyin": "huo4 de2", "english": "to obtain; to gain", "band": 3, "category": "verb"},
    {"hanzi": "失败", "pinyin": "shi1 bai4", "english": "to fail; failure", "band": 3, "category": "verb"},
    {"hanzi": "成功", "pinyin": "cheng2 gong1", "english": "to succeed; success", "band": 3, "category": "verb"},
    {"hanzi": "整理", "pinyin": "zheng3 li3", "english": "to organize; to tidy up", "band": 3, "category": "verb"},
    {"hanzi": "翻译", "pinyin": "fan1 yi4", "english": "to translate; translator", "band": 3, "category": "verb"},
    {"hanzi": "感动", "pinyin": "gan3 dong4", "english": "to be moved; touching", "band": 3, "category": "verb"},
    {"hanzi": "感觉", "pinyin": "gan3 jue2", "english": "to feel; feeling", "band": 3, "category": "verb"},
    {"hanzi": "组织", "pinyin": "zu3 zhi1", "english": "to organize; organization", "band": 3, "category": "verb"},
    {"hanzi": "支持", "pinyin": "zhi1 chi2", "english": "to support", "band": 3, "category": "verb"},
    {"hanzi": "反对", "pinyin": "fan3 dui4", "english": "to oppose; to be against", "band": 3, "category": "verb"},
    {"hanzi": "理解", "pinyin": "li3 jie3", "english": "to understand; to comprehend", "band": 3, "category": "verb"},
    {"hanzi": "实现", "pinyin": "shi2 xian4", "english": "to realize; to achieve", "band": 3, "category": "verb"},

    # --- Band 3: Adjectives ---
    {"hanzi": "丰富", "pinyin": "feng1 fu4", "english": "rich; abundant", "band": 3, "category": "adjective"},
    {"hanzi": "复杂", "pinyin": "fu4 za2", "english": "complex; complicated", "band": 3, "category": "adjective"},
    {"hanzi": "普通", "pinyin": "pu3 tong1", "english": "ordinary; common", "band": 3, "category": "adjective"},
    {"hanzi": "正常", "pinyin": "zheng4 chang2", "english": "normal", "band": 3, "category": "adjective"},
    {"hanzi": "正式", "pinyin": "zheng4 shi4", "english": "formal; official", "band": 3, "category": "adjective"},
    {"hanzi": "合适", "pinyin": "he2 shi4", "english": "suitable; appropriate", "band": 3, "category": "adjective"},
    {"hanzi": "专业", "pinyin": "zhuan1 ye4", "english": "professional; major", "band": 3, "category": "adjective"},
    {"hanzi": "积极", "pinyin": "ji1 ji2", "english": "positive; active", "band": 3, "category": "adjective"},
    {"hanzi": "消极", "pinyin": "xiao1 ji2", "english": "negative; passive", "band": 3, "category": "adjective"},
    {"hanzi": "严格", "pinyin": "yan2 ge2", "english": "strict", "band": 3, "category": "adjective"},
    {"hanzi": "明显", "pinyin": "ming2 xian3", "english": "obvious; clear", "band": 3, "category": "adjective"},
    {"hanzi": "独立", "pinyin": "du2 li4", "english": "independent", "band": 3, "category": "adjective"},
    {"hanzi": "勇敢", "pinyin": "yong3 gan3", "english": "brave; courageous", "band": 3, "category": "adjective"},
    {"hanzi": "诚实", "pinyin": "cheng2 shi2", "english": "honest", "band": 3, "category": "adjective"},
    {"hanzi": "骄傲", "pinyin": "jiao1 ao4", "english": "proud; arrogant", "band": 3, "category": "adjective"},
    {"hanzi": "幸福", "pinyin": "xing4 fu2", "english": "happy; blessed", "band": 3, "category": "adjective"},
    {"hanzi": "满意", "pinyin": "man3 yi4", "english": "satisfied", "band": 3, "category": "adjective"},
    {"hanzi": "失望", "pinyin": "shi1 wang4", "english": "disappointed", "band": 3, "category": "adjective"},
    {"hanzi": "紧张", "pinyin": "jin3 zhang1", "english": "nervous; tense", "band": 3, "category": "adjective"},
    {"hanzi": "害怕", "pinyin": "hai4 pa4", "english": "afraid; scared", "band": 3, "category": "adjective"},
    {"hanzi": "无聊", "pinyin": "wu2 liao2", "english": "bored; boring", "band": 3, "category": "adjective"},
    {"hanzi": "温暖", "pinyin": "wen1 nuan3", "english": "warm", "band": 3, "category": "adjective"},
    {"hanzi": "凉快", "pinyin": "liang2 kuai5", "english": "cool; pleasantly cool", "band": 3, "category": "adjective"},
    {"hanzi": "干燥", "pinyin": "gan1 zao4", "english": "dry", "band": 3, "category": "adjective"},
    {"hanzi": "危险", "pinyin": "wei1 xian3", "english": "dangerous", "band": 3, "category": "adjective"},
    {"hanzi": "免费", "pinyin": "mian3 fei4", "english": "free (no cost)", "band": 3, "category": "adjective"},
    {"hanzi": "实际", "pinyin": "shi2 ji4", "english": "actual; practical", "band": 3, "category": "adjective"},
    {"hanzi": "具体", "pinyin": "ju4 ti3", "english": "specific; concrete", "band": 3, "category": "adjective"},

    # --- Band 3: Adverbs ---
    {"hanzi": "逐渐", "pinyin": "zhu2 jian4", "english": "gradually", "band": 3, "category": "adverb"},
    {"hanzi": "大约", "pinyin": "da4 yue1", "english": "approximately; about", "band": 3, "category": "adverb"},
    {"hanzi": "至少", "pinyin": "zhi4 shao3", "english": "at least", "band": 3, "category": "adverb"},
    {"hanzi": "首先", "pinyin": "shou3 xian1", "english": "first of all", "band": 3, "category": "adverb"},
    {"hanzi": "其次", "pinyin": "qi2 ci4", "english": "secondly; next", "band": 3, "category": "adverb"},
    {"hanzi": "然后", "pinyin": "ran2 hou4", "english": "then; after that", "band": 3, "category": "adverb"},
    {"hanzi": "否则", "pinyin": "fou3 ze2", "english": "otherwise", "band": 3, "category": "adverb"},
    {"hanzi": "尤其", "pinyin": "you2 qi2", "english": "especially", "band": 3, "category": "adverb"},
    {"hanzi": "甚至", "pinyin": "shen4 zhi4", "english": "even; so much so that", "band": 3, "category": "adverb"},
    {"hanzi": "仍然", "pinyin": "reng2 ran2", "english": "still; yet", "band": 3, "category": "adverb"},
    {"hanzi": "千万", "pinyin": "qian1 wan4", "english": "absolutely must (not)", "band": 3, "category": "adverb"},
    {"hanzi": "大概", "pinyin": "da4 gai4", "english": "probably; roughly", "band": 3, "category": "adverb"},
    {"hanzi": "互相", "pinyin": "hu4 xiang1", "english": "mutually; each other", "band": 3, "category": "adverb"},
    {"hanzi": "到处", "pinyin": "dao4 chu4", "english": "everywhere", "band": 3, "category": "adverb"},

    # --- Band 3: Measure Words ---
    {"hanzi": "份", "pinyin": "fen4", "english": "measure word for copies/portions", "band": 3, "category": "measure_word"},
    {"hanzi": "场", "pinyin": "chang3", "english": "measure word for events/games", "band": 3, "category": "measure_word"},
    {"hanzi": "首", "pinyin": "shou3", "english": "measure word for poems/songs", "band": 3, "category": "measure_word"},
    {"hanzi": "篇", "pinyin": "pian1", "english": "measure word for articles", "band": 3, "category": "measure_word"},

    # --- Band 3: Conjunctions ---
    {"hanzi": "不管", "pinyin": "bu4 guan3", "english": "regardless; no matter", "band": 3, "category": "conjunction"},
    {"hanzi": "即使", "pinyin": "ji2 shi3", "english": "even if; even though", "band": 3, "category": "conjunction"},
    {"hanzi": "由于", "pinyin": "you2 yu2", "english": "due to; because of", "band": 3, "category": "conjunction"},
    {"hanzi": "既然", "pinyin": "ji4 ran2", "english": "since; now that", "band": 3, "category": "conjunction"},
    {"hanzi": "无论", "pinyin": "wu2 lun4", "english": "no matter; regardless", "band": 3, "category": "conjunction"},
    {"hanzi": "另外", "pinyin": "ling4 wai4", "english": "in addition; besides", "band": 3, "category": "conjunction"},

    # --- Band 3: Prepositions ---
    {"hanzi": "按照", "pinyin": "an4 zhao4", "english": "according to", "band": 3, "category": "preposition"},
    {"hanzi": "随着", "pinyin": "sui2 zhe5", "english": "along with; as", "band": 3, "category": "preposition"},
    {"hanzi": "通过", "pinyin": "tong1 guo4", "english": "through; by means of", "band": 3, "category": "preposition"},

    # --- Band 3: Time Words ---
    {"hanzi": "将来", "pinyin": "jiang1 lai2", "english": "future; in the future", "band": 3, "category": "time_word"},
    {"hanzi": "过去", "pinyin": "guo4 qu4", "english": "past; in the past", "band": 3, "category": "time_word"},
    {"hanzi": "目前", "pinyin": "mu4 qian2", "english": "currently; at present", "band": 3, "category": "time_word"},
    {"hanzi": "永远", "pinyin": "yong3 yuan3", "english": "forever; always", "band": 3, "category": "time_word"},
    {"hanzi": "及时", "pinyin": "ji2 shi2", "english": "in time; timely", "band": 3, "category": "time_word"},
    {"hanzi": "同时", "pinyin": "tong2 shi2", "english": "at the same time", "band": 3, "category": "time_word"},
]
