"""HSK Level 4 vocabulary data."""

WORDS = [
    # ── Verbs – Actions & Movement ──
    {"hanzi": "感动", "pinyin": "gǎndòng", "english": "to move emotionally"},
    {"hanzi": "打扮", "pinyin": "dǎban", "english": "to dress up"},
    {"hanzi": "鼓励", "pinyin": "gǔlì", "english": "to encourage"},
    {"hanzi": "坚持", "pinyin": "jiānchí", "english": "to persist"},
    {"hanzi": "克服", "pinyin": "kèfú", "english": "to overcome"},
    {"hanzi": "理解", "pinyin": "lǐjiě", "english": "to understand"},
    {"hanzi": "判断", "pinyin": "pànduàn", "english": "to judge"},
    {"hanzi": "适应", "pinyin": "shìyìng", "english": "to adapt"},
    {"hanzi": "积累", "pinyin": "jīlěi", "english": "to accumulate"},
    {"hanzi": "交流", "pinyin": "jiāoliú", "english": "to communicate"},
    {"hanzi": "接受", "pinyin": "jiēshòu", "english": "to accept"},
    {"hanzi": "经历", "pinyin": "jīnglì", "english": "to experience"},
    {"hanzi": "满足", "pinyin": "mǎnzú", "english": "to satisfy"},
    {"hanzi": "培养", "pinyin": "péiyǎng", "english": "to cultivate"},
    {"hanzi": "评价", "pinyin": "píngjià", "english": "to evaluate"},
    {"hanzi": "申请", "pinyin": "shēnqǐng", "english": "to apply for"},
    {"hanzi": "适合", "pinyin": "shìhé", "english": "to suit"},
    {"hanzi": "说明", "pinyin": "shuōmíng", "english": "to explain"},
    {"hanzi": "证明", "pinyin": "zhèngmíng", "english": "to prove"},
    {"hanzi": "重视", "pinyin": "zhòngshì", "english": "to value"},
    {"hanzi": "阅读", "pinyin": "yuèdú", "english": "to read"},
    {"hanzi": "修理", "pinyin": "xiūlǐ", "english": "to repair"},
    {"hanzi": "约会", "pinyin": "yuēhuì", "english": "to have a date"},
    {"hanzi": "省", "pinyin": "shěng", "english": "to save / province"},
    {"hanzi": "使", "pinyin": "shǐ", "english": "to make / cause"},
    {"hanzi": "保护", "pinyin": "bǎohù", "english": "to protect"},
    {"hanzi": "保证", "pinyin": "bǎozhèng", "english": "to guarantee"},
    {"hanzi": "抄", "pinyin": "chāo", "english": "to copy"},
    {"hanzi": "吵", "pinyin": "chǎo", "english": "to quarrel"},
    {"hanzi": "称赞", "pinyin": "chēngzàn", "english": "to praise"},
    {"hanzi": "乘", "pinyin": "chéng", "english": "to ride"},
    {"hanzi": "充满", "pinyin": "chōngmǎn", "english": "to be full of"},
    {"hanzi": "重复", "pinyin": "chóngfù", "english": "to repeat"},
    {"hanzi": "抽", "pinyin": "chōu", "english": "to draw out"},
    {"hanzi": "出差", "pinyin": "chūchāi", "english": "to go on a business trip"},
    {"hanzi": "处理", "pinyin": "chǔlǐ", "english": "to handle"},
    {"hanzi": "传", "pinyin": "chuán", "english": "to pass / spread"},
    {"hanzi": "打招呼", "pinyin": "dǎ zhāohu", "english": "to greet"},
    {"hanzi": "代表", "pinyin": "dàibiǎo", "english": "to represent"},
    {"hanzi": "代替", "pinyin": "dàitì", "english": "to replace"},
    {"hanzi": "当", "pinyin": "dāng", "english": "to serve as"},
    {"hanzi": "倒", "pinyin": "dào", "english": "to pour"},
    {"hanzi": "道歉", "pinyin": "dàoqiàn", "english": "to apologize"},
    {"hanzi": "递", "pinyin": "dì", "english": "to hand over"},
    {"hanzi": "丢", "pinyin": "diū", "english": "to lose / throw"},
    {"hanzi": "发展", "pinyin": "fāzhǎn", "english": "to develop"},
    {"hanzi": "反对", "pinyin": "fǎnduì", "english": "to oppose"},
    {"hanzi": "反映", "pinyin": "fǎnyìng", "english": "to reflect"},
    {"hanzi": "翻译", "pinyin": "fānyì", "english": "to translate"},
    {"hanzi": "放弃", "pinyin": "fàngqì", "english": "to give up"},
    {"hanzi": "放松", "pinyin": "fàngsōng", "english": "to relax"},
    {"hanzi": "付", "pinyin": "fù", "english": "to pay"},
    {"hanzi": "付款", "pinyin": "fùkuǎn", "english": "to make a payment"},
    {"hanzi": "复印", "pinyin": "fùyìn", "english": "to photocopy"},
    {"hanzi": "赶", "pinyin": "gǎn", "english": "to rush / catch up"},
    {"hanzi": "感受", "pinyin": "gǎnshòu", "english": "to feel"},
    {"hanzi": "管理", "pinyin": "guǎnlǐ", "english": "to manage"},
    {"hanzi": "逛", "pinyin": "guàng", "english": "to stroll"},
    {"hanzi": "后悔", "pinyin": "hòuhuǐ", "english": "to regret"},
    {"hanzi": "呼吸", "pinyin": "hūxī", "english": "to breathe"},
    {"hanzi": "怀疑", "pinyin": "huáiyí", "english": "to doubt"},
    {"hanzi": "回忆", "pinyin": "huíyì", "english": "to recall"},
    {"hanzi": "加班", "pinyin": "jiābān", "english": "to work overtime"},
    {"hanzi": "减肥", "pinyin": "jiǎnféi", "english": "to lose weight"},
    {"hanzi": "建设", "pinyin": "jiànshè", "english": "to construct"},
    {"hanzi": "教育", "pinyin": "jiàoyù", "english": "to educate"},
    {"hanzi": "接待", "pinyin": "jiēdài", "english": "to receive guests"},
    {"hanzi": "节约", "pinyin": "jiéyuē", "english": "to economize"},
    {"hanzi": "解释", "pinyin": "jiěshì", "english": "to explain / interpret"},
    {"hanzi": "禁止", "pinyin": "jìnzhǐ", "english": "to prohibit"},
    {"hanzi": "进行", "pinyin": "jìnxíng", "english": "to carry out"},
    {"hanzi": "举办", "pinyin": "jǔbàn", "english": "to hold (an event)"},
    {"hanzi": "拒绝", "pinyin": "jùjué", "english": "to refuse"},
    {"hanzi": "开玩笑", "pinyin": "kāi wánxiào", "english": "to joke"},
    {"hanzi": "肯定", "pinyin": "kěndìng", "english": "to affirm / certain"},
    {"hanzi": "来得及", "pinyin": "láidejí", "english": "to be in time"},
    {"hanzi": "来不及", "pinyin": "láibují", "english": "too late (to do sth)"},
    {"hanzi": "浪费", "pinyin": "làngfèi", "english": "to waste"},
    {"hanzi": "录", "pinyin": "lù", "english": "to record"},
    {"hanzi": "命令", "pinyin": "mìnglìng", "english": "to command"},
    {"hanzi": "排队", "pinyin": "páiduì", "english": "to queue up"},
    {"hanzi": "碰", "pinyin": "pèng", "english": "to bump into"},
    {"hanzi": "骗", "pinyin": "piàn", "english": "to deceive"},
    {"hanzi": "破", "pinyin": "pò", "english": "to break"},
    {"hanzi": "签", "pinyin": "qiān", "english": "to sign"},
    {"hanzi": "敲", "pinyin": "qiāo", "english": "to knock"},
    {"hanzi": "取消", "pinyin": "qǔxiāo", "english": "to cancel"},
    {"hanzi": "确定", "pinyin": "quèdìng", "english": "to confirm"},
    {"hanzi": "确认", "pinyin": "quèrèn", "english": "to verify"},
    {"hanzi": "扔", "pinyin": "rēng", "english": "to throw away"},
    {"hanzi": "商量", "pinyin": "shāngliang", "english": "to discuss"},
    {"hanzi": "伤心", "pinyin": "shāngxīn", "english": "to be sad"},
    {"hanzi": "生产", "pinyin": "shēngchǎn", "english": "to produce"},
    {"hanzi": "失望", "pinyin": "shīwàng", "english": "to be disappointed"},
    {"hanzi": "实现", "pinyin": "shíxiàn", "english": "to realize / achieve"},
    {"hanzi": "受不了", "pinyin": "shòubuliǎo", "english": "cannot stand"},
    {"hanzi": "输入", "pinyin": "shūrù", "english": "to input"},
    {"hanzi": "数", "pinyin": "shǔ", "english": "to count"},
    {"hanzi": "同情", "pinyin": "tóngqíng", "english": "to sympathize"},
    {"hanzi": "同意", "pinyin": "tóngyì", "english": "to agree"},
    {"hanzi": "偷", "pinyin": "tōu", "english": "to steal"},
    {"hanzi": "退", "pinyin": "tuì", "english": "to retreat / return"},
    {"hanzi": "吓", "pinyin": "xià", "english": "to frighten"},
    {"hanzi": "享受", "pinyin": "xiǎngshòu", "english": "to enjoy"},
    {"hanzi": "醒", "pinyin": "xǐng", "english": "to wake up"},
    {"hanzi": "修改", "pinyin": "xiūgǎi", "english": "to revise"},
    {"hanzi": "需要", "pinyin": "xūyào", "english": "to need"},
    {"hanzi": "宣布", "pinyin": "xuānbù", "english": "to announce"},
    {"hanzi": "邀请", "pinyin": "yāoqǐng", "english": "to invite"},
    {"hanzi": "引起", "pinyin": "yǐnqǐ", "english": "to cause / arouse"},
    {"hanzi": "预习", "pinyin": "yùxí", "english": "to preview / study beforehand"},
    {"hanzi": "原谅", "pinyin": "yuánliàng", "english": "to forgive"},
    {"hanzi": "愿意", "pinyin": "yuànyì", "english": "to be willing"},
    {"hanzi": "赞成", "pinyin": "zànchéng", "english": "to approve"},
    {"hanzi": "招聘", "pinyin": "zhāopìn", "english": "to recruit"},
    {"hanzi": "争论", "pinyin": "zhēnglùn", "english": "to argue / debate"},
    {"hanzi": "整理", "pinyin": "zhěnglǐ", "english": "to organize / tidy up"},
    {"hanzi": "指", "pinyin": "zhǐ", "english": "to point"},
    {"hanzi": "制造", "pinyin": "zhìzào", "english": "to manufacture"},
    {"hanzi": "主动", "pinyin": "zhǔdòng", "english": "to take initiative"},
    {"hanzi": "祝贺", "pinyin": "zhùhè", "english": "to congratulate"},
    {"hanzi": "抓紧", "pinyin": "zhuājǐn", "english": "to hurry up"},
    {"hanzi": "赚", "pinyin": "zhuàn", "english": "to earn"},
    {"hanzi": "撞", "pinyin": "zhuàng", "english": "to collide"},
    {"hanzi": "总结", "pinyin": "zǒngjié", "english": "to summarize"},
    {"hanzi": "租", "pinyin": "zū", "english": "to rent"},
    {"hanzi": "挑", "pinyin": "tiāo", "english": "to choose / pick"},
    {"hanzi": "转", "pinyin": "zhuǎn", "english": "to turn"},
    {"hanzi": "停", "pinyin": "tíng", "english": "to stop"},
    {"hanzi": "通知", "pinyin": "tōngzhī", "english": "to notify"},
    {"hanzi": "推迟", "pinyin": "tuīchí", "english": "to postpone"},
    {"hanzi": "退休", "pinyin": "tuìxiū", "english": "to retire"},
    {"hanzi": "弹", "pinyin": "tán", "english": "to play (instrument)"},
    {"hanzi": "提前", "pinyin": "tíqián", "english": "to do in advance"},
    {"hanzi": "填", "pinyin": "tián", "english": "to fill in"},
    {"hanzi": "调", "pinyin": "tiáo", "english": "to adjust"},
    {"hanzi": "养", "pinyin": "yǎng", "english": "to raise / keep"},
    {"hanzi": "装", "pinyin": "zhuāng", "english": "to install / pretend"},
    {"hanzi": "抱", "pinyin": "bào", "english": "to hold / hug"},
    {"hanzi": "报道", "pinyin": "bàodào", "english": "to report (news)"},
    {"hanzi": "表达", "pinyin": "biǎodá", "english": "to express"},
    {"hanzi": "表扬", "pinyin": "biǎoyáng", "english": "to praise"},
    {"hanzi": "补", "pinyin": "bǔ", "english": "to mend / make up"},
    {"hanzi": "采访", "pinyin": "cǎifǎng", "english": "to interview"},
    {"hanzi": "吃惊", "pinyin": "chījīng", "english": "to be surprised"},
    {"hanzi": "冲", "pinyin": "chōng", "english": "to rush / rinse"},
    {"hanzi": "存", "pinyin": "cún", "english": "to save / deposit"},
    {"hanzi": "打工", "pinyin": "dǎgōng", "english": "to do part-time work"},
    {"hanzi": "打听", "pinyin": "dǎting", "english": "to inquire"},
    {"hanzi": "导致", "pinyin": "dǎozhì", "english": "to lead to"},
    {"hanzi": "登记", "pinyin": "dēngjì", "english": "to register"},
    {"hanzi": "发挥", "pinyin": "fāhuī", "english": "to bring into play"},
    {"hanzi": "发明", "pinyin": "fāmíng", "english": "to invent"},
    {"hanzi": "分配", "pinyin": "fēnpèi", "english": "to distribute"},
    {"hanzi": "否认", "pinyin": "fǒurèn", "english": "to deny"},
    {"hanzi": "改革", "pinyin": "gǎigé", "english": "to reform"},
    {"hanzi": "告别", "pinyin": "gàobié", "english": "to say goodbye"},
    {"hanzi": "估计", "pinyin": "gūjì", "english": "to estimate"},
    {"hanzi": "鼓掌", "pinyin": "gǔzhǎng", "english": "to applaud"},
    {"hanzi": "挂号", "pinyin": "guàhào", "english": "to register (hospital)"},
    {"hanzi": "观察", "pinyin": "guānchá", "english": "to observe"},
    {"hanzi": "怪", "pinyin": "guài", "english": "to blame / strange"},
    {"hanzi": "运", "pinyin": "yùn", "english": "to transport"},
    {"hanzi": "占线", "pinyin": "zhànxiàn", "english": "line is busy"},
    {"hanzi": "组合", "pinyin": "zǔhé", "english": "to combine"},

    # ── Verbs – Communication & Thought ──
    {"hanzi": "麻烦", "pinyin": "máfan", "english": "to trouble / troublesome"},
    {"hanzi": "联合", "pinyin": "liánhé", "english": "to unite"},
    {"hanzi": "安慰", "pinyin": "ānwèi", "english": "to comfort"},
    {"hanzi": "操心", "pinyin": "cāoxīn", "english": "to worry about"},
    {"hanzi": "抱歉", "pinyin": "bàoqiàn", "english": "to be sorry"},
    {"hanzi": "讨厌", "pinyin": "tǎoyàn", "english": "to dislike / annoying"},
    {"hanzi": "下载", "pinyin": "xiàzài", "english": "to download"},
    {"hanzi": "预订", "pinyin": "yùdìng", "english": "to reserve"},
    {"hanzi": "预报", "pinyin": "yùbào", "english": "to forecast"},
    {"hanzi": "祝", "pinyin": "zhù", "english": "to wish (well)"},
    {"hanzi": "指导", "pinyin": "zhǐdǎo", "english": "to guide"},

    # ── Nouns – People & Relationships ──
    {"hanzi": "导游", "pinyin": "dǎoyóu", "english": "tour guide"},
    {"hanzi": "儿童", "pinyin": "értóng", "english": "children"},
    {"hanzi": "夫妻", "pinyin": "fūqī", "english": "married couple"},
    {"hanzi": "服务员", "pinyin": "fúwùyuán", "english": "waiter / waitress"},
    {"hanzi": "父亲", "pinyin": "fùqīn", "english": "father"},
    {"hanzi": "工程师", "pinyin": "gōngchéngshī", "english": "engineer"},
    {"hanzi": "顾客", "pinyin": "gùkè", "english": "customer"},
    {"hanzi": "华人", "pinyin": "huárén", "english": "Chinese person (overseas)"},
    {"hanzi": "伙伴", "pinyin": "huǒbàn", "english": "partner / companion"},
    {"hanzi": "护士", "pinyin": "hùshi", "english": "nurse"},
    {"hanzi": "老百姓", "pinyin": "lǎobǎixìng", "english": "common people"},
    {"hanzi": "老板", "pinyin": "lǎobǎn", "english": "boss"},
    {"hanzi": "领导", "pinyin": "lǐngdǎo", "english": "leader"},
    {"hanzi": "母亲", "pinyin": "mǔqīn", "english": "mother"},
    {"hanzi": "亲戚", "pinyin": "qīnqi", "english": "relative"},
    {"hanzi": "人口", "pinyin": "rénkǒu", "english": "population"},
    {"hanzi": "人民", "pinyin": "rénmín", "english": "people / citizens"},
    {"hanzi": "人物", "pinyin": "rénwù", "english": "character / figure"},
    {"hanzi": "售货员", "pinyin": "shòuhuòyuán", "english": "shop assistant"},
    {"hanzi": "司机", "pinyin": "sījī", "english": "driver"},
    {"hanzi": "孙子", "pinyin": "sūnzi", "english": "grandson"},
    {"hanzi": "兄弟", "pinyin": "xiōngdì", "english": "brothers"},
    {"hanzi": "运动员", "pinyin": "yùndòngyuán", "english": "athlete"},
    {"hanzi": "游客", "pinyin": "yóukè", "english": "tourist"},
    {"hanzi": "主人", "pinyin": "zhǔrén", "english": "host / owner"},
    {"hanzi": "房东", "pinyin": "fángdōng", "english": "landlord"},
    {"hanzi": "小偷", "pinyin": "xiǎotōu", "english": "thief"},

    # ── Nouns – Places & Buildings ──
    {"hanzi": "地址", "pinyin": "dìzhǐ", "english": "address"},
    {"hanzi": "公寓", "pinyin": "gōngyù", "english": "apartment"},
    {"hanzi": "工厂", "pinyin": "gōngchǎng", "english": "factory"},
    {"hanzi": "郊区", "pinyin": "jiāoqū", "english": "suburb"},
    {"hanzi": "客厅", "pinyin": "kètīng", "english": "living room"},
    {"hanzi": "理发店", "pinyin": "lǐfàdiàn", "english": "barbershop"},
    {"hanzi": "旅馆", "pinyin": "lǚguǎn", "english": "hotel"},
    {"hanzi": "入口", "pinyin": "rùkǒu", "english": "entrance"},
    {"hanzi": "社区", "pinyin": "shèqū", "english": "community"},
    {"hanzi": "首都", "pinyin": "shǒudū", "english": "capital city"},
    {"hanzi": "停车场", "pinyin": "tíngchēchǎng", "english": "parking lot"},
    {"hanzi": "卧室", "pinyin": "wòshì", "english": "bedroom"},
    {"hanzi": "院子", "pinyin": "yuànzi", "english": "courtyard"},
    {"hanzi": "宿舍", "pinyin": "sùshè", "english": "dormitory"},

    # ── Nouns – Objects & Items ──
    {"hanzi": "电梯", "pinyin": "diàntī", "english": "elevator"},
    {"hanzi": "电子邮件", "pinyin": "diànzǐ yóujiàn", "english": "email"},
    {"hanzi": "钢琴", "pinyin": "gāngqín", "english": "piano"},
    {"hanzi": "工具", "pinyin": "gōngjù", "english": "tool"},
    {"hanzi": "家具", "pinyin": "jiājù", "english": "furniture"},
    {"hanzi": "戒指", "pinyin": "jièzhi", "english": "ring (jewelry)"},
    {"hanzi": "镜子", "pinyin": "jìngzi", "english": "mirror"},
    {"hanzi": "空调", "pinyin": "kōngtiáo", "english": "air conditioner"},
    {"hanzi": "垃圾桶", "pinyin": "lājītǒng", "english": "trash can"},
    {"hanzi": "蜡烛", "pinyin": "làzhú", "english": "candle"},
    {"hanzi": "毛巾", "pinyin": "máojīn", "english": "towel"},
    {"hanzi": "密码", "pinyin": "mìmǎ", "english": "password"},
    {"hanzi": "牌子", "pinyin": "páizi", "english": "brand / sign"},
    {"hanzi": "瓶子", "pinyin": "píngzi", "english": "bottle"},
    {"hanzi": "沙发", "pinyin": "shāfā", "english": "sofa"},
    {"hanzi": "扇子", "pinyin": "shànzi", "english": "fan"},
    {"hanzi": "勺子", "pinyin": "sháozi", "english": "spoon"},
    {"hanzi": "手表", "pinyin": "shǒubiǎo", "english": "watch"},
    {"hanzi": "钥匙", "pinyin": "yàoshi", "english": "key"},
    {"hanzi": "碗", "pinyin": "wǎn", "english": "bowl"},
    {"hanzi": "袜子", "pinyin": "wàzi", "english": "socks"},
    {"hanzi": "裤子", "pinyin": "kùzi", "english": "pants"},
    {"hanzi": "裙子", "pinyin": "qúnzi", "english": "skirt"},
    {"hanzi": "暖气", "pinyin": "nuǎnqì", "english": "heating"},
    {"hanzi": "铁", "pinyin": "tiě", "english": "iron"},
    {"hanzi": "零件", "pinyin": "língjiàn", "english": "spare part"},

    # ── Nouns – Food & Drink ──
    {"hanzi": "酒", "pinyin": "jiǔ", "english": "alcohol / wine"},
    {"hanzi": "咖啡", "pinyin": "kāfēi", "english": "coffee"},
    {"hanzi": "啤酒", "pinyin": "píjiǔ", "english": "beer"},
    {"hanzi": "葡萄", "pinyin": "pútao", "english": "grape"},
    {"hanzi": "肉", "pinyin": "ròu", "english": "meat"},
    {"hanzi": "蔬菜", "pinyin": "shūcài", "english": "vegetables"},
    {"hanzi": "酸奶", "pinyin": "suānnǎi", "english": "yogurt"},
    {"hanzi": "甜点", "pinyin": "tiándiǎn", "english": "dessert"},
    {"hanzi": "西红柿", "pinyin": "xīhóngshì", "english": "tomato"},
    {"hanzi": "饮料", "pinyin": "yǐnliào", "english": "beverage"},
    {"hanzi": "巧克力", "pinyin": "qiǎokèlì", "english": "chocolate"},
    {"hanzi": "早餐", "pinyin": "zǎocān", "english": "breakfast"},
    {"hanzi": "食品", "pinyin": "shípǐn", "english": "food product"},
    {"hanzi": "口味", "pinyin": "kǒuwèi", "english": "taste / flavor"},
    {"hanzi": "味道", "pinyin": "wèidào", "english": "taste / flavor"},

    # ── Nouns – Nature & Animals ──
    {"hanzi": "老虎", "pinyin": "lǎohǔ", "english": "tiger"},
    {"hanzi": "猴子", "pinyin": "hóuzi", "english": "monkey"},
    {"hanzi": "蛇", "pinyin": "shé", "english": "snake"},
    {"hanzi": "龙", "pinyin": "lóng", "english": "dragon"},
    {"hanzi": "竹子", "pinyin": "zhúzi", "english": "bamboo"},
    {"hanzi": "石头", "pinyin": "shítou", "english": "stone / rock"},
    {"hanzi": "土地", "pinyin": "tǔdì", "english": "land"},
    {"hanzi": "天空", "pinyin": "tiānkōng", "english": "sky"},
    {"hanzi": "阳光", "pinyin": "yángguāng", "english": "sunshine"},
    {"hanzi": "火", "pinyin": "huǒ", "english": "fire"},
    {"hanzi": "烟", "pinyin": "yān", "english": "smoke / cigarette"},
    {"hanzi": "山", "pinyin": "shān", "english": "mountain"},

    # ── Nouns – Society & Culture ──
    {"hanzi": "法律", "pinyin": "fǎlǜ", "english": "law"},
    {"hanzi": "政府", "pinyin": "zhèngfǔ", "english": "government"},
    {"hanzi": "政治", "pinyin": "zhèngzhì", "english": "politics"},
    {"hanzi": "民主", "pinyin": "mínzhǔ", "english": "democracy"},
    {"hanzi": "京剧", "pinyin": "jīngjù", "english": "Peking opera"},
    {"hanzi": "文学", "pinyin": "wénxué", "english": "literature"},
    {"hanzi": "文明", "pinyin": "wénmíng", "english": "civilization"},
    {"hanzi": "美术", "pinyin": "měishù", "english": "fine arts"},
    {"hanzi": "展览", "pinyin": "zhǎnlǎn", "english": "exhibition"},
    {"hanzi": "杂志", "pinyin": "zázhì", "english": "magazine"},
    {"hanzi": "新闻", "pinyin": "xīnwén", "english": "news"},
    {"hanzi": "广播", "pinyin": "guǎngbō", "english": "broadcast"},
    {"hanzi": "诗", "pinyin": "shī", "english": "poem"},
    {"hanzi": "著作", "pinyin": "zhùzuò", "english": "written work"},
    {"hanzi": "作品", "pinyin": "zuòpǐn", "english": "work (of art)"},
    {"hanzi": "作文", "pinyin": "zuòwén", "english": "essay / composition"},
    {"hanzi": "传统", "pinyin": "chuántǒng", "english": "tradition / traditional"},
    {"hanzi": "活动", "pinyin": "huódòng", "english": "activity"},
    {"hanzi": "晚会", "pinyin": "wǎnhuì", "english": "evening party"},
    {"hanzi": "演出", "pinyin": "yǎnchū", "english": "performance"},
    {"hanzi": "戏剧", "pinyin": "xìjù", "english": "drama / theater"},
    {"hanzi": "收入", "pinyin": "shōurù", "english": "income"},
    {"hanzi": "利润", "pinyin": "lìrùn", "english": "profit"},
    {"hanzi": "商品", "pinyin": "shāngpǐn", "english": "commodity / goods"},
    {"hanzi": "商业", "pinyin": "shāngyè", "english": "business / commerce"},

    # ── Nouns – Science & Technology ──
    {"hanzi": "技术", "pinyin": "jìshù", "english": "technology"},
    {"hanzi": "科技", "pinyin": "kējì", "english": "science and technology"},
    {"hanzi": "化学", "pinyin": "huàxué", "english": "chemistry"},
    {"hanzi": "物理", "pinyin": "wùlǐ", "english": "physics"},
    {"hanzi": "数据", "pinyin": "shùjù", "english": "data"},
    {"hanzi": "数字", "pinyin": "shùzì", "english": "number / digit"},
    {"hanzi": "系统", "pinyin": "xìtǒng", "english": "system"},
    {"hanzi": "金属", "pinyin": "jīnshǔ", "english": "metal"},
    {"hanzi": "丝绸", "pinyin": "sīchóu", "english": "silk"},
    {"hanzi": "塑料", "pinyin": "sùliào", "english": "plastic"},
    {"hanzi": "汽油", "pinyin": "qìyóu", "english": "gasoline"},
    {"hanzi": "矿", "pinyin": "kuàng", "english": "mine / mineral"},
    {"hanzi": "功能", "pinyin": "gōngnéng", "english": "function"},
    {"hanzi": "通讯", "pinyin": "tōngxùn", "english": "communication"},
    {"hanzi": "频道", "pinyin": "píndào", "english": "channel"},

    # ── Nouns – Abstract Concepts ──
    {"hanzi": "答案", "pinyin": "dá'àn", "english": "answer"},
    {"hanzi": "方式", "pinyin": "fāngshì", "english": "way / manner"},
    {"hanzi": "风格", "pinyin": "fēnggé", "english": "style"},
    {"hanzi": "感情", "pinyin": "gǎnqíng", "english": "feelings / emotions"},
    {"hanzi": "关键", "pinyin": "guānjiàn", "english": "key point"},
    {"hanzi": "观点", "pinyin": "guāndiǎn", "english": "viewpoint"},
    {"hanzi": "规律", "pinyin": "guīlǜ", "english": "pattern / law"},
    {"hanzi": "过程", "pinyin": "guòchéng", "english": "process"},
    {"hanzi": "基础", "pinyin": "jīchǔ", "english": "foundation"},
    {"hanzi": "阶段", "pinyin": "jiēduàn", "english": "stage / phase"},
    {"hanzi": "结构", "pinyin": "jiégòu", "english": "structure"},
    {"hanzi": "结论", "pinyin": "jiélùn", "english": "conclusion"},
    {"hanzi": "理想", "pinyin": "lǐxiǎng", "english": "ideal"},
    {"hanzi": "面积", "pinyin": "miànjī", "english": "area (size)"},
    {"hanzi": "目标", "pinyin": "mùbiāo", "english": "goal / target"},
    {"hanzi": "前途", "pinyin": "qiántú", "english": "future prospect"},
    {"hanzi": "情景", "pinyin": "qíngjǐng", "english": "scene / situation"},
    {"hanzi": "生命", "pinyin": "shēngmìng", "english": "life"},
    {"hanzi": "生意", "pinyin": "shēngyì", "english": "business"},
    {"hanzi": "事实", "pinyin": "shìshí", "english": "fact"},
    {"hanzi": "思想", "pinyin": "sīxiǎng", "english": "thought / ideology"},
    {"hanzi": "效果", "pinyin": "xiàoguǒ", "english": "effect / result"},
    {"hanzi": "效率", "pinyin": "xiàolǜ", "english": "efficiency"},
    {"hanzi": "心情", "pinyin": "xīnqíng", "english": "mood"},
    {"hanzi": "心理", "pinyin": "xīnlǐ", "english": "psychology"},
    {"hanzi": "印象", "pinyin": "yìnxiàng", "english": "impression"},
    {"hanzi": "友谊", "pinyin": "yǒuyì", "english": "friendship"},
    {"hanzi": "质量", "pinyin": "zhìliàng", "english": "quality"},
    {"hanzi": "状态", "pinyin": "zhuàngtài", "english": "state / condition"},
    {"hanzi": "资料", "pinyin": "zīliào", "english": "material / data"},
    {"hanzi": "种类", "pinyin": "zhǒnglèi", "english": "type / kind"},
    {"hanzi": "现实", "pinyin": "xiànshí", "english": "reality"},
    {"hanzi": "现象", "pinyin": "xiànxiàng", "english": "phenomenon"},
    {"hanzi": "行为", "pinyin": "xíngwéi", "english": "behavior"},
    {"hanzi": "身份", "pinyin": "shēnfèn", "english": "identity"},
    {"hanzi": "消费", "pinyin": "xiāofèi", "english": "consumption"},
    {"hanzi": "痛苦", "pinyin": "tòngkǔ", "english": "pain / suffering"},
    {"hanzi": "动作", "pinyin": "dòngzuò", "english": "action / movement"},
    {"hanzi": "对话", "pinyin": "duìhuà", "english": "dialogue"},
    {"hanzi": "温度", "pinyin": "wēndù", "english": "temperature"},
    {"hanzi": "顺序", "pinyin": "shùnxù", "english": "order / sequence"},

    # ── Nouns – Body & Health ──
    {"hanzi": "头发", "pinyin": "tóufa", "english": "hair"},
    {"hanzi": "皮肤", "pinyin": "pífū", "english": "skin"},
    {"hanzi": "牙齿", "pinyin": "yáchǐ", "english": "tooth"},
    {"hanzi": "血", "pinyin": "xuè", "english": "blood"},
    {"hanzi": "手术", "pinyin": "shǒushù", "english": "surgery"},
    {"hanzi": "健康", "pinyin": "jiànkāng", "english": "health"},
    {"hanzi": "脑袋", "pinyin": "nǎodai", "english": "head / brain"},

    # ── Nouns – Education & Work ──
    {"hanzi": "职业", "pinyin": "zhíyè", "english": "profession"},
    {"hanzi": "学历", "pinyin": "xuélì", "english": "educational background"},
    {"hanzi": "学问", "pinyin": "xuéwen", "english": "knowledge / learning"},
    {"hanzi": "家庭", "pinyin": "jiātíng", "english": "family / household"},
    {"hanzi": "奖金", "pinyin": "jiǎngjīn", "english": "bonus"},
    {"hanzi": "合同", "pinyin": "hétong", "english": "contract"},
    {"hanzi": "文件", "pinyin": "wénjiàn", "english": "document / file"},
    {"hanzi": "账户", "pinyin": "zhànghù", "english": "account"},
    {"hanzi": "中介", "pinyin": "zhōngjiè", "english": "agency / intermediary"},
    {"hanzi": "名牌", "pinyin": "míngpái", "english": "brand name"},
    {"hanzi": "字幕", "pinyin": "zìmù", "english": "subtitle"},

    # ── Nouns – Time & Measurement ──
    {"hanzi": "将来", "pinyin": "jiānglái", "english": "future"},
    {"hanzi": "年代", "pinyin": "niándài", "english": "era / decade"},
    {"hanzi": "平时", "pinyin": "píngshí", "english": "usually / normally"},
    {"hanzi": "古代", "pinyin": "gǔdài", "english": "ancient times"},
    {"hanzi": "公斤", "pinyin": "gōngjīn", "english": "kilogram"},
    {"hanzi": "公里", "pinyin": "gōnglǐ", "english": "kilometer"},
    {"hanzi": "厘米", "pinyin": "límǐ", "english": "centimeter"},
    {"hanzi": "数量", "pinyin": "shùliàng", "english": "quantity"},
    {"hanzi": "元旦", "pinyin": "yuándàn", "english": "New Year's Day"},

    # ── Nouns – Geography & Travel ──
    {"hanzi": "海关", "pinyin": "hǎiguān", "english": "customs"},
    {"hanzi": "航班", "pinyin": "hángbān", "english": "flight"},
    {"hanzi": "亚洲", "pinyin": "yàzhōu", "english": "Asia"},
    {"hanzi": "墙", "pinyin": "qiáng", "english": "wall"},
    {"hanzi": "周围", "pinyin": "zhōuwéi", "english": "surroundings"},
    {"hanzi": "对面", "pinyin": "duìmiàn", "english": "opposite side"},
    {"hanzi": "中心", "pinyin": "zhōngxīn", "english": "center"},

    # ── Nouns – Sports & Recreation ──
    {"hanzi": "排球", "pinyin": "páiqiú", "english": "volleyball"},
    {"hanzi": "乒乓球", "pinyin": "pīngpāngqiú", "english": "table tennis"},
    {"hanzi": "网球", "pinyin": "wǎngqiú", "english": "tennis"},
    {"hanzi": "太极拳", "pinyin": "tàijíquán", "english": "Tai Chi"},
    {"hanzi": "笑话", "pinyin": "xiàohua", "english": "joke"},

    # ── Nouns – Miscellaneous ──
    {"hanzi": "手工", "pinyin": "shǒugōng", "english": "handmade / handcraft"},
    {"hanzi": "座", "pinyin": "zuò", "english": "seat (measure word)"},
    {"hanzi": "台", "pinyin": "tái", "english": "platform / measure word"},
    {"hanzi": "楼", "pinyin": "lóu", "english": "building / floor"},
    {"hanzi": "样子", "pinyin": "yàngzi", "english": "appearance / manner"},
    {"hanzi": "礼拜", "pinyin": "lǐbài", "english": "week / worship"},
    {"hanzi": "礼貌", "pinyin": "lǐmào", "english": "politeness"},
    {"hanzi": "水平", "pinyin": "shuǐpíng", "english": "level / standard"},
    {"hanzi": "农业", "pinyin": "nóngyè", "english": "agriculture"},
    {"hanzi": "大约", "pinyin": "dàyuē", "english": "approximately"},

    # ── Adjectives – Description & Quality ──
    {"hanzi": "暗", "pinyin": "àn", "english": "dark"},
    {"hanzi": "傲慢", "pinyin": "àomàn", "english": "arrogant"},
    {"hanzi": "出色", "pinyin": "chūsè", "english": "outstanding"},
    {"hanzi": "大方", "pinyin": "dàfang", "english": "generous"},
    {"hanzi": "活泼", "pinyin": "huópō", "english": "lively"},
    {"hanzi": "谦虚", "pinyin": "qiānxū", "english": "modest"},
    {"hanzi": "勤奋", "pinyin": "qínfèn", "english": "diligent"},
    {"hanzi": "确实", "pinyin": "quèshí", "english": "indeed / truly"},
    {"hanzi": "普遍", "pinyin": "pǔbiàn", "english": "common / universal"},
    {"hanzi": "明显", "pinyin": "míngxiǎn", "english": "obvious"},
    {"hanzi": "具体", "pinyin": "jùtǐ", "english": "specific / concrete"},
    {"hanzi": "了不起", "pinyin": "liǎobuqǐ", "english": "amazing"},
    {"hanzi": "成熟", "pinyin": "chéngshú", "english": "mature"},
    {"hanzi": "粗", "pinyin": "cū", "english": "coarse / thick"},
    {"hanzi": "单调", "pinyin": "dāndiào", "english": "monotonous"},
    {"hanzi": "淡", "pinyin": "dàn", "english": "light / bland"},
    {"hanzi": "低", "pinyin": "dī", "english": "low"},
    {"hanzi": "典型", "pinyin": "diǎnxíng", "english": "typical"},
    {"hanzi": "独立", "pinyin": "dúlì", "english": "independent"},
    {"hanzi": "独特", "pinyin": "dútè", "english": "unique"},
    {"hanzi": "烦", "pinyin": "fán", "english": "annoyed"},
    {"hanzi": "方便", "pinyin": "fāngbiàn", "english": "convenient"},
    {"hanzi": "公平", "pinyin": "gōngpíng", "english": "fair"},
    {"hanzi": "古老", "pinyin": "gǔlǎo", "english": "ancient"},
    {"hanzi": "固定", "pinyin": "gùdìng", "english": "fixed"},
    {"hanzi": "广泛", "pinyin": "guǎngfàn", "english": "extensive"},
    {"hanzi": "豪华", "pinyin": "háohuá", "english": "luxurious"},
    {"hanzi": "合理", "pinyin": "hélǐ", "english": "reasonable"},
    {"hanzi": "和平", "pinyin": "hépíng", "english": "peaceful"},
    {"hanzi": "糊涂", "pinyin": "hútu", "english": "confused / muddled"},
    {"hanzi": "滑", "pinyin": "huá", "english": "slippery"},
    {"hanzi": "灰", "pinyin": "huī", "english": "grey"},
    {"hanzi": "灰心", "pinyin": "huīxīn", "english": "discouraged"},
    {"hanzi": "急", "pinyin": "jí", "english": "urgent"},
    {"hanzi": "寂寞", "pinyin": "jìmò", "english": "lonely"},
    {"hanzi": "尖", "pinyin": "jiān", "english": "sharp / pointed"},
    {"hanzi": "艰苦", "pinyin": "jiānkǔ", "english": "arduous"},
    {"hanzi": "结实", "pinyin": "jiēshi", "english": "sturdy"},
    {"hanzi": "紧急", "pinyin": "jǐnjí", "english": "urgent / emergency"},
    {"hanzi": "精神", "pinyin": "jīngshén", "english": "spirit / energetic"},
    {"hanzi": "巨大", "pinyin": "jùdà", "english": "huge"},
    {"hanzi": "可靠", "pinyin": "kěkào", "english": "reliable"},
    {"hanzi": "客观", "pinyin": "kèguān", "english": "objective"},
    {"hanzi": "宽", "pinyin": "kuān", "english": "wide"},
    {"hanzi": "快乐", "pinyin": "kuàilè", "english": "happy"},
    {"hanzi": "冷静", "pinyin": "lěngjìng", "english": "calm"},
    {"hanzi": "良好", "pinyin": "liánghǎo", "english": "good / fine"},
    {"hanzi": "灵活", "pinyin": "línghuó", "english": "flexible"},
    {"hanzi": "流利", "pinyin": "liúlì", "english": "fluent"},
    {"hanzi": "乱", "pinyin": "luàn", "english": "messy / chaotic"},
    {"hanzi": "马虎", "pinyin": "mǎhu", "english": "careless"},
    {"hanzi": "满", "pinyin": "mǎn", "english": "full"},
    {"hanzi": "美好", "pinyin": "měihǎo", "english": "beautiful / fine"},
    {"hanzi": "密切", "pinyin": "mìqiè", "english": "close / intimate"},
    {"hanzi": "免费", "pinyin": "miǎnfèi", "english": "free of charge"},
    {"hanzi": "敏感", "pinyin": "mǐngǎn", "english": "sensitive"},
    {"hanzi": "难受", "pinyin": "nánshòu", "english": "uncomfortable"},
    {"hanzi": "平等", "pinyin": "píngděng", "english": "equal"},
    {"hanzi": "平凡", "pinyin": "píngfán", "english": "ordinary"},
    {"hanzi": "平静", "pinyin": "píngjìng", "english": "calm / tranquil"},
    {"hanzi": "朴素", "pinyin": "pǔsù", "english": "plain / simple"},
    {"hanzi": "强", "pinyin": "qiáng", "english": "strong"},
    {"hanzi": "强烈", "pinyin": "qiángliè", "english": "intense"},
    {"hanzi": "巧妙", "pinyin": "qiǎomiào", "english": "clever / ingenious"},
    {"hanzi": "勤劳", "pinyin": "qínláo", "english": "hardworking"},
    {"hanzi": "清楚", "pinyin": "qīngchu", "english": "clear"},
    {"hanzi": "轻松", "pinyin": "qīngsōng", "english": "relaxed / easy"},
    {"hanzi": "温暖", "pinyin": "wēnnuǎn", "english": "warm"},
    {"hanzi": "凉快", "pinyin": "liángkuai", "english": "cool (weather)"},
    {"hanzi": "年轻", "pinyin": "niánqīng", "english": "young"},
    {"hanzi": "现代", "pinyin": "xiàndài", "english": "modern"},
    {"hanzi": "真实", "pinyin": "zhēnshí", "english": "real / true"},
    {"hanzi": "整个", "pinyin": "zhěnggè", "english": "entire / whole"},
    {"hanzi": "突然", "pinyin": "tūrán", "english": "sudden"},
    {"hanzi": "完全", "pinyin": "wánquán", "english": "complete / fully"},
    {"hanzi": "危险", "pinyin": "wēixiǎn", "english": "dangerous"},
    {"hanzi": "幸运", "pinyin": "xìngyùn", "english": "lucky"},
    {"hanzi": "友好", "pinyin": "yǒuhǎo", "english": "friendly"},
    {"hanzi": "全面", "pinyin": "quánmiàn", "english": "comprehensive"},
    {"hanzi": "深刻", "pinyin": "shēnkè", "english": "profound"},

    # ── Adjectives – Character & Emotion ──
    {"hanzi": "抽象", "pinyin": "chōuxiàng", "english": "abstract"},
    {"hanzi": "活跃", "pinyin": "huóyuè", "english": "active"},
    {"hanzi": "骄傲", "pinyin": "jiāo'ào", "english": "proud / arrogant"},
    {"hanzi": "热闹", "pinyin": "rènao", "english": "lively / bustling"},
    {"hanzi": "伤害", "pinyin": "shānghài", "english": "to harm / injury"},
    {"hanzi": "详细", "pinyin": "xiángxì", "english": "detailed"},
    {"hanzi": "严重", "pinyin": "yánzhòng", "english": "serious / severe"},
    {"hanzi": "优美", "pinyin": "yōuměi", "english": "graceful / fine"},
    {"hanzi": "永远", "pinyin": "yǒngyuǎn", "english": "forever"},
    {"hanzi": "有利", "pinyin": "yǒulì", "english": "favorable"},
    {"hanzi": "正式", "pinyin": "zhèngshì", "english": "formal / official"},
    {"hanzi": "干燥", "pinyin": "gānzào", "english": "dry"},
    {"hanzi": "相当", "pinyin": "xiāngdāng", "english": "quite / fairly"},
    {"hanzi": "性别", "pinyin": "xìngbié", "english": "gender"},
    {"hanzi": "富", "pinyin": "fù", "english": "rich / wealthy"},
    {"hanzi": "傻", "pinyin": "shǎ", "english": "silly / foolish"},
    {"hanzi": "硬", "pinyin": "yìng", "english": "hard / stiff"},
    {"hanzi": "嫩", "pinyin": "nèn", "english": "tender"},
    {"hanzi": "肥", "pinyin": "féi", "english": "fat / fertile"},

    # ── Adverbs & Conjunctions ──
    {"hanzi": "另外", "pinyin": "lìngwài", "english": "other / besides"},
    {"hanzi": "偶尔", "pinyin": "ǒu'ěr", "english": "occasionally"},
    {"hanzi": "仍然", "pinyin": "réngrán", "english": "still / yet"},
    {"hanzi": "稍微", "pinyin": "shāowēi", "english": "slightly"},
    {"hanzi": "甚至", "pinyin": "shènzhì", "english": "even (to the point)"},
    {"hanzi": "实际", "pinyin": "shíjì", "english": "actual / reality"},
    {"hanzi": "实在", "pinyin": "shízài", "english": "really / truly"},
    {"hanzi": "首先", "pinyin": "shǒuxiān", "english": "first of all"},
    {"hanzi": "尽管", "pinyin": "jǐnguǎn", "english": "despite / even though"},
    {"hanzi": "尽量", "pinyin": "jǐnliàng", "english": "to the best of one's ability"},
    {"hanzi": "竟然", "pinyin": "jìngrán", "english": "unexpectedly"},
    {"hanzi": "于是", "pinyin": "yúshì", "english": "thereupon / so"},
    {"hanzi": "因此", "pinyin": "yīncǐ", "english": "therefore"},
    {"hanzi": "也许", "pinyin": "yěxǔ", "english": "perhaps"},
    {"hanzi": "暂时", "pinyin": "zànshí", "english": "temporarily"},
    {"hanzi": "至少", "pinyin": "zhìshǎo", "english": "at least"},
    {"hanzi": "重新", "pinyin": "chóngxīn", "english": "again / anew"},
    {"hanzi": "专门", "pinyin": "zhuānmén", "english": "specially"},
    {"hanzi": "准确", "pinyin": "zhǔnquè", "english": "accurate"},
    {"hanzi": "分别", "pinyin": "fēnbié", "english": "respectively / separately"},
    {"hanzi": "顺便", "pinyin": "shùnbiàn", "english": "conveniently / in passing"},
    {"hanzi": "随便", "pinyin": "suíbiàn", "english": "casual / as one pleases"},
    {"hanzi": "正好", "pinyin": "zhènghǎo", "english": "just right / exactly"},
    {"hanzi": "十分", "pinyin": "shífēn", "english": "very / fully"},
    {"hanzi": "彼此", "pinyin": "bǐcǐ", "english": "each other"},
    {"hanzi": "果然", "pinyin": "guǒrán", "english": "as expected"},
    {"hanzi": "难道", "pinyin": "nándào", "english": "could it be that"},
    {"hanzi": "然而", "pinyin": "rán'ér", "english": "however"},
    {"hanzi": "无论", "pinyin": "wúlùn", "english": "no matter"},
    {"hanzi": "原来", "pinyin": "yuánlái", "english": "originally / it turns out"},
    {"hanzi": "其次", "pinyin": "qícì", "english": "secondly / next"},
    {"hanzi": "总共", "pinyin": "zǒnggòng", "english": "altogether"},
    {"hanzi": "日常", "pinyin": "rìcháng", "english": "daily / everyday"},
    {"hanzi": "往往", "pinyin": "wǎngwǎng", "english": "often / frequently"},
    {"hanzi": "例如", "pinyin": "lìrú", "english": "for example"},

    # ── Measure Words & Particles ──
    {"hanzi": "之", "pinyin": "zhī", "english": "of (literary)"},
    {"hanzi": "项", "pinyin": "xiàng", "english": "item / measure word"},
    {"hanzi": "种", "pinyin": "zhǒng", "english": "kind / type (measure word)"},
    {"hanzi": "片", "pinyin": "piàn", "english": "slice / piece"},
    {"hanzi": "共", "pinyin": "gòng", "english": "altogether"},
    {"hanzi": "趟", "pinyin": "tàng", "english": "measure word for trips"},
    {"hanzi": "条", "pinyin": "tiáo", "english": "strip / measure word"},
    {"hanzi": "盘", "pinyin": "pán", "english": "plate / measure word"},

    # ── Phrases & Expressions ──
    {"hanzi": "可惜", "pinyin": "kěxī", "english": "it's a pity"},
    {"hanzi": "恐怕", "pinyin": "kǒngpà", "english": "I'm afraid that"},
    {"hanzi": "千万", "pinyin": "qiānwàn", "english": "by all means / absolutely"},
    {"hanzi": "一切", "pinyin": "yīqiè", "english": "everything / all"},
    {"hanzi": "一般", "pinyin": "yībān", "english": "ordinary / general"},
    {"hanzi": "以为", "pinyin": "yǐwéi", "english": "to think (mistakenly)"},
    {"hanzi": "意义", "pinyin": "yìyì", "english": "meaning / significance"},
    {"hanzi": "同时", "pinyin": "tóngshí", "english": "at the same time"},
    {"hanzi": "没关系", "pinyin": "méi guānxi", "english": "it doesn't matter"},
    {"hanzi": "优惠", "pinyin": "yōuhuì", "english": "discount / preferential"},
    {"hanzi": "尤其", "pinyin": "yóuqí", "english": "especially"},
    {"hanzi": "有时", "pinyin": "yǒushí", "english": "sometimes"},
    {"hanzi": "主意", "pinyin": "zhǔyi", "english": "idea / plan"},
    {"hanzi": "自信", "pinyin": "zìxìn", "english": "self-confident"},
    {"hanzi": "亲爱", "pinyin": "qīn'ài", "english": "dear / beloved"},
    {"hanzi": "上当", "pinyin": "shàngdàng", "english": "to be deceived"},
    {"hanzi": "真正", "pinyin": "zhēnzhèng", "english": "genuine / true"},
    {"hanzi": "要不", "pinyin": "yàobù", "english": "otherwise / or else"},
    {"hanzi": "特点", "pinyin": "tèdiǎn", "english": "characteristic"},
    {"hanzi": "特色", "pinyin": "tèsè", "english": "distinguishing feature"},
    {"hanzi": "中间", "pinyin": "zhōngjiān", "english": "middle / between"},
    {"hanzi": "落后", "pinyin": "luòhòu", "english": "backward / to fall behind"},
    {"hanzi": "留言", "pinyin": "liúyán", "english": "to leave a message"},
    {"hanzi": "内", "pinyin": "nèi", "english": "inner / within"},

    # ── Additional Nouns ──
    {"hanzi": "语气", "pinyin": "yǔqì", "english": "tone (of speech)"},
    {"hanzi": "压力", "pinyin": "yālì", "english": "pressure"},
    {"hanzi": "盐", "pinyin": "yán", "english": "salt"},
    {"hanzi": "夜", "pinyin": "yè", "english": "night"},
    {"hanzi": "消息", "pinyin": "xiāoxi", "english": "news / message"},
    {"hanzi": "信任", "pinyin": "xìnrèn", "english": "trust"},
    {"hanzi": "装饰", "pinyin": "zhuāngshì", "english": "decoration"},
    {"hanzi": "网络", "pinyin": "wǎngluò", "english": "network / internet"},
    {"hanzi": "卫生", "pinyin": "wèishēng", "english": "hygiene / sanitation"},
    {"hanzi": "动画片", "pinyin": "dònghuàpiàn", "english": "cartoon / animation"},

    # ── Additional Verbs ──
    {"hanzi": "吸烟", "pinyin": "xīyān", "english": "to smoke"},
    {"hanzi": "洗澡", "pinyin": "xǐzǎo", "english": "to take a bath"},
    {"hanzi": "入", "pinyin": "rù", "english": "to enter"},
    {"hanzi": "散", "pinyin": "sàn", "english": "to scatter / dismiss"},
    {"hanzi": "死", "pinyin": "sǐ", "english": "to die"},
    {"hanzi": "恋爱", "pinyin": "liàn'ài", "english": "to be in love"},
    {"hanzi": "留学", "pinyin": "liúxué", "english": "to study abroad"},
    {"hanzi": "冒险", "pinyin": "màoxiǎn", "english": "to take a risk"},
    {"hanzi": "摸", "pinyin": "mō", "english": "to touch / feel"},
    {"hanzi": "缺点", "pinyin": "quēdiǎn", "english": "shortcoming"},
    {"hanzi": "脏", "pinyin": "zāng", "english": "dirty"},
    {"hanzi": "座位", "pinyin": "zuòwèi", "english": "seat"},
    {"hanzi": "勇气", "pinyin": "yǒngqì", "english": "courage"},
    {"hanzi": "标点", "pinyin": "biāodiǎn", "english": "punctuation"},
    {"hanzi": "窗帘", "pinyin": "chuānglián", "english": "curtain"},
    {"hanzi": "大象", "pinyin": "dàxiàng", "english": "elephant"},
    {"hanzi": "粉红", "pinyin": "fěnhóng", "english": "pink"},
    {"hanzi": "复习", "pinyin": "fùxí", "english": "to review"},
    {"hanzi": "感激", "pinyin": "gǎnjī", "english": "to be grateful"},
    {"hanzi": "挡", "pinyin": "dǎng", "english": "to block"},
    {"hanzi": "格外", "pinyin": "géwài", "english": "especially"},
    {"hanzi": "高档", "pinyin": "gāodàng", "english": "high-end"},
    {"hanzi": "后果", "pinyin": "hòuguǒ", "english": "consequence"},
    {"hanzi": "赠送", "pinyin": "zèngsòng", "english": "to give as a gift"},

]
