"""HSK Level 3 vocabulary data."""

WORDS = [
    {"hanzi": "表示", "pinyin": "biǎoshì", "english": "to express / to indicate"},
    {"hanzi": "表演", "pinyin": "biǎoyǎn", "english": "to perform"},
    {"hanzi": "参加", "pinyin": "cānjiā", "english": "to participate"},
    {"hanzi": "迟到", "pinyin": "chídào", "english": "to be late"},
    {"hanzi": "出发", "pinyin": "chūfā", "english": "to set off / to depart"},
    {"hanzi": "打扫", "pinyin": "dǎsǎo", "english": "to clean up"},
    {"hanzi": "打算", "pinyin": "dǎsuàn", "english": "to plan / to intend"},
    {"hanzi": "发现", "pinyin": "fāxiàn", "english": "to discover"},
    {"hanzi": "放", "pinyin": "fàng", "english": "to put / to place"},
    {"hanzi": "改变", "pinyin": "gǎibiàn", "english": "to change"},
    {"hanzi": "感觉", "pinyin": "gǎnjué", "english": "to feel / feeling"},
    {"hanzi": "感谢", "pinyin": "gǎnxiè", "english": "to thank / to be grateful"},
    {"hanzi": "干", "pinyin": "gàn", "english": "to do / to work"},
    {"hanzi": "挂", "pinyin": "guà", "english": "to hang"},
    {"hanzi": "害怕", "pinyin": "hàipà", "english": "to be afraid"},
    {"hanzi": "合适", "pinyin": "héshì", "english": "suitable / appropriate"},
    {"hanzi": "花", "pinyin": "huā", "english": "to spend (money/time)"},
    {"hanzi": "获得", "pinyin": "huòdé", "english": "to obtain / to gain"},
    {"hanzi": "检查", "pinyin": "jiǎnchá", "english": "to inspect / to check"},
    {"hanzi": "减少", "pinyin": "jiǎnshǎo", "english": "to reduce / to decrease"},
    {"hanzi": "建议", "pinyin": "jiànyì", "english": "to suggest / suggestion"},
    {"hanzi": "解决", "pinyin": "jiějué", "english": "to solve / to resolve"},
    {"hanzi": "接", "pinyin": "jiē", "english": "to receive / to pick up"},
    {"hanzi": "借", "pinyin": "jiè", "english": "to borrow / to lend"},
    {"hanzi": "进步", "pinyin": "jìnbù", "english": "to improve / progress"},
    {"hanzi": "竞争", "pinyin": "jìngzhēng", "english": "to compete / competition"},
    {"hanzi": "举行", "pinyin": "jǔxíng", "english": "to hold (an event)"},
    {"hanzi": "决定", "pinyin": "juédìng", "english": "to decide"},
    {"hanzi": "考虑", "pinyin": "kǎolǜ", "english": "to consider"},
    {"hanzi": "拉", "pinyin": "lā", "english": "to pull"},
    {"hanzi": "留", "pinyin": "liú", "english": "to stay / to keep"},
    {"hanzi": "联系", "pinyin": "liánxì", "english": "to contact"},
    {"hanzi": "满意", "pinyin": "mǎnyì", "english": "to be satisfied"},
    {"hanzi": "梦", "pinyin": "mèng", "english": "to dream / dream"},
    {"hanzi": "弄", "pinyin": "nòng", "english": "to make / to handle"},
    {"hanzi": "排列", "pinyin": "páiliè", "english": "to arrange"},
    {"hanzi": "陪", "pinyin": "péi", "english": "to accompany"},
    {"hanzi": "批评", "pinyin": "pīpíng", "english": "to criticize"},
    {"hanzi": "骑", "pinyin": "qí", "english": "to ride (a bicycle/horse)"},
    {"hanzi": "请假", "pinyin": "qǐngjià", "english": "to ask for leave"},
    {"hanzi": "取", "pinyin": "qǔ", "english": "to take / to fetch"},
    {"hanzi": "缺少", "pinyin": "quēshǎo", "english": "to lack"},
    {"hanzi": "散步", "pinyin": "sànbù", "english": "to take a walk"},
    {"hanzi": "失败", "pinyin": "shībài", "english": "to fail / failure"},
    {"hanzi": "使用", "pinyin": "shǐyòng", "english": "to use"},
    {"hanzi": "收", "pinyin": "shōu", "english": "to receive / to collect"},
    {"hanzi": "输", "pinyin": "shū", "english": "to lose (a game)"},
    {"hanzi": "提高", "pinyin": "tígāo", "english": "to improve / to raise"},
    {"hanzi": "提供", "pinyin": "tígōng", "english": "to provide"},
    {"hanzi": "提醒", "pinyin": "tíxǐng", "english": "to remind"},
    {"hanzi": "讨论", "pinyin": "tǎolùn", "english": "to discuss"},
    {"hanzi": "通过", "pinyin": "tōngguò", "english": "to pass through"},
    {"hanzi": "推", "pinyin": "tuī", "english": "to push"},
    {"hanzi": "完成", "pinyin": "wánchéng", "english": "to complete"},
    {"hanzi": "误会", "pinyin": "wùhuì", "english": "to misunderstand"},
    {"hanzi": "吸引", "pinyin": "xīyǐn", "english": "to attract"},
    {"hanzi": "选择", "pinyin": "xuǎnzé", "english": "to choose"},
    {"hanzi": "要求", "pinyin": "yāoqiú", "english": "to require / requirement"},
    {"hanzi": "赢", "pinyin": "yíng", "english": "to win"},
    {"hanzi": "影响", "pinyin": "yǐngxiǎng", "english": "to influence / influence"},
    {"hanzi": "约", "pinyin": "yuē", "english": "to make an appointment"},
    {"hanzi": "允许", "pinyin": "yǔnxǔ", "english": "to allow"},
    {"hanzi": "增加", "pinyin": "zēngjiā", "english": "to increase"},
    {"hanzi": "占", "pinyin": "zhàn", "english": "to occupy"},
    {"hanzi": "值得", "pinyin": "zhídé", "english": "to be worth"},
    {"hanzi": "支持", "pinyin": "zhīchí", "english": "to support"},
    {"hanzi": "组织", "pinyin": "zǔzhī", "english": "to organize / organization"},
    {"hanzi": "尊重", "pinyin": "zūnzhòng", "english": "to respect"},
    {"hanzi": "诚实", "pinyin": "chéngshí", "english": "honest"},
    {"hanzi": "聪明", "pinyin": "cōngmíng", "english": "smart / intelligent"},
    {"hanzi": "粗心", "pinyin": "cūxīn", "english": "careless"},
    {"hanzi": "大概", "pinyin": "dàgài", "english": "roughly / probably"},
    {"hanzi": "丰富", "pinyin": "fēngfù", "english": "rich / abundant"},
    {"hanzi": "复杂", "pinyin": "fùzá", "english": "complicated"},
    {"hanzi": "孤单", "pinyin": "gūdān", "english": "lonely"},
    {"hanzi": "合格", "pinyin": "hégé", "english": "qualified"},
    {"hanzi": "厚", "pinyin": "hòu", "english": "thick"},
    {"hanzi": "积极", "pinyin": "jījí", "english": "active / positive"},
    {"hanzi": "及时", "pinyin": "jíshí", "english": "timely"},
    {"hanzi": "简单", "pinyin": "jiǎndān", "english": "simple"},
    {"hanzi": "紧张", "pinyin": "jǐnzhāng", "english": "nervous / tense"},
    {"hanzi": "精彩", "pinyin": "jīngcǎi", "english": "wonderful / brilliant"},
    {"hanzi": "开心", "pinyin": "kāixīn", "english": "happy / joyful"},
    {"hanzi": "可爱", "pinyin": "kě'ài", "english": "cute / lovely"},
    {"hanzi": "可怜", "pinyin": "kělián", "english": "pitiful"},
    {"hanzi": "苦", "pinyin": "kǔ", "english": "bitter"},
    {"hanzi": "辣", "pinyin": "là", "english": "spicy"},
    {"hanzi": "甜", "pinyin": "tián", "english": "sweet"},
    {"hanzi": "酸", "pinyin": "suān", "english": "sour"},
    {"hanzi": "咸", "pinyin": "xián", "english": "salty"},
    {"hanzi": "浪漫", "pinyin": "làngmàn", "english": "romantic"},
    {"hanzi": "乐观", "pinyin": "lèguān", "english": "optimistic"},
    {"hanzi": "厉害", "pinyin": "lìhai", "english": "amazing / intense"},
    {"hanzi": "美丽", "pinyin": "měilì", "english": "beautiful"},
    {"hanzi": "耐心", "pinyin": "nàixīn", "english": "patient / patience"},
    {"hanzi": "暖和", "pinyin": "nuǎnhuo", "english": "warm"},
    {"hanzi": "胖", "pinyin": "pàng", "english": "fat / overweight"},
    {"hanzi": "瘦", "pinyin": "shòu", "english": "thin / slim"},
    {"hanzi": "轻", "pinyin": "qīng", "english": "light (weight)"},
    {"hanzi": "穷", "pinyin": "qióng", "english": "poor"},
    {"hanzi": "认真", "pinyin": "rènzhēn", "english": "serious / earnest"},
    {"hanzi": "深", "pinyin": "shēn", "english": "deep"},
    {"hanzi": "生气", "pinyin": "shēngqì", "english": "angry"},
    {"hanzi": "无聊", "pinyin": "wúliáo", "english": "bored / boring"},
    {"hanzi": "幸福", "pinyin": "xìngfú", "english": "happy / blessed"},
    {"hanzi": "严格", "pinyin": "yángé", "english": "strict"},
    {"hanzi": "勇敢", "pinyin": "yǒnggǎn", "english": "brave"},
    {"hanzi": "优秀", "pinyin": "yōuxiù", "english": "excellent"},
    {"hanzi": "有趣", "pinyin": "yǒuqù", "english": "interesting / fun"},
    {"hanzi": "正常", "pinyin": "zhèngcháng", "english": "normal"},
    {"hanzi": "正确", "pinyin": "zhèngquè", "english": "correct"},
    {"hanzi": "著名", "pinyin": "zhùmíng", "english": "famous"},
    {"hanzi": "自然", "pinyin": "zìrán", "english": "natural / nature"},
    {"hanzi": "爱好", "pinyin": "àihào", "english": "hobby"},
    {"hanzi": "安全", "pinyin": "ānquán", "english": "safety / safe"},
    {"hanzi": "包", "pinyin": "bāo", "english": "bag / package"},
    {"hanzi": "报名", "pinyin": "bàomíng", "english": "to register / sign up"},
    {"hanzi": "倍", "pinyin": "bèi", "english": "times / fold"},
    {"hanzi": "本来", "pinyin": "běnlái", "english": "originally"},
    {"hanzi": "标准", "pinyin": "biāozhǔn", "english": "standard"},
    {"hanzi": "饼干", "pinyin": "bǐnggān", "english": "cookie / biscuit"},
    {"hanzi": "博物馆", "pinyin": "bówùguǎn", "english": "museum"},
    {"hanzi": "材料", "pinyin": "cáiliào", "english": "material"},
    {"hanzi": "餐厅", "pinyin": "cāntīng", "english": "dining hall / restaurant"},
    {"hanzi": "厕所", "pinyin": "cèsuǒ", "english": "bathroom / toilet"},
    {"hanzi": "长城", "pinyin": "Chángchéng", "english": "Great Wall"},
    {"hanzi": "城市", "pinyin": "chéngshì", "english": "city"},
    {"hanzi": "窗户", "pinyin": "chuānghu", "english": "window"},
    {"hanzi": "词语", "pinyin": "cíyǔ", "english": "word / term"},
    {"hanzi": "大使馆", "pinyin": "dàshǐguǎn", "english": "embassy"},
    {"hanzi": "大学", "pinyin": "dàxué", "english": "university"},
    {"hanzi": "道理", "pinyin": "dàolǐ", "english": "reason / principle"},
    {"hanzi": "地方", "pinyin": "dìfang", "english": "place / location"},
    {"hanzi": "地球", "pinyin": "dìqiú", "english": "Earth"},
    {"hanzi": "调查", "pinyin": "diàochá", "english": "investigation / survey"},
    {"hanzi": "动物", "pinyin": "dòngwù", "english": "animal"},
    {"hanzi": "方法", "pinyin": "fāngfǎ", "english": "method"},
    {"hanzi": "方面", "pinyin": "fāngmiàn", "english": "aspect / respect"},
    {"hanzi": "方向", "pinyin": "fāngxiàng", "english": "direction"},
    {"hanzi": "房间", "pinyin": "fángjiān", "english": "room"},
    {"hanzi": "份", "pinyin": "fèn", "english": "measure word for portions"},
    {"hanzi": "风景", "pinyin": "fēngjǐng", "english": "scenery / landscape"},
    {"hanzi": "父母", "pinyin": "fùmǔ", "english": "parents"},
    {"hanzi": "感冒", "pinyin": "gǎnmào", "english": "cold (illness)"},
    {"hanzi": "功夫", "pinyin": "gōngfu", "english": "kung fu"},
    {"hanzi": "工资", "pinyin": "gōngzī", "english": "salary / wages"},
    {"hanzi": "共同", "pinyin": "gòngtóng", "english": "common / shared"},
    {"hanzi": "广告", "pinyin": "guǎnggào", "english": "advertisement"},
    {"hanzi": "广场", "pinyin": "guǎngchǎng", "english": "square / plaza"},
    {"hanzi": "规定", "pinyin": "guīdìng", "english": "rule / regulation"},
    {"hanzi": "国家", "pinyin": "guójiā", "english": "country / nation"},
    {"hanzi": "国际", "pinyin": "guójì", "english": "international"},
    {"hanzi": "海洋", "pinyin": "hǎiyáng", "english": "ocean"},
    {"hanzi": "汉字", "pinyin": "hànzì", "english": "Chinese character"},
    {"hanzi": "行李", "pinyin": "xíngli", "english": "luggage / baggage"},
    {"hanzi": "环境", "pinyin": "huánjìng", "english": "environment"},
    {"hanzi": "机会", "pinyin": "jīhuì", "english": "opportunity"},
    {"hanzi": "计划", "pinyin": "jìhuà", "english": "plan"},
    {"hanzi": "价格", "pinyin": "jiàgé", "english": "price"},
    {"hanzi": "交通", "pinyin": "jiāotōng", "english": "traffic / transportation"},
    {"hanzi": "结果", "pinyin": "jiéguǒ", "english": "result"},
    {"hanzi": "经济", "pinyin": "jīngjì", "english": "economy"},
    {"hanzi": "经验", "pinyin": "jīngyàn", "english": "experience"},
    {"hanzi": "句子", "pinyin": "jùzi", "english": "sentence"},
    {"hanzi": "距离", "pinyin": "jùlí", "english": "distance"},
    {"hanzi": "科学", "pinyin": "kēxué", "english": "science"},
    {"hanzi": "客人", "pinyin": "kèrén", "english": "guest / visitor"},
    {"hanzi": "空气", "pinyin": "kōngqì", "english": "air"},
    {"hanzi": "口", "pinyin": "kǒu", "english": "mouth / opening"},
    {"hanzi": "矿泉水", "pinyin": "kuàngquánshuǐ", "english": "mineral water"},
    {"hanzi": "困难", "pinyin": "kùnnan", "english": "difficulty / difficult"},
    {"hanzi": "垃圾", "pinyin": "lājī", "english": "garbage / trash"},
    {"hanzi": "历史", "pinyin": "lìshǐ", "english": "history"},
    {"hanzi": "力量", "pinyin": "lìliang", "english": "power / strength"},
    {"hanzi": "练习", "pinyin": "liànxí", "english": "to practice / exercise"},
    {"hanzi": "零食", "pinyin": "língshí", "english": "snack"},
    {"hanzi": "流行", "pinyin": "liúxíng", "english": "popular / fashionable"},
    {"hanzi": "旅行", "pinyin": "lǚxíng", "english": "to travel / trip"},
    {"hanzi": "律师", "pinyin": "lǜshī", "english": "lawyer"},
    {"hanzi": "民族", "pinyin": "mínzú", "english": "nation / ethnicity"},
    {"hanzi": "目的", "pinyin": "mùdì", "english": "purpose / goal"},
    {"hanzi": "内容", "pinyin": "nèiróng", "english": "content"},
    {"hanzi": "年龄", "pinyin": "niánlíng", "english": "age"},
    {"hanzi": "农村", "pinyin": "nóngcūn", "english": "countryside / rural area"},
    {"hanzi": "普通话", "pinyin": "pǔtōnghuà", "english": "Mandarin (standard Chinese)"},
    {"hanzi": "气候", "pinyin": "qìhòu", "english": "climate"},
    {"hanzi": "签证", "pinyin": "qiānzhèng", "english": "visa"},
    {"hanzi": "情况", "pinyin": "qíngkuàng", "english": "situation"},
    {"hanzi": "任务", "pinyin": "rènwu", "english": "task / mission"},
    {"hanzi": "日记", "pinyin": "rìjì", "english": "diary"},
    {"hanzi": "森林", "pinyin": "sēnlín", "english": "forest"},
    {"hanzi": "社会", "pinyin": "shèhuì", "english": "society"},
    {"hanzi": "世界", "pinyin": "shìjiè", "english": "world"},
    {"hanzi": "数学", "pinyin": "shùxué", "english": "mathematics"},
    {"hanzi": "速度", "pinyin": "sùdù", "english": "speed"},
    {"hanzi": "塑料袋", "pinyin": "sùliàodài", "english": "plastic bag"},
    {"hanzi": "态度", "pinyin": "tàidu", "english": "attitude"},
    {"hanzi": "条件", "pinyin": "tiáojiàn", "english": "condition / requirement"},
    {"hanzi": "同事", "pinyin": "tóngshì", "english": "colleague"},
    {"hanzi": "网站", "pinyin": "wǎngzhàn", "english": "website"},
    {"hanzi": "文化", "pinyin": "wénhuà", "english": "culture"},
    {"hanzi": "文章", "pinyin": "wénzhāng", "english": "article / essay"},
    {"hanzi": "习惯", "pinyin": "xíguàn", "english": "habit / to be used to"},
    {"hanzi": "信息", "pinyin": "xìnxī", "english": "information / message"},
    {"hanzi": "性格", "pinyin": "xìnggé", "english": "personality / character"},
    {"hanzi": "学期", "pinyin": "xuéqī", "english": "semester"},
    {"hanzi": "研究", "pinyin": "yánjiū", "english": "to research / research"},
    {"hanzi": "演员", "pinyin": "yǎnyuán", "english": "actor / performer"},
    {"hanzi": "意见", "pinyin": "yìjiàn", "english": "opinion"},
    {"hanzi": "意思", "pinyin": "yìsi", "english": "meaning"},
    {"hanzi": "语法", "pinyin": "yǔfǎ", "english": "grammar"},
    {"hanzi": "语言", "pinyin": "yǔyán", "english": "language"},
    {"hanzi": "原因", "pinyin": "yuányīn", "english": "reason / cause"},
    {"hanzi": "责任", "pinyin": "zérèn", "english": "responsibility"},
    {"hanzi": "植物", "pinyin": "zhíwù", "english": "plant"},
    {"hanzi": "中文", "pinyin": "zhōngwén", "english": "Chinese (language)"},
    {"hanzi": "重点", "pinyin": "zhòngdiǎn", "english": "key point / emphasis"},
    {"hanzi": "专业", "pinyin": "zhuānyè", "english": "major / specialty"},
    {"hanzi": "自己", "pinyin": "zìjǐ", "english": "oneself"},
    {"hanzi": "作者", "pinyin": "zuòzhě", "english": "author / writer"},
]
