"""HSK Level 2 vocabulary data."""

WORDS = [
    {"hanzi": "准备", "pinyin": "zhǔnbèi", "english": "to prepare"},
    {"hanzi": "帮忙", "pinyin": "bāngmáng", "english": "to help"},
    {"hanzi": "告诉", "pinyin": "gàosu", "english": "to tell"},
    {"hanzi": "知道", "pinyin": "zhīdao", "english": "to know (a fact)"},
    {"hanzi": "觉得", "pinyin": "juéde", "english": "to feel / to think"},
    {"hanzi": "希望", "pinyin": "xīwàng", "english": "to hope / to wish"},
    {"hanzi": "开始", "pinyin": "kāishǐ", "english": "to begin / to start"},
    {"hanzi": "完", "pinyin": "wán", "english": "to finish"},
    {"hanzi": "给", "pinyin": "gěi", "english": "to give"},
    {"hanzi": "找", "pinyin": "zhǎo", "english": "to find / to look for"},
    {"hanzi": "到", "pinyin": "dào", "english": "to arrive"},
    {"hanzi": "等", "pinyin": "děng", "english": "to wait"},
    {"hanzi": "送", "pinyin": "sòng", "english": "to give (a gift) / to send"},
    {"hanzi": "让", "pinyin": "ràng", "english": "to let / to allow"},
    {"hanzi": "走", "pinyin": "zǒu", "english": "to walk"},
    {"hanzi": "跑", "pinyin": "pǎo", "english": "to run"},
    {"hanzi": "玩", "pinyin": "wán", "english": "to play / to have fun"},
    {"hanzi": "唱歌", "pinyin": "chànggē", "english": "to sing"},
    {"hanzi": "跳舞", "pinyin": "tiàowǔ", "english": "to dance"},
    {"hanzi": "旅游", "pinyin": "lǚyóu", "english": "to travel"},
    {"hanzi": "游泳", "pinyin": "yóuyǒng", "english": "to swim"},
    {"hanzi": "锻炼", "pinyin": "duànliàn", "english": "to exercise"},
    {"hanzi": "生病", "pinyin": "shēngbìng", "english": "to get sick"},
    {"hanzi": "穿", "pinyin": "chuān", "english": "to wear"},
    {"hanzi": "洗", "pinyin": "xǐ", "english": "to wash"},
    {"hanzi": "教", "pinyin": "jiāo", "english": "to teach"},
    {"hanzi": "笑", "pinyin": "xiào", "english": "to laugh / to smile"},
    {"hanzi": "哭", "pinyin": "kū", "english": "to cry"},
    {"hanzi": "关", "pinyin": "guān", "english": "to close / to turn off"},
    {"hanzi": "试", "pinyin": "shì", "english": "to try"},
    {"hanzi": "用", "pinyin": "yòng", "english": "to use"},
    {"hanzi": "拿", "pinyin": "ná", "english": "to take / to hold"},
    {"hanzi": "搬", "pinyin": "bān", "english": "to move (objects)"},
    {"hanzi": "回答", "pinyin": "huídá", "english": "to answer"},
    {"hanzi": "问", "pinyin": "wèn", "english": "to ask"},
    {"hanzi": "介绍", "pinyin": "jièshào", "english": "to introduce"},
    {"hanzi": "担心", "pinyin": "dānxīn", "english": "to worry"},
    {"hanzi": "了解", "pinyin": "liǎojiě", "english": "to understand"},
    {"hanzi": "相信", "pinyin": "xiāngxìn", "english": "to believe"},
    {"hanzi": "注意", "pinyin": "zhùyì", "english": "to pay attention"},
    {"hanzi": "长", "pinyin": "cháng", "english": "long"},
    {"hanzi": "短", "pinyin": "duǎn", "english": "short (length)"},
    {"hanzi": "新", "pinyin": "xīn", "english": "new"},
    {"hanzi": "旧", "pinyin": "jiù", "english": "old (things)"},
    {"hanzi": "快", "pinyin": "kuài", "english": "fast / quick"},
    {"hanzi": "慢", "pinyin": "màn", "english": "slow"},
    {"hanzi": "远", "pinyin": "yuǎn", "english": "far"},
    {"hanzi": "近", "pinyin": "jìn", "english": "near / close"},
    {"hanzi": "贵", "pinyin": "guì", "english": "expensive"},
    {"hanzi": "便宜", "pinyin": "piányi", "english": "cheap"},
    {"hanzi": "难", "pinyin": "nán", "english": "difficult"},
    {"hanzi": "容易", "pinyin": "róngyì", "english": "easy"},
    {"hanzi": "忙", "pinyin": "máng", "english": "busy"},
    {"hanzi": "累", "pinyin": "lèi", "english": "tired"},
    {"hanzi": "晴", "pinyin": "qíng", "english": "sunny / clear"},
    {"hanzi": "阴", "pinyin": "yīn", "english": "cloudy / overcast"},
    {"hanzi": "重要", "pinyin": "zhòngyào", "english": "important"},
    {"hanzi": "特别", "pinyin": "tèbié", "english": "special / especially"},
    {"hanzi": "安静", "pinyin": "ānjìng", "english": "quiet"},
    {"hanzi": "干净", "pinyin": "gānjìng", "english": "clean"},
    {"hanzi": "眼睛", "pinyin": "yǎnjing", "english": "eye"},
    {"hanzi": "鼻子", "pinyin": "bízi", "english": "nose"},
    {"hanzi": "耳朵", "pinyin": "ěrduo", "english": "ear"},
    {"hanzi": "嘴", "pinyin": "zuǐ", "english": "mouth"},
    {"hanzi": "头", "pinyin": "tóu", "english": "head"},
    {"hanzi": "手", "pinyin": "shǒu", "english": "hand"},
    {"hanzi": "脚", "pinyin": "jiǎo", "english": "foot"},
    {"hanzi": "身体", "pinyin": "shēntǐ", "english": "body / health"},
    {"hanzi": "脸", "pinyin": "liǎn", "english": "face"},
    {"hanzi": "腿", "pinyin": "tuǐ", "english": "leg"},
    {"hanzi": "春天", "pinyin": "chūntiān", "english": "spring"},
    {"hanzi": "夏天", "pinyin": "xiàtiān", "english": "summer"},
    {"hanzi": "秋天", "pinyin": "qiūtiān", "english": "autumn"},
    {"hanzi": "冬天", "pinyin": "dōngtiān", "english": "winter"},
    {"hanzi": "花", "pinyin": "huā", "english": "flower"},
    {"hanzi": "树", "pinyin": "shù", "english": "tree"},
    {"hanzi": "鸟", "pinyin": "niǎo", "english": "bird"},
    {"hanzi": "鱼", "pinyin": "yú", "english": "fish"},
    {"hanzi": "牛奶", "pinyin": "niúnǎi", "english": "milk"},
    {"hanzi": "鸡蛋", "pinyin": "jīdàn", "english": "egg"},
    {"hanzi": "面条", "pinyin": "miàntiáo", "english": "noodles"},
    {"hanzi": "西瓜", "pinyin": "xīguā", "english": "watermelon"},
    {"hanzi": "药", "pinyin": "yào", "english": "medicine"},
    {"hanzi": "颜色", "pinyin": "yánsè", "english": "color"},
    {"hanzi": "红", "pinyin": "hóng", "english": "red"},
    {"hanzi": "黑", "pinyin": "hēi", "english": "black"},
    {"hanzi": "白", "pinyin": "bái", "english": "white"},
    {"hanzi": "绿", "pinyin": "lǜ", "english": "green"},
    {"hanzi": "蓝", "pinyin": "lán", "english": "blue"},
    {"hanzi": "黄", "pinyin": "huáng", "english": "yellow"},
    {"hanzi": "教室", "pinyin": "jiàoshì", "english": "classroom"},
    {"hanzi": "图书馆", "pinyin": "túshūguǎn", "english": "library"},
    {"hanzi": "公园", "pinyin": "gōngyuán", "english": "park"},
    {"hanzi": "银行", "pinyin": "yínháng", "english": "bank"},
    {"hanzi": "超市", "pinyin": "chāoshì", "english": "supermarket"},
    {"hanzi": "机场", "pinyin": "jīchǎng", "english": "airport"},
    {"hanzi": "地铁", "pinyin": "dìtiě", "english": "subway"},
    {"hanzi": "公共汽车", "pinyin": "gōnggòng qìchē", "english": "bus"},
    {"hanzi": "自行车", "pinyin": "zìxíngchē", "english": "bicycle"},
    {"hanzi": "地图", "pinyin": "dìtú", "english": "map"},
    {"hanzi": "护照", "pinyin": "hùzhào", "english": "passport"},
    {"hanzi": "手机", "pinyin": "shǒujī", "english": "mobile phone"},
    {"hanzi": "照片", "pinyin": "zhàopiàn", "english": "photo"},
    {"hanzi": "报纸", "pinyin": "bàozhǐ", "english": "newspaper"},
    {"hanzi": "故事", "pinyin": "gùshi", "english": "story"},
    {"hanzi": "生日", "pinyin": "shēngrì", "english": "birthday"},
    {"hanzi": "节日", "pinyin": "jiérì", "english": "festival / holiday"},
    {"hanzi": "礼物", "pinyin": "lǐwù", "english": "gift / present"},
    {"hanzi": "作业", "pinyin": "zuòyè", "english": "homework"},
    {"hanzi": "考试", "pinyin": "kǎoshì", "english": "exam / test"},
    {"hanzi": "成绩", "pinyin": "chéngjì", "english": "score / grade"},
    {"hanzi": "问题", "pinyin": "wèntí", "english": "question / problem"},
    {"hanzi": "办法", "pinyin": "bànfǎ", "english": "method / way"},
    {"hanzi": "经理", "pinyin": "jīnglǐ", "english": "manager"},
    {"hanzi": "邻居", "pinyin": "línjū", "english": "neighbor"},
    {"hanzi": "丈夫", "pinyin": "zhàngfu", "english": "husband"},
    {"hanzi": "妻子", "pinyin": "qīzi", "english": "wife"},
    {"hanzi": "爷爷", "pinyin": "yéye", "english": "grandfather (paternal)"},
    {"hanzi": "奶奶", "pinyin": "nǎinai", "english": "grandmother (paternal)"},
    {"hanzi": "哥哥", "pinyin": "gēge", "english": "older brother"},
    {"hanzi": "姐姐", "pinyin": "jiějie", "english": "older sister"},
    {"hanzi": "弟弟", "pinyin": "dìdi", "english": "younger brother"},
    {"hanzi": "妹妹", "pinyin": "mèimei", "english": "younger sister"},
    {"hanzi": "已经", "pinyin": "yǐjīng", "english": "already"},
    {"hanzi": "一直", "pinyin": "yìzhí", "english": "always / all along"},
    {"hanzi": "还是", "pinyin": "háishi", "english": "or (in questions)"},
    {"hanzi": "或者", "pinyin": "huòzhě", "english": "or (in statements)"},
    {"hanzi": "虽然", "pinyin": "suīrán", "english": "although"},
    {"hanzi": "但是", "pinyin": "dànshì", "english": "but / however"},
    {"hanzi": "因为", "pinyin": "yīnwèi", "english": "because"},
    {"hanzi": "所以", "pinyin": "suǒyǐ", "english": "so / therefore"},
    {"hanzi": "如果", "pinyin": "rúguǒ", "english": "if"},
    {"hanzi": "可能", "pinyin": "kěnéng", "english": "possible / maybe"},
    {"hanzi": "一定", "pinyin": "yídìng", "english": "certainly / definitely"},
    {"hanzi": "必须", "pinyin": "bìxū", "english": "must / have to"},
    {"hanzi": "应该", "pinyin": "yīnggāi", "english": "should"},
    {"hanzi": "可以", "pinyin": "kěyǐ", "english": "may / can"},
    {"hanzi": "非常", "pinyin": "fēicháng", "english": "very / extremely"},
    {"hanzi": "比较", "pinyin": "bǐjiào", "english": "comparatively / fairly"},
    {"hanzi": "最", "pinyin": "zuì", "english": "most / -est"},
    {"hanzi": "比", "pinyin": "bǐ", "english": "compared to"},
    {"hanzi": "越来越", "pinyin": "yuè lái yuè", "english": "more and more"},
    {"hanzi": "马上", "pinyin": "mǎshàng", "english": "immediately / at once"},
    {"hanzi": "一起", "pinyin": "yìqǐ", "english": "together"},
    {"hanzi": "刚才", "pinyin": "gāngcái", "english": "just now"},
    {"hanzi": "经常", "pinyin": "jīngcháng", "english": "often"},
    {"hanzi": "总是", "pinyin": "zǒngshì", "english": "always"},
    {"hanzi": "终于", "pinyin": "zhōngyú", "english": "finally"},
    {"hanzi": "差不多", "pinyin": "chàbuduō", "english": "almost / about the same"},
    {"hanzi": "当然", "pinyin": "dāngrán", "english": "of course"},
    {"hanzi": "除了", "pinyin": "chúle", "english": "besides / except"},
    {"hanzi": "根据", "pinyin": "gēnjù", "english": "according to"},
    {"hanzi": "其实", "pinyin": "qíshí", "english": "actually / in fact"},
    {"hanzi": "只", "pinyin": "zhǐ", "english": "only"},
    {"hanzi": "才", "pinyin": "cái", "english": "only then / just"},
    {"hanzi": "就", "pinyin": "jiù", "english": "then / just / precisely"},
    {"hanzi": "又", "pinyin": "yòu", "english": "again (past)"},
    {"hanzi": "再", "pinyin": "zài", "english": "again (future)"},
    {"hanzi": "还", "pinyin": "hái", "english": "still / also"},
    {"hanzi": "从", "pinyin": "cóng", "english": "from"},
    {"hanzi": "离", "pinyin": "lí", "english": "away from"},
    {"hanzi": "向", "pinyin": "xiàng", "english": "toward"},
    {"hanzi": "对", "pinyin": "duì", "english": "correct / toward"},
    {"hanzi": "把", "pinyin": "bǎ", "english": "object-moving particle (bǎ)"},
    {"hanzi": "被", "pinyin": "bèi", "english": "passive marker"},
    {"hanzi": "着", "pinyin": "zhe", "english": "ongoing action particle"},
    {"hanzi": "过", "pinyin": "guò", "english": "experiential particle"},
    {"hanzi": "得", "pinyin": "de", "english": "complement particle"},
    {"hanzi": "地", "pinyin": "de", "english": "adverbial particle"},
]
