"""HSK Level 1 vocabulary data."""

WORDS = [
    {"hanzi": "我", "pinyin": "wǒ", "english": "I / me"},
    {"hanzi": "你", "pinyin": "nǐ", "english": "you"},
    {"hanzi": "他", "pinyin": "tā", "english": "he / him"},
    {"hanzi": "她", "pinyin": "tā", "english": "she / her"},
    {"hanzi": "我们", "pinyin": "wǒmen", "english": "we / us"},
    {"hanzi": "你们", "pinyin": "nǐmen", "english": "you (plural)"},
    {"hanzi": "他们", "pinyin": "tāmen", "english": "they / them"},
    {"hanzi": "这", "pinyin": "zhè", "english": "this"},
    {"hanzi": "那", "pinyin": "nà", "english": "that"},
    {"hanzi": "哪", "pinyin": "nǎ", "english": "which"},
    {"hanzi": "谁", "pinyin": "shéi", "english": "who"},
    {"hanzi": "什么", "pinyin": "shénme", "english": "what"},
    {"hanzi": "多少", "pinyin": "duōshao", "english": "how many / how much"},
    {"hanzi": "几", "pinyin": "jǐ", "english": "how many (small number)"},
    {"hanzi": "怎么", "pinyin": "zěnme", "english": "how"},
    {"hanzi": "怎么样", "pinyin": "zěnmeyàng", "english": "how about"},
    {"hanzi": "人", "pinyin": "rén", "english": "person / people"},
    {"hanzi": "爸爸", "pinyin": "bàba", "english": "father / dad"},
    {"hanzi": "妈妈", "pinyin": "māma", "english": "mother / mom"},
    {"hanzi": "儿子", "pinyin": "érzi", "english": "son"},
    {"hanzi": "女儿", "pinyin": "nǚér", "english": "daughter"},
    {"hanzi": "朋友", "pinyin": "péngyou", "english": "friend"},
    {"hanzi": "同学", "pinyin": "tóngxué", "english": "classmate"},
    {"hanzi": "老师", "pinyin": "lǎoshī", "english": "teacher"},
    {"hanzi": "学生", "pinyin": "xuésheng", "english": "student"},
    {"hanzi": "医生", "pinyin": "yīshēng", "english": "doctor"},
    {"hanzi": "先生", "pinyin": "xiānsheng", "english": "Mr. / sir"},
    {"hanzi": "小姐", "pinyin": "xiǎojiě", "english": "Miss / young lady"},
    {"hanzi": "一", "pinyin": "yī", "english": "one"},
    {"hanzi": "二", "pinyin": "èr", "english": "two"},
    {"hanzi": "三", "pinyin": "sān", "english": "three"},
    {"hanzi": "四", "pinyin": "sì", "english": "four"},
    {"hanzi": "五", "pinyin": "wǔ", "english": "five"},
    {"hanzi": "六", "pinyin": "liù", "english": "six"},
    {"hanzi": "七", "pinyin": "qī", "english": "seven"},
    {"hanzi": "八", "pinyin": "bā", "english": "eight"},
    {"hanzi": "九", "pinyin": "jiǔ", "english": "nine"},
    {"hanzi": "十", "pinyin": "shí", "english": "ten"},
    {"hanzi": "百", "pinyin": "bǎi", "english": "hundred"},
    {"hanzi": "千", "pinyin": "qiān", "english": "thousand"},
    {"hanzi": "零", "pinyin": "líng", "english": "zero"},
    {"hanzi": "个", "pinyin": "gè", "english": "general measure word"},
    {"hanzi": "岁", "pinyin": "suì", "english": "year (of age)"},
    {"hanzi": "块", "pinyin": "kuài", "english": "unit of money (yuan)"},
    {"hanzi": "些", "pinyin": "xiē", "english": "some"},
    {"hanzi": "年", "pinyin": "nián", "english": "year"},
    {"hanzi": "月", "pinyin": "yuè", "english": "month / moon"},
    {"hanzi": "日", "pinyin": "rì", "english": "day / date"},
    {"hanzi": "号", "pinyin": "hào", "english": "number / date"},
    {"hanzi": "星期", "pinyin": "xīngqī", "english": "week"},
    {"hanzi": "点", "pinyin": "diǎn", "english": "o'clock / point"},
    {"hanzi": "分钟", "pinyin": "fēnzhōng", "english": "minute"},
    {"hanzi": "今天", "pinyin": "jīntiān", "english": "today"},
    {"hanzi": "明天", "pinyin": "míngtiān", "english": "tomorrow"},
    {"hanzi": "昨天", "pinyin": "zuótiān", "english": "yesterday"},
    {"hanzi": "时候", "pinyin": "shíhou", "english": "time / moment"},
    {"hanzi": "上午", "pinyin": "shàngwǔ", "english": "morning"},
    {"hanzi": "下午", "pinyin": "xiàwǔ", "english": "afternoon"},
    {"hanzi": "现在", "pinyin": "xiànzài", "english": "now"},
    {"hanzi": "是", "pinyin": "shì", "english": "to be"},
    {"hanzi": "有", "pinyin": "yǒu", "english": "to have"},
    {"hanzi": "看", "pinyin": "kàn", "english": "to look / to see"},
    {"hanzi": "听", "pinyin": "tīng", "english": "to listen"},
    {"hanzi": "说", "pinyin": "shuō", "english": "to speak / to say"},
    {"hanzi": "读", "pinyin": "dú", "english": "to read"},
    {"hanzi": "写", "pinyin": "xiě", "english": "to write"},
    {"hanzi": "学习", "pinyin": "xuéxí", "english": "to study / to learn"},
    {"hanzi": "工作", "pinyin": "gōngzuò", "english": "to work / work"},
    {"hanzi": "住", "pinyin": "zhù", "english": "to live"},
    {"hanzi": "吃", "pinyin": "chī", "english": "to eat"},
    {"hanzi": "喝", "pinyin": "hē", "english": "to drink"},
    {"hanzi": "买", "pinyin": "mǎi", "english": "to buy"},
    {"hanzi": "去", "pinyin": "qù", "english": "to go"},
    {"hanzi": "来", "pinyin": "lái", "english": "to come"},
    {"hanzi": "回", "pinyin": "huí", "english": "to return"},
    {"hanzi": "做", "pinyin": "zuò", "english": "to do / to make"},
    {"hanzi": "坐", "pinyin": "zuò", "english": "to sit"},
    {"hanzi": "打电话", "pinyin": "dǎ diànhuà", "english": "to make a phone call"},
    {"hanzi": "想", "pinyin": "xiǎng", "english": "to think / to want"},
    {"hanzi": "喜欢", "pinyin": "xǐhuan", "english": "to like"},
    {"hanzi": "爱", "pinyin": "ài", "english": "to love"},
    {"hanzi": "叫", "pinyin": "jiào", "english": "to call / to be called"},
    {"hanzi": "开", "pinyin": "kāi", "english": "to open / to drive"},
    {"hanzi": "睡觉", "pinyin": "shuìjiào", "english": "to sleep"},
    {"hanzi": "认识", "pinyin": "rènshi", "english": "to know (someone)"},
    {"hanzi": "会", "pinyin": "huì", "english": "can / will"},
    {"hanzi": "能", "pinyin": "néng", "english": "can / able to"},
    {"hanzi": "好", "pinyin": "hǎo", "english": "good"},
    {"hanzi": "大", "pinyin": "dà", "english": "big"},
    {"hanzi": "小", "pinyin": "xiǎo", "english": "small"},
    {"hanzi": "多", "pinyin": "duō", "english": "many / much"},
    {"hanzi": "少", "pinyin": "shǎo", "english": "few / little"},
    {"hanzi": "冷", "pinyin": "lěng", "english": "cold"},
    {"hanzi": "热", "pinyin": "rè", "english": "hot"},
    {"hanzi": "高兴", "pinyin": "gāoxìng", "english": "happy"},
    {"hanzi": "漂亮", "pinyin": "piàoliang", "english": "pretty / beautiful"},
    {"hanzi": "中国", "pinyin": "Zhōngguó", "english": "China"},
    {"hanzi": "北京", "pinyin": "Běijīng", "english": "Beijing"},
    {"hanzi": "家", "pinyin": "jiā", "english": "home / family"},
    {"hanzi": "学校", "pinyin": "xuéxiào", "english": "school"},
    {"hanzi": "饭店", "pinyin": "fàndiàn", "english": "restaurant / hotel"},
    {"hanzi": "商店", "pinyin": "shāngdiàn", "english": "shop / store"},
    {"hanzi": "医院", "pinyin": "yīyuàn", "english": "hospital"},
    {"hanzi": "火车站", "pinyin": "huǒchē zhàn", "english": "train station"},
    {"hanzi": "飞机", "pinyin": "fēijī", "english": "airplane"},
    {"hanzi": "出租车", "pinyin": "chūzūchē", "english": "taxi"},
    {"hanzi": "电脑", "pinyin": "diànnǎo", "english": "computer"},
    {"hanzi": "电视", "pinyin": "diànshì", "english": "television"},
    {"hanzi": "电影", "pinyin": "diànyǐng", "english": "movie"},
    {"hanzi": "书", "pinyin": "shū", "english": "book"},
    {"hanzi": "桌子", "pinyin": "zhuōzi", "english": "table / desk"},
    {"hanzi": "椅子", "pinyin": "yǐzi", "english": "chair"},
    {"hanzi": "水", "pinyin": "shuǐ", "english": "water"},
    {"hanzi": "茶", "pinyin": "chá", "english": "tea"},
    {"hanzi": "米饭", "pinyin": "mǐfàn", "english": "rice"},
    {"hanzi": "水果", "pinyin": "shuǐguǒ", "english": "fruit"},
    {"hanzi": "苹果", "pinyin": "píngguǒ", "english": "apple"},
    {"hanzi": "菜", "pinyin": "cài", "english": "dish / vegetable"},
    {"hanzi": "天气", "pinyin": "tiānqì", "english": "weather"},
    {"hanzi": "钱", "pinyin": "qián", "english": "money"},
    {"hanzi": "猫", "pinyin": "māo", "english": "cat"},
    {"hanzi": "狗", "pinyin": "gǒu", "english": "dog"},
    {"hanzi": "衣服", "pinyin": "yīfu", "english": "clothes"},
    {"hanzi": "名字", "pinyin": "míngzi", "english": "name"},
    {"hanzi": "的", "pinyin": "de", "english": "possessive / descriptive particle"},
    {"hanzi": "了", "pinyin": "le", "english": "completed action particle"},
    {"hanzi": "不", "pinyin": "bù", "english": "not / no"},
    {"hanzi": "没", "pinyin": "méi", "english": "not (have)"},
    {"hanzi": "在", "pinyin": "zài", "english": "at / in / (ongoing action)"},
    {"hanzi": "很", "pinyin": "hěn", "english": "very"},
    {"hanzi": "都", "pinyin": "dōu", "english": "all / both"},
    {"hanzi": "也", "pinyin": "yě", "english": "also"},
    {"hanzi": "和", "pinyin": "hé", "english": "and"},
    {"hanzi": "吗", "pinyin": "ma", "english": "question particle"},
    {"hanzi": "呢", "pinyin": "ne", "english": "question particle (and you?)"},
    {"hanzi": "太", "pinyin": "tài", "english": "too (excessive)"},
    {"hanzi": "上", "pinyin": "shàng", "english": "above / on"},
    {"hanzi": "下", "pinyin": "xià", "english": "below / under"},
    {"hanzi": "前面", "pinyin": "qiánmiàn", "english": "front / ahead"},
    {"hanzi": "后面", "pinyin": "hòumiàn", "english": "behind"},
    {"hanzi": "里面", "pinyin": "lǐmiàn", "english": "inside"},
    {"hanzi": "对不起", "pinyin": "duìbuqǐ", "english": "sorry"},
    {"hanzi": "谢谢", "pinyin": "xièxie", "english": "thank you"},
    {"hanzi": "再见", "pinyin": "zàijiàn", "english": "goodbye"},
    {"hanzi": "请", "pinyin": "qǐng", "english": "please"},
    {"hanzi": "你好", "pinyin": "nǐ hǎo", "english": "hello"},
]
