"""HSK Level 5 vocabulary data."""

WORDS = [
    {"hanzi": "论文", "pinyin": "lùnwén", "english": "thesis, paper"},
    {"hanzi": "学术", "pinyin": "xuéshù", "english": "academic, scholarly"},
    {"hanzi": "教授", "pinyin": "jiàoshòu", "english": "professor"},
    {"hanzi": "导师", "pinyin": "dǎoshī", "english": "mentor, supervisor"},
    {"hanzi": "课题", "pinyin": "kètí", "english": "research topic"},
    {"hanzi": "毕业", "pinyin": "bìyè", "english": "to graduate"},
    {"hanzi": "学位", "pinyin": "xuéwèi", "english": "academic degree"},
    {"hanzi": "博士", "pinyin": "bóshì", "english": "doctoral degree"},
    {"hanzi": "硕士", "pinyin": "shuòshì", "english": "master's degree"},
    {"hanzi": "知识", "pinyin": "zhīshi", "english": "knowledge"},
    {"hanzi": "学科", "pinyin": "xuékē", "english": "academic discipline"},
    {"hanzi": "教材", "pinyin": "jiàocái", "english": "teaching materials"},
    {"hanzi": "讲座", "pinyin": "jiǎngzuò", "english": "lecture, seminar"},
    {"hanzi": "培训", "pinyin": "péixùn", "english": "training"},
    {"hanzi": "实习", "pinyin": "shíxí", "english": "internship"},
    {"hanzi": "奖学金", "pinyin": "jiǎngxuéjīn", "english": "scholarship"},
    {"hanzi": "学位证", "pinyin": "xuéwèizhèng", "english": "degree certificate"},
    {"hanzi": "课程", "pinyin": "kèchéng", "english": "course, curriculum"},
    {"hanzi": "录取", "pinyin": "lùqǔ", "english": "to admit, enroll"},
    {"hanzi": "辅导", "pinyin": "fǔdǎo", "english": "to tutor, coach"},
    {"hanzi": "学费", "pinyin": "xuéfèi", "english": "tuition fee"},
    {"hanzi": "学分", "pinyin": "xuéfēn", "english": "academic credit"},
    {"hanzi": "答辩", "pinyin": "dábìan", "english": "thesis defense"},
    {"hanzi": "选修", "pinyin": "xuǎnxiū", "english": "elective course"},
    {"hanzi": "必修", "pinyin": "bìxiū", "english": "required course"},
    {"hanzi": "学者", "pinyin": "xuézhě", "english": "scholar"},
    {"hanzi": "院校", "pinyin": "yuànxiào", "english": "colleges, schools"},
    {"hanzi": "系主任", "pinyin": "xìzhǔrèn", "english": "department chair"},
    {"hanzi": "投资", "pinyin": "tóuzī", "english": "to invest"},
    {"hanzi": "市场", "pinyin": "shìchǎng", "english": "market"},
    {"hanzi": "企业", "pinyin": "qǐyè", "english": "enterprise, company"},
    {"hanzi": "贸易", "pinyin": "màoyì", "english": "trade, commerce"},
    {"hanzi": "股票", "pinyin": "gǔpiào", "english": "stock, share"},
    {"hanzi": "金融", "pinyin": "jīnróng", "english": "finance"},
    {"hanzi": "财务", "pinyin": "cáiwù", "english": "financial affairs"},
    {"hanzi": "预算", "pinyin": "yùsuàn", "english": "budget"},
    {"hanzi": "成本", "pinyin": "chéngběn", "english": "cost"},
    {"hanzi": "产品", "pinyin": "chǎnpǐn", "english": "product"},
    {"hanzi": "品牌", "pinyin": "pǐnpái", "english": "brand"},
    {"hanzi": "资金", "pinyin": "zījīn", "english": "capital, funds"},
    {"hanzi": "税收", "pinyin": "shuìshōu", "english": "tax revenue"},
    {"hanzi": "利息", "pinyin": "lìxī", "english": "interest (financial)"},
    {"hanzi": "贷款", "pinyin": "dàikuǎn", "english": "loan"},
    {"hanzi": "货币", "pinyin": "huòbì", "english": "currency"},
    {"hanzi": "汇率", "pinyin": "huìlǜ", "english": "exchange rate"},
    {"hanzi": "盈利", "pinyin": "yínglì", "english": "profit, earnings"},
    {"hanzi": "亏损", "pinyin": "kuīsǔn", "english": "loss, deficit"},
    {"hanzi": "破产", "pinyin": "pòchǎn", "english": "bankruptcy"},
    {"hanzi": "营业", "pinyin": "yíngyè", "english": "to do business"},
    {"hanzi": "合伙", "pinyin": "héhuǒ", "english": "partnership"},
    {"hanzi": "股东", "pinyin": "gǔdōng", "english": "shareholder"},
    {"hanzi": "董事", "pinyin": "dǒngshì", "english": "board director"},
    {"hanzi": "仓库", "pinyin": "cāngkù", "english": "warehouse"},
    {"hanzi": "供应", "pinyin": "gōngyìng", "english": "to supply"},
    {"hanzi": "需求", "pinyin": "xūqiú", "english": "demand, need"},
    {"hanzi": "订单", "pinyin": "dìngdān", "english": "order form"},
    {"hanzi": "出口", "pinyin": "chūkǒu", "english": "to export"},
    {"hanzi": "进口", "pinyin": "jìnkǒu", "english": "to import"},
    {"hanzi": "批发", "pinyin": "pīfā", "english": "wholesale"},
    {"hanzi": "零售", "pinyin": "língshòu", "english": "retail"},
    {"hanzi": "促销", "pinyin": "cùxiāo", "english": "sales promotion"},
    {"hanzi": "债务", "pinyin": "zhàiwù", "english": "debt"},
    {"hanzi": "程序", "pinyin": "chéngxù", "english": "program, procedure"},
    {"hanzi": "实验", "pinyin": "shíyàn", "english": "experiment"},
    {"hanzi": "研发", "pinyin": "yánfā", "english": "research & development"},
    {"hanzi": "软件", "pinyin": "ruǎnjiàn", "english": "software"},
    {"hanzi": "硬件", "pinyin": "yìngjiàn", "english": "hardware"},
    {"hanzi": "人工", "pinyin": "réngōng", "english": "artificial, manual"},
    {"hanzi": "智能", "pinyin": "zhìnéng", "english": "intelligent, smart"},
    {"hanzi": "机器", "pinyin": "jīqì", "english": "machine"},
    {"hanzi": "操作", "pinyin": "cāozuò", "english": "to operate"},
    {"hanzi": "更新", "pinyin": "gēngxīn", "english": "to update"},
    {"hanzi": "算法", "pinyin": "suànfǎ", "english": "algorithm"},
    {"hanzi": "芯片", "pinyin": "xīnpiàn", "english": "chip, microchip"},
    {"hanzi": "数码", "pinyin": "shùmǎ", "english": "digital"},
    {"hanzi": "光纤", "pinyin": "guāngxiān", "english": "optical fiber"},
    {"hanzi": "卫星", "pinyin": "wèixīng", "english": "satellite"},
    {"hanzi": "航天", "pinyin": "hángtiān", "english": "aerospace"},
    {"hanzi": "雷达", "pinyin": "léidá", "english": "radar"},
    {"hanzi": "频率", "pinyin": "pínlǜ", "english": "frequency"},
    {"hanzi": "电池", "pinyin": "diànchí", "english": "battery"},
    {"hanzi": "充电", "pinyin": "chōngdiàn", "english": "to charge (battery)"},
    {"hanzi": "服务器", "pinyin": "fúwùqì", "english": "server (computer)"},
    {"hanzi": "数据库", "pinyin": "shùjùkù", "english": "database"},
    {"hanzi": "密钥", "pinyin": "mìyào", "english": "encryption key"},
    {"hanzi": "虚拟", "pinyin": "xūnǐ", "english": "virtual"},
    {"hanzi": "模拟", "pinyin": "mónǐ", "english": "to simulate"},
    {"hanzi": "自动化", "pinyin": "zìdònghuà", "english": "automation"},
    {"hanzi": "编程", "pinyin": "biānchéng", "english": "programming"},
    {"hanzi": "终端", "pinyin": "zhōngduān", "english": "terminal, endpoint"},
    {"hanzi": "宽带", "pinyin": "kuāndài", "english": "broadband"},
    {"hanzi": "云计算", "pinyin": "yúnjìsuàn", "english": "cloud computing"},
    {"hanzi": "触屏", "pinyin": "chùpíng", "english": "touch screen"},
    {"hanzi": "生态", "pinyin": "shēngtài", "english": "ecology, ecosystem"},
    {"hanzi": "污染", "pinyin": "wūrǎn", "english": "pollution"},
    {"hanzi": "资源", "pinyin": "zīyuán", "english": "resource"},
    {"hanzi": "能源", "pinyin": "néngyuán", "english": "energy source"},
    {"hanzi": "大气", "pinyin": "dàqì", "english": "atmosphere"},
    {"hanzi": "湿度", "pinyin": "shīdù", "english": "humidity"},
    {"hanzi": "灾害", "pinyin": "zāihài", "english": "disaster, calamity"},
    {"hanzi": "排放", "pinyin": "páifàng", "english": "to emit, discharge"},
    {"hanzi": "碳排放", "pinyin": "tànpáifàng", "english": "carbon emission"},
    {"hanzi": "臭氧", "pinyin": "chòuyǎng", "english": "ozone"},
    {"hanzi": "沙漠", "pinyin": "shāmò", "english": "desert"},
    {"hanzi": "草原", "pinyin": "cǎoyuán", "english": "grassland, prairie"},
    {"hanzi": "冰川", "pinyin": "bīngchuān", "english": "glacier"},
    {"hanzi": "火山", "pinyin": "huǒshān", "english": "volcano"},
    {"hanzi": "地震", "pinyin": "dìzhèn", "english": "earthquake"},
    {"hanzi": "洪水", "pinyin": "hóngshuǐ", "english": "flood"},
    {"hanzi": "干旱", "pinyin": "gānhàn", "english": "drought"},
    {"hanzi": "台风", "pinyin": "táifēng", "english": "typhoon"},
    {"hanzi": "物种", "pinyin": "wùzhǒng", "english": "species"},
    {"hanzi": "濒危", "pinyin": "bīnwēi", "english": "endangered"},
    {"hanzi": "回收", "pinyin": "huíshōu", "english": "to recycle"},
    {"hanzi": "可再生", "pinyin": "kězàishēng", "english": "renewable"},
    {"hanzi": "太阳能", "pinyin": "tàiyángnéng", "english": "solar energy"},
    {"hanzi": "风力", "pinyin": "fēnglì", "english": "wind power"},
    {"hanzi": "水力", "pinyin": "shuǐlì", "english": "hydropower"},
    {"hanzi": "核能", "pinyin": "hénéng", "english": "nuclear energy"},
    {"hanzi": "绿化", "pinyin": "lǜhuà", "english": "to plant greenery"},
    {"hanzi": "生物", "pinyin": "shēngwù", "english": "organism, biology"},
    {"hanzi": "土壤", "pinyin": "tǔrǎng", "english": "soil"},
    {"hanzi": "矿产", "pinyin": "kuàngchǎn", "english": "mineral resources"},
    {"hanzi": "症状", "pinyin": "zhèngzhuàng", "english": "symptom"},
    {"hanzi": "治疗", "pinyin": "zhìliáo", "english": "to treat (medical)"},
    {"hanzi": "诊断", "pinyin": "zhěnduàn", "english": "to diagnose"},
    {"hanzi": "疾病", "pinyin": "jíbìng", "english": "disease, illness"},
    {"hanzi": "药物", "pinyin": "yàowù", "english": "medicine, drug"},
    {"hanzi": "医疗", "pinyin": "yīliáo", "english": "medical treatment"},
    {"hanzi": "病人", "pinyin": "bìngrén", "english": "patient"},
    {"hanzi": "处方", "pinyin": "chǔfāng", "english": "prescription"},
    {"hanzi": "免疫", "pinyin": "miǎnyì", "english": "immunity"},
    {"hanzi": "疫苗", "pinyin": "yìmiáo", "english": "vaccine"},
    {"hanzi": "手术室", "pinyin": "shǒushùshì", "english": "operating room"},
    {"hanzi": "急诊", "pinyin": "jízhěn", "english": "emergency treatment"},
    {"hanzi": "体检", "pinyin": "tǐjiǎn", "english": "physical exam"},
    {"hanzi": "血压", "pinyin": "xuèyā", "english": "blood pressure"},
    {"hanzi": "心脏", "pinyin": "xīnzàng", "english": "heart (organ)"},
    {"hanzi": "肺", "pinyin": "fèi", "english": "lung"},
    {"hanzi": "肝", "pinyin": "gān", "english": "liver"},
    {"hanzi": "肾", "pinyin": "shèn", "english": "kidney"},
    {"hanzi": "胃", "pinyin": "wèi", "english": "stomach"},
    {"hanzi": "骨折", "pinyin": "gǔzhé", "english": "bone fracture"},
    {"hanzi": "感染", "pinyin": "gǎnrǎn", "english": "infection"},
    {"hanzi": "过敏", "pinyin": "guòmǐn", "english": "allergy"},
    {"hanzi": "糖尿病", "pinyin": "tángniàobìng", "english": "diabetes"},
    {"hanzi": "高血压", "pinyin": "gāoxuèyā", "english": "hypertension"},
    {"hanzi": "抗生素", "pinyin": "kàngshēngsù", "english": "antibiotic"},
    {"hanzi": "麻醉", "pinyin": "mázuì", "english": "anesthesia"},
    {"hanzi": "康复", "pinyin": "kāngfù", "english": "to recover, rehab"},
    {"hanzi": "门诊", "pinyin": "ménzhěn", "english": "outpatient clinic"},
    {"hanzi": "挂号费", "pinyin": "guàhàofèi", "english": "registration fee"},
    {"hanzi": "住院", "pinyin": "zhùyuàn", "english": "hospitalization"},
    {"hanzi": "法规", "pinyin": "fǎguī", "english": "law, regulation"},
    {"hanzi": "权利", "pinyin": "quánlì", "english": "right, entitlement"},
    {"hanzi": "义务", "pinyin": "yìwù", "english": "duty, obligation"},
    {"hanzi": "制度", "pinyin": "zhìdù", "english": "system, institution"},
    {"hanzi": "政策", "pinyin": "zhèngcè", "english": "policy"},
    {"hanzi": "公民", "pinyin": "gōngmín", "english": "citizen"},
    {"hanzi": "选举", "pinyin": "xuǎnjǔ", "english": "election"},
    {"hanzi": "宪法", "pinyin": "xiànfǎ", "english": "constitution"},
    {"hanzi": "立法", "pinyin": "lìfǎ", "english": "legislation"},
    {"hanzi": "司法", "pinyin": "sīfǎ", "english": "judicial"},
    {"hanzi": "法院", "pinyin": "fǎyuàn", "english": "court of law"},
    {"hanzi": "检察", "pinyin": "jiǎnchá", "english": "to prosecute"},
    {"hanzi": "审判", "pinyin": "shěnpàn", "english": "trial, judgment"},
    {"hanzi": "罪犯", "pinyin": "zuìfàn", "english": "criminal"},
    {"hanzi": "刑事", "pinyin": "xíngshì", "english": "criminal (legal)"},
    {"hanzi": "民事", "pinyin": "mínshì", "english": "civil (legal)"},
    {"hanzi": "诉讼", "pinyin": "sùsòng", "english": "lawsuit"},
    {"hanzi": "证据", "pinyin": "zhèngjù", "english": "evidence"},
    {"hanzi": "辩护", "pinyin": "biànhù", "english": "to defend (legal)"},
    {"hanzi": "判决", "pinyin": "pànjué", "english": "verdict, sentence"},
    {"hanzi": "监狱", "pinyin": "jiānyù", "english": "prison"},
    {"hanzi": "拘留", "pinyin": "jūliú", "english": "to detain"},
    {"hanzi": "罚款", "pinyin": "fákuǎn", "english": "fine, penalty"},
    {"hanzi": "执法", "pinyin": "zhífǎ", "english": "law enforcement"},
    {"hanzi": "仲裁", "pinyin": "zhòngcái", "english": "arbitration"},
    {"hanzi": "合法", "pinyin": "héfǎ", "english": "legal, lawful"},
    {"hanzi": "违法", "pinyin": "wéifǎ", "english": "illegal, unlawful"},
    {"hanzi": "纠纷", "pinyin": "jiūfēn", "english": "dispute"},
    {"hanzi": "维权", "pinyin": "wéiquán", "english": "rights protection"},
    {"hanzi": "外交", "pinyin": "wàijiāo", "english": "diplomacy"},
    {"hanzi": "国防", "pinyin": "guófáng", "english": "national defense"},
    {"hanzi": "军事", "pinyin": "jūnshì", "english": "military affairs"},
    {"hanzi": "领土", "pinyin": "lǐngtǔ", "english": "territory"},
    {"hanzi": "主权", "pinyin": "zhǔquán", "english": "sovereignty"},
    {"hanzi": "条约", "pinyin": "tiáoyuē", "english": "treaty"},
    {"hanzi": "联盟", "pinyin": "liánméng", "english": "alliance, league"},
    {"hanzi": "评估", "pinyin": "pínggū", "english": "to evaluate"},
    {"hanzi": "项目", "pinyin": "xiàngmù", "english": "project, program"},
    {"hanzi": "方案", "pinyin": "fāngàn", "english": "plan, scheme"},
    {"hanzi": "策略", "pinyin": "cèlüè", "english": "strategy"},
    {"hanzi": "目录", "pinyin": "mùlù", "english": "catalog, index"},
    {"hanzi": "档案", "pinyin": "dàngàn", "english": "file, archive"},
    {"hanzi": "咨询", "pinyin": "zīxún", "english": "to consult"},
    {"hanzi": "委托", "pinyin": "wěituō", "english": "to entrust"},
    {"hanzi": "签署", "pinyin": "qiānshǔ", "english": "to sign (document)"},
    {"hanzi": "拨款", "pinyin": "bōkuǎn", "english": "to allocate funds"},
    {"hanzi": "审批", "pinyin": "shěnpī", "english": "to approve, review"},
    {"hanzi": "招标", "pinyin": "zhāobiāo", "english": "to invite bids"},
    {"hanzi": "投标", "pinyin": "tóubiāo", "english": "to bid, tender"},
    {"hanzi": "协议", "pinyin": "xiéyì", "english": "agreement, pact"},
    {"hanzi": "章程", "pinyin": "zhāngchéng", "english": "bylaws, charter"},
    {"hanzi": "融资", "pinyin": "róngzī", "english": "financing"},
    {"hanzi": "上市", "pinyin": "shàngshì", "english": "to go public (IPO)"},
    {"hanzi": "并购", "pinyin": "bìnggòu", "english": "merger & acquisition"},
    {"hanzi": "资产", "pinyin": "zīchǎn", "english": "asset"},
    {"hanzi": "负债", "pinyin": "fùzhài", "english": "liability, debt"},
    {"hanzi": "审计", "pinyin": "shěnjì", "english": "audit"},
    {"hanzi": "保险", "pinyin": "bǎoxiǎn", "english": "insurance"},
    {"hanzi": "理赔", "pinyin": "lǐpéi", "english": "insurance claim"},
    {"hanzi": "证券", "pinyin": "zhèngquàn", "english": "securities"},
    {"hanzi": "基金", "pinyin": "jījīn", "english": "fund (financial)"},
    {"hanzi": "债券", "pinyin": "zhàiquàn", "english": "bond (financial)"},
    {"hanzi": "期货", "pinyin": "qīhuò", "english": "futures (trading)"},
    {"hanzi": "抵押", "pinyin": "dǐyā", "english": "mortgage, collateral"},
    {"hanzi": "担保", "pinyin": "dānbǎo", "english": "to guarantee"},
    {"hanzi": "基因", "pinyin": "jīyīn", "english": "gene"},
    {"hanzi": "细胞", "pinyin": "xìbāo", "english": "cell (biology)"},
    {"hanzi": "分子", "pinyin": "fēnzǐ", "english": "molecule"},
    {"hanzi": "原子", "pinyin": "yuánzǐ", "english": "atom"},
    {"hanzi": "元素", "pinyin": "yuánsù", "english": "element (chemistry)"},
    {"hanzi": "化合物", "pinyin": "huàhéwù", "english": "chemical compound"},
    {"hanzi": "物质", "pinyin": "wùzhì", "english": "matter, substance"},
    {"hanzi": "引力", "pinyin": "yǐnlì", "english": "gravity"},
    {"hanzi": "磁场", "pinyin": "cíchǎng", "english": "magnetic field"},
    {"hanzi": "辐射", "pinyin": "fúshè", "english": "radiation"},
    {"hanzi": "激光", "pinyin": "jīguāng", "english": "laser"},
    {"hanzi": "纳米", "pinyin": "nàmǐ", "english": "nanometer"},
    {"hanzi": "望远镜", "pinyin": "wàngyuǎnjìng", "english": "telescope"},
    {"hanzi": "显微镜", "pinyin": "xiǎnwēijìng", "english": "microscope"},
    {"hanzi": "探测", "pinyin": "tàncè", "english": "to detect, probe"},
    {"hanzi": "机器人", "pinyin": "jīqìrén", "english": "robot"},
    {"hanzi": "无人机", "pinyin": "wúrénjī", "english": "drone"},
    {"hanzi": "3D打印", "pinyin": "sān D dǎyìn", "english": "3D printing"},
    {"hanzi": "区块链", "pinyin": "qūkuàiliàn", "english": "blockchain"},
    {"hanzi": "大数据", "pinyin": "dàshùjù", "english": "big data"},
    {"hanzi": "湿地", "pinyin": "shīdì", "english": "wetland"},
    {"hanzi": "珊瑚", "pinyin": "shānhú", "english": "coral"},
    {"hanzi": "雾霾", "pinyin": "wùmái", "english": "smog, haze"},
    {"hanzi": "温室", "pinyin": "wēnshì", "english": "greenhouse"},
    {"hanzi": "废气", "pinyin": "fèiqì", "english": "exhaust gas"},
    {"hanzi": "废水", "pinyin": "fèishuǐ", "english": "wastewater"},
    {"hanzi": "噪音", "pinyin": "zàoyīn", "english": "noise pollution"},
    {"hanzi": "中医", "pinyin": "zhōngyī", "english": "Chinese medicine"},
    {"hanzi": "西医", "pinyin": "xīyī", "english": "Western medicine"},
    {"hanzi": "针灸", "pinyin": "zhēnjiǔ", "english": "acupuncture"},
    {"hanzi": "保健", "pinyin": "bǎojiàn", "english": "health care"},
    {"hanzi": "营养", "pinyin": "yíngyǎng", "english": "nutrition"},
    {"hanzi": "维生素", "pinyin": "wéishēngsù", "english": "vitamin"},
    {"hanzi": "蛋白质", "pinyin": "dànbáizhì", "english": "protein"},
    {"hanzi": "议会", "pinyin": "yìhuì", "english": "parliament"},
    {"hanzi": "总统", "pinyin": "zǒngtǒng", "english": "president (country)"},
    {"hanzi": "内阁", "pinyin": "nèigé", "english": "cabinet (govt)"},
    {"hanzi": "省份", "pinyin": "shěngfèn", "english": "province"},
    {"hanzi": "自治区", "pinyin": "zìzhìqū", "english": "autonomous region"},
    {"hanzi": "市政", "pinyin": "shìzhèng", "english": "municipal government"},
    {"hanzi": "财政", "pinyin": "cáizhèng", "english": "public finance"},
    {"hanzi": "预算案", "pinyin": "yùsuànàn", "english": "budget proposal"},
    {"hanzi": "承担", "pinyin": "chéngdān", "english": "to undertake, bear"},
    {"hanzi": "促进", "pinyin": "cùjìn", "english": "to promote, advance"},
    {"hanzi": "创造", "pinyin": "chuàngzào", "english": "to create"},
    {"hanzi": "抵抗", "pinyin": "dǐkàng", "english": "to resist, withstand"},
    {"hanzi": "推广", "pinyin": "tuīguǎng", "english": "to promote, popularize"},
    {"hanzi": "维护", "pinyin": "wéihù", "english": "to maintain, safeguard"},
    {"hanzi": "改善", "pinyin": "gǎishàn", "english": "to improve, ameliorate"},
    {"hanzi": "实施", "pinyin": "shíshī", "english": "to implement, carry out"},
    {"hanzi": "采取", "pinyin": "cǎiqǔ", "english": "to adopt, take measures"},
    {"hanzi": "涉及", "pinyin": "shèjí", "english": "to involve, relate to"},
    {"hanzi": "具备", "pinyin": "jùbèi", "english": "to possess, have"},
    {"hanzi": "构成", "pinyin": "gòuchéng", "english": "to constitute, form"},
    {"hanzi": "呈现", "pinyin": "chéngxiàn", "english": "to present, appear"},
    {"hanzi": "蕴含", "pinyin": "yùnhán", "english": "to contain, embody"},
    {"hanzi": "体现", "pinyin": "tǐxiàn", "english": "to embody, reflect"},
    {"hanzi": "启发", "pinyin": "qǐfā", "english": "to inspire, enlighten"},
    {"hanzi": "依赖", "pinyin": "yīlài", "english": "to depend on, rely on"},
    {"hanzi": "面临", "pinyin": "miànlín", "english": "to face, confront"},
    {"hanzi": "遭受", "pinyin": "zāoshòu", "english": "to suffer, sustain"},
    {"hanzi": "抵达", "pinyin": "dǐdá", "english": "to arrive at, reach"},
    {"hanzi": "展示", "pinyin": "zhǎnshì", "english": "to display, demonstrate"},
    {"hanzi": "揭示", "pinyin": "jiēshì", "english": "to reveal, disclose"},
    {"hanzi": "激发", "pinyin": "jīfā", "english": "to stimulate, inspire"},
    {"hanzi": "贡献", "pinyin": "gòngxiàn", "english": "to contribute; contribution"},
    {"hanzi": "忽视", "pinyin": "hūshì", "english": "to ignore, neglect"},
    {"hanzi": "阻碍", "pinyin": "zǔài", "english": "to hinder, obstruct"},
    {"hanzi": "承认", "pinyin": "chéngrèn", "english": "to admit, acknowledge"},
    {"hanzi": "透露", "pinyin": "tòulù", "english": "to disclose, reveal"},
    {"hanzi": "遵守", "pinyin": "zūnshǒu", "english": "to comply with, abide by"},
    {"hanzi": "驱动", "pinyin": "qūdòng", "english": "to drive, propel"},
    {"hanzi": "催促", "pinyin": "cuīcù", "english": "to urge, press"},
    {"hanzi": "拓展", "pinyin": "tuòzhǎn", "english": "to expand, broaden"},
    {"hanzi": "弥补", "pinyin": "míbǔ", "english": "to make up for, compensate"},
    {"hanzi": "追求", "pinyin": "zhuīqiú", "english": "to pursue, seek"},
    {"hanzi": "捕捉", "pinyin": "bǔzhuō", "english": "to capture, catch"},
    {"hanzi": "融合", "pinyin": "rónghé", "english": "to integrate, fuse"},
    {"hanzi": "携带", "pinyin": "xiédài", "english": "to carry, bring along"},
    {"hanzi": "储存", "pinyin": "chǔcún", "english": "to store, save"},
    {"hanzi": "淘汰", "pinyin": "táotài", "english": "to eliminate, phase out"},
    {"hanzi": "衡量", "pinyin": "héngliáng", "english": "to measure, weigh"},
    {"hanzi": "释放", "pinyin": "shìfàng", "english": "to release, set free"},
    {"hanzi": "承诺", "pinyin": "chéngnuò", "english": "to promise; commitment"},
    {"hanzi": "崩溃", "pinyin": "bēngkuì", "english": "to collapse, break down"},
    {"hanzi": "干预", "pinyin": "gānyù", "english": "to intervene"},
    {"hanzi": "模仿", "pinyin": "mófǎng", "english": "to imitate, mimic"},
    {"hanzi": "束缚", "pinyin": "shùfù", "english": "to restrain, bind"},
    {"hanzi": "颠覆", "pinyin": "diānfù", "english": "to overturn, subvert"},
    {"hanzi": "诱发", "pinyin": "yòufā", "english": "to trigger, induce"},
    {"hanzi": "凝聚", "pinyin": "níngjù", "english": "to condense, cohere"},
    {"hanzi": "渗透", "pinyin": "shèntòu", "english": "to permeate, infiltrate"},
    {"hanzi": "显著", "pinyin": "xiǎnzhù", "english": "notable, remarkable"},
    {"hanzi": "消极", "pinyin": "xiāojí", "english": "negative, passive"},
    {"hanzi": "主观", "pinyin": "zhǔguān", "english": "subjective"},
    {"hanzi": "必要", "pinyin": "bìyào", "english": "necessary, essential"},
    {"hanzi": "充分", "pinyin": "chōngfèn", "english": "sufficient, full"},
    {"hanzi": "适当", "pinyin": "shìdàng", "english": "appropriate, proper"},
    {"hanzi": "有效", "pinyin": "yǒuxiào", "english": "effective, valid"},
    {"hanzi": "特殊", "pinyin": "tèshū", "english": "special, particular"},
    {"hanzi": "相对", "pinyin": "xiāngduì", "english": "relative, comparative"},
    {"hanzi": "频繁", "pinyin": "pínfán", "english": "frequent"},
    {"hanzi": "潜在", "pinyin": "qiánzài", "english": "potential, latent"},
    {"hanzi": "固有", "pinyin": "gùyǒu", "english": "inherent, innate"},
    {"hanzi": "持续", "pinyin": "chíxù", "english": "continuous, sustained"},
    {"hanzi": "稳定", "pinyin": "wěndìng", "english": "stable, steady"},
    {"hanzi": "繁荣", "pinyin": "fánróng", "english": "prosperous, thriving"},
    {"hanzi": "匮乏", "pinyin": "kuìfá", "english": "scarce, deficient"},
    {"hanzi": "庞大", "pinyin": "pángdà", "english": "enormous, huge"},
    {"hanzi": "浓厚", "pinyin": "nónghòu", "english": "dense, strong, rich"},
    {"hanzi": "紧迫", "pinyin": "jǐnpò", "english": "urgent, pressing"},
    {"hanzi": "脆弱", "pinyin": "cuìruò", "english": "fragile, vulnerable"},
    {"hanzi": "宏观", "pinyin": "hóngguān", "english": "macroscopic, macro"},
    {"hanzi": "微观", "pinyin": "wēiguān", "english": "microscopic, micro"},
    {"hanzi": "空前", "pinyin": "kōngqián", "english": "unprecedented"},
    {"hanzi": "漫长", "pinyin": "màncháng", "english": "very long, endless"},
    {"hanzi": "模糊", "pinyin": "móhu", "english": "vague, blurry"},
    {"hanzi": "崭新", "pinyin": "zhǎnxīn", "english": "brand-new"},
    {"hanzi": "罕见", "pinyin": "hǎnjiàn", "english": "rare, seldom seen"},
    {"hanzi": "迫切", "pinyin": "pòqiè", "english": "urgent, pressing"},
    {"hanzi": "辉煌", "pinyin": "huīhuáng", "english": "splendid, glorious"},
    {"hanzi": "匿名", "pinyin": "nìmíng", "english": "anonymous"},
    {"hanzi": "透明", "pinyin": "tòumíng", "english": "transparent"},
    {"hanzi": "均匀", "pinyin": "jūnyún", "english": "even, uniform"},
    {"hanzi": "惊人", "pinyin": "jīngrén", "english": "astonishing, amazing"},
    {"hanzi": "焦虑", "pinyin": "jiāolǜ", "english": "anxious, anxiety"},
    {"hanzi": "沮丧", "pinyin": "jǔsàng", "english": "dejected, depressed"},
    {"hanzi": "恐惧", "pinyin": "kǒngjù", "english": "fear, dread"},
    {"hanzi": "悲观", "pinyin": "bēiguān", "english": "pessimistic"},
    {"hanzi": "自卑", "pinyin": "zìbēi", "english": "inferiority complex"},
    {"hanzi": "情绪", "pinyin": "qíngxù", "english": "emotion, mood"},
    {"hanzi": "思维", "pinyin": "sīwéi", "english": "thinking, thought"},
    {"hanzi": "意识", "pinyin": "yìshí", "english": "consciousness, awareness"},
    {"hanzi": "灵感", "pinyin": "línggǎn", "english": "inspiration"},
    {"hanzi": "动机", "pinyin": "dòngjī", "english": "motive, motivation"},
    {"hanzi": "抑郁", "pinyin": "yìyù", "english": "depressed, depression"},
    {"hanzi": "烦躁", "pinyin": "fánzào", "english": "irritable, agitated"},
    {"hanzi": "愧疚", "pinyin": "kuìjiù", "english": "guilty, remorseful"},
    {"hanzi": "嫉妒", "pinyin": "jídù", "english": "jealous, envious"},
    {"hanzi": "怀旧", "pinyin": "huáijiù", "english": "nostalgic"},
    {"hanzi": "冲动", "pinyin": "chōngdòng", "english": "impulsive, impulse"},
    {"hanzi": "敏锐", "pinyin": "mǐnruì", "english": "keen, acute"},
    {"hanzi": "共鸣", "pinyin": "gòngmíng", "english": "resonance, empathy"},
    {"hanzi": "欣慰", "pinyin": "xīnwèi", "english": "gratified, relieved"},
    {"hanzi": "挫折", "pinyin": "cuòzhé", "english": "setback, frustration"},
    {"hanzi": "疲惫", "pinyin": "píbèi", "english": "exhausted, fatigued"},
    {"hanzi": "振奋", "pinyin": "zhènfèn", "english": "inspired, uplifted"},
    {"hanzi": "内疚", "pinyin": "nèijiù", "english": "guilty, conscience-stricken"},
    {"hanzi": "委屈", "pinyin": "wěiqu", "english": "wronged, aggrieved"},
    {"hanzi": "羡慕", "pinyin": "xiànmù", "english": "to envy, admire"},
    {"hanzi": "依恋", "pinyin": "yīliàn", "english": "attachment, affection"},
    {"hanzi": "郁闷", "pinyin": "yùmèn", "english": "gloomy, depressed"},
    {"hanzi": "惆怅", "pinyin": "chóuchàng", "english": "melancholy, wistful"},
    {"hanzi": "渴望", "pinyin": "kěwàng", "english": "to yearn for, crave"},
    {"hanzi": "执着", "pinyin": "zhízhuó", "english": "persistent, devoted"},
    {"hanzi": "偏见", "pinyin": "piānjiàn", "english": "prejudice, bias"},
    {"hanzi": "认知", "pinyin": "rènzhī", "english": "cognition, perception"},
    {"hanzi": "潜意识", "pinyin": "qiányìshí", "english": "subconscious"},
    {"hanzi": "直觉", "pinyin": "zhíjué", "english": "intuition"},
    {"hanzi": "幻想", "pinyin": "huànxiǎng", "english": "fantasy, illusion"},
    {"hanzi": "习俗", "pinyin": "xísú", "english": "custom, tradition"},
    {"hanzi": "宗教", "pinyin": "zōngjiào", "english": "religion"},
    {"hanzi": "信仰", "pinyin": "xìnyǎng", "english": "faith, belief"},
    {"hanzi": "道德", "pinyin": "dàodé", "english": "morality, ethics"},
    {"hanzi": "价值观", "pinyin": "jiàzhíguān", "english": "values, value system"},
    {"hanzi": "遗产", "pinyin": "yíchǎn", "english": "heritage, legacy"},
    {"hanzi": "阶层", "pinyin": "jiēcéng", "english": "social class, stratum"},
    {"hanzi": "地位", "pinyin": "dìwèi", "english": "status, position"},
    {"hanzi": "舆论", "pinyin": "yúlùn", "english": "public opinion"},
    {"hanzi": "仪式", "pinyin": "yíshì", "english": "ceremony, ritual"},
    {"hanzi": "风俗", "pinyin": "fēngsú", "english": "custom, convention"},
    {"hanzi": "偏远", "pinyin": "piānyuǎn", "english": "remote, outlying"},
    {"hanzi": "贫富", "pinyin": "pínfù", "english": "rich and poor, wealth gap"},
    {"hanzi": "慈善", "pinyin": "císhàn", "english": "charity, philanthropy"},
    {"hanzi": "歧视", "pinyin": "qíshì", "english": "discrimination"},
    {"hanzi": "平衡", "pinyin": "pínghéng", "english": "balance, equilibrium"},
    {"hanzi": "公益", "pinyin": "gōngyì", "english": "public welfare"},
    {"hanzi": "伦理", "pinyin": "lúnlǐ", "english": "ethics, moral principles"},
    {"hanzi": "素养", "pinyin": "sùyǎng", "english": "literacy, competence"},
    {"hanzi": "凝聚力", "pinyin": "níngjùlì", "english": "cohesion, unity"},
    {"hanzi": "归属感", "pinyin": "guīshǔgǎn", "english": "sense of belonging"},
    {"hanzi": "包容", "pinyin": "bāoróng", "english": "tolerant, inclusive"},
    {"hanzi": "多元", "pinyin": "duōyuán", "english": "diverse, pluralistic"},
    {"hanzi": "共识", "pinyin": "gòngshí", "english": "consensus"},
    {"hanzi": "融洽", "pinyin": "róngqià", "english": "harmonious, friendly"},
    {"hanzi": "治安", "pinyin": "zhìān", "english": "public order, security"},
    {"hanzi": "福利", "pinyin": "fúlì", "english": "welfare, benefits"},
    {"hanzi": "弱势", "pinyin": "ruòshì", "english": "vulnerable, disadvantaged"},
    {"hanzi": "群体", "pinyin": "qúntǐ", "english": "group, community"},
    {"hanzi": "草根", "pinyin": "cǎogēn", "english": "grassroots"},
    {"hanzi": "阶级", "pinyin": "jiējí", "english": "social class"},
    {"hanzi": "精英", "pinyin": "jīngyīng", "english": "elite"},
    {"hanzi": "贫困", "pinyin": "pínkùn", "english": "impoverished, poverty"},
    {"hanzi": "城乡", "pinyin": "chéngxiāng", "english": "urban and rural"},
    {"hanzi": "移民", "pinyin": "yímín", "english": "immigrant, migration"},
    {"hanzi": "祭祀", "pinyin": "jìsì", "english": "sacrificial rites, worship"},
    {"hanzi": "传承", "pinyin": "chuánchéng", "english": "to inherit and pass on"},
    {"hanzi": "非遗", "pinyin": "fēiyí", "english": "intangible heritage"},
    {"hanzi": "本质", "pinyin": "běnzhì", "english": "essence, nature"},
    {"hanzi": "概念", "pinyin": "gàiniàn", "english": "concept, notion"},
    {"hanzi": "原则", "pinyin": "yuánzé", "english": "principle"},
    {"hanzi": "理论", "pinyin": "lǐlùn", "english": "theory"},
    {"hanzi": "趋势", "pinyin": "qūshì", "english": "trend, tendency"},
    {"hanzi": "因素", "pinyin": "yīnsù", "english": "factor, element"},
    {"hanzi": "特征", "pinyin": "tèzhēng", "english": "characteristic, feature"},
    {"hanzi": "范围", "pinyin": "fànwéi", "english": "scope, range"},
    {"hanzi": "程度", "pinyin": "chéngdù", "english": "degree, extent"},
    {"hanzi": "比例", "pinyin": "bǐlì", "english": "proportion, ratio"},
    {"hanzi": "规模", "pinyin": "guīmó", "english": "scale, scope"},
    {"hanzi": "前提", "pinyin": "qiántí", "english": "premise, prerequisite"},
    {"hanzi": "层面", "pinyin": "céngmiàn", "english": "level, dimension"},
    {"hanzi": "格局", "pinyin": "géjú", "english": "pattern, structure"},
    {"hanzi": "框架", "pinyin": "kuàngjià", "english": "framework"},
    {"hanzi": "核心", "pinyin": "héxīn", "english": "core, nucleus"},
    {"hanzi": "基准", "pinyin": "jīzhǔn", "english": "benchmark, baseline"},
    {"hanzi": "要素", "pinyin": "yàosù", "english": "essential element"},
    {"hanzi": "脉络", "pinyin": "màiluò", "english": "context, thread"},
    {"hanzi": "逻辑", "pinyin": "luóji", "english": "logic"},
    {"hanzi": "矛盾", "pinyin": "máodùn", "english": "contradiction, conflict"},
    {"hanzi": "根源", "pinyin": "gēnyuán", "english": "root cause, origin"},
    {"hanzi": "途径", "pinyin": "tújìng", "english": "approach, channel"},
    {"hanzi": "底线", "pinyin": "dǐxiàn", "english": "bottom line"},
    {"hanzi": "维度", "pinyin": "wéidù", "english": "dimension"},
    {"hanzi": "变量", "pinyin": "biànliàng", "english": "variable"},
    {"hanzi": "常量", "pinyin": "chángliàng", "english": "constant"},
    {"hanzi": "参数", "pinyin": "cānshù", "english": "parameter"},
    {"hanzi": "指标", "pinyin": "zhǐbiāo", "english": "indicator, index"},
    {"hanzi": "临界", "pinyin": "línjiè", "english": "critical, threshold"},
    {"hanzi": "周期", "pinyin": "zhōuqī", "english": "cycle, period"},
    {"hanzi": "演变", "pinyin": "yǎnbiàn", "english": "evolution, development"},
    {"hanzi": "转型", "pinyin": "zhuǎnxíng", "english": "transformation"},
    {"hanzi": "瓶颈", "pinyin": "píngjǐng", "english": "bottleneck"},
    {"hanzi": "契机", "pinyin": "qìjī", "english": "opportunity, turning point"},
    {"hanzi": "共性", "pinyin": "gòngxìng", "english": "commonality"},
    {"hanzi": "差异", "pinyin": "chāyì", "english": "difference, disparity"},
    {"hanzi": "关联", "pinyin": "guānlián", "english": "correlation, connection"},
    {"hanzi": "内涵", "pinyin": "nèihán", "english": "connotation, meaning"},
    {"hanzi": "外延", "pinyin": "wàiyán", "english": "extension, denotation"},
    {"hanzi": "遏制", "pinyin": "èzhì", "english": "to curb, contain"},
    {"hanzi": "践行", "pinyin": "jiànxíng", "english": "to practice, carry out"},
    {"hanzi": "统筹", "pinyin": "tǒngchóu", "english": "to coordinate overall"},
    {"hanzi": "落实", "pinyin": "luòshí", "english": "to implement, put into effect"},
    {"hanzi": "着力", "pinyin": "zhuólì", "english": "to focus efforts on"},
    {"hanzi": "赋予", "pinyin": "fùyǔ", "english": "to endow, grant"},
    {"hanzi": "涵盖", "pinyin": "hángài", "english": "to cover, encompass"},
    {"hanzi": "扭转", "pinyin": "niǔzhuǎn", "english": "to reverse, turn around"},
    {"hanzi": "攻克", "pinyin": "gōngkè", "english": "to overcome, conquer"},
    {"hanzi": "孕育", "pinyin": "yùnyù", "english": "to nurture, breed"},
    {"hanzi": "衍生", "pinyin": "yǎnshēng", "english": "to derive, spawn"},
    {"hanzi": "筛选", "pinyin": "shāixuǎn", "english": "to screen, filter"},
    {"hanzi": "整合", "pinyin": "zhěnghé", "english": "to integrate, consolidate"},
    {"hanzi": "规避", "pinyin": "guībì", "english": "to avoid, circumvent"},
    {"hanzi": "攀升", "pinyin": "pānshēng", "english": "to climb, rise"},
    {"hanzi": "突破", "pinyin": "tūpò", "english": "to break through"},
    {"hanzi": "转化", "pinyin": "zhuǎnhuà", "english": "to transform, convert"},
    {"hanzi": "推动", "pinyin": "tuīdòng", "english": "to promote, push forward"},
    {"hanzi": "彰显", "pinyin": "zhāngxiǎn", "english": "to manifest, highlight"},
    {"hanzi": "深远", "pinyin": "shēnyuǎn", "english": "far-reaching, profound"},
    {"hanzi": "根本", "pinyin": "gēnběn", "english": "fundamental, basic"},
    {"hanzi": "严峻", "pinyin": "yánjùn", "english": "severe, grim"},
    {"hanzi": "艰巨", "pinyin": "jiānjù", "english": "arduous, formidable"},
    {"hanzi": "丰硕", "pinyin": "fēngshuò", "english": "fruitful, abundant"},
    {"hanzi": "匮缺", "pinyin": "kuìquē", "english": "scarce, lacking"},
    {"hanzi": "卓越", "pinyin": "zhuóyuè", "english": "outstanding, excellent"},
    {"hanzi": "长远", "pinyin": "chángyuǎn", "english": "long-term, far-sighted"},
    {"hanzi": "广阔", "pinyin": "guǎngkuò", "english": "vast, broad"},
    {"hanzi": "复合", "pinyin": "fùhé", "english": "composite, compound"},
    {"hanzi": "多样", "pinyin": "duōyàng", "english": "diverse, varied"},
    {"hanzi": "双赢", "pinyin": "shuāngyíng", "english": "win-win"},
    {"hanzi": "可控", "pinyin": "kěkòng", "english": "controllable"},
    {"hanzi": "可行", "pinyin": "kěxíng", "english": "feasible, viable"},
    {"hanzi": "常态", "pinyin": "chángtài", "english": "normal state, norm"},
    {"hanzi": "意愿", "pinyin": "yìyuàn", "english": "wish, willingness"},
    {"hanzi": "诉求", "pinyin": "sùqiú", "english": "appeal, demand"},
    {"hanzi": "呼声", "pinyin": "hūshēng", "english": "public outcry, voice"},
    {"hanzi": "民意", "pinyin": "mínyì", "english": "public opinion, will"},
    {"hanzi": "导向", "pinyin": "dǎoxiàng", "english": "orientation, guidance"},
    {"hanzi": "氛围", "pinyin": "fēnwéi", "english": "atmosphere, ambiance"},
    {"hanzi": "格调", "pinyin": "gédiào", "english": "style, tone"},
    {"hanzi": "底蕴", "pinyin": "dǐyùn", "english": "cultural depth"},
    {"hanzi": "传播", "pinyin": "chuánbō", "english": "to spread, disseminate"},
    {"hanzi": "渠道", "pinyin": "qúdào", "english": "channel, conduit"},
    {"hanzi": "媒介", "pinyin": "méijiè", "english": "medium, media"},
    {"hanzi": "载体", "pinyin": "zàitǐ", "english": "carrier, vehicle"},
    {"hanzi": "纽带", "pinyin": "niǔdài", "english": "link, bond"},
    {"hanzi": "桥梁", "pinyin": "qiáoliáng", "english": "bridge"},
    {"hanzi": "平台", "pinyin": "píngtái", "english": "platform"},
    {"hanzi": "机制", "pinyin": "jīzhì", "english": "mechanism, system"},
    {"hanzi": "体制", "pinyin": "tǐzhì", "english": "system, institution"},
    {"hanzi": "举措", "pinyin": "jǔcuò", "english": "measure, initiative"},
    {"hanzi": "方针", "pinyin": "fāngzhēn", "english": "policy, guideline"},
    {"hanzi": "纲领", "pinyin": "gānglǐng", "english": "program, platform"},
    {"hanzi": "布局", "pinyin": "bùjú", "english": "layout, arrangement"},
    {"hanzi": "部署", "pinyin": "bùshǔ", "english": "to deploy, arrange"},
    {"hanzi": "规划", "pinyin": "guīhuà", "english": "to plan; plan"},
    {"hanzi": "蓝图", "pinyin": "lántú", "english": "blueprint"},
    {"hanzi": "愿景", "pinyin": "yuànjǐng", "english": "vision"},
    {"hanzi": "使命", "pinyin": "shǐmìng", "english": "mission"},
    {"hanzi": "目光", "pinyin": "mùguāng", "english": "gaze, vision"},
    {"hanzi": "视野", "pinyin": "shìyě", "english": "field of vision, horizon"},
    {"hanzi": "眼界", "pinyin": "yǎnjiè", "english": "breadth of view"},
    {"hanzi": "胸怀", "pinyin": "xiōnghuái", "english": "mind, breadth of mind"},
    {"hanzi": "时代", "pinyin": "shídài", "english": "era; age; epoch"},
    {"hanzi": "时期", "pinyin": "shíqī", "english": "period; phase"},
    {"hanzi": "期间", "pinyin": "qījiān", "english": "during; period"},
    {"hanzi": "日益", "pinyin": "rìyì", "english": "increasingly; day by day"},
    {"hanzi": "逐渐", "pinyin": "zhújiàn", "english": "gradually"},
    {"hanzi": "不断", "pinyin": "búduàn", "english": "unceasingly; continuously"},
    {"hanzi": "始终", "pinyin": "shǐzhōng", "english": "from beginning to end; always"},
    {"hanzi": "陆续", "pinyin": "lùxù", "english": "one after another; successively"},
    {"hanzi": "顿时", "pinyin": "dùnshí", "english": "immediately; at once"},
    {"hanzi": "随时", "pinyin": "suíshí", "english": "at any time"},
    {"hanzi": "及早", "pinyin": "jízǎo", "english": "as early as possible"},
    {"hanzi": "迟早", "pinyin": "chízǎo", "english": "sooner or later"},
    {"hanzi": "当初", "pinyin": "dāngchū", "english": "originally; at that time"},
    {"hanzi": "如今", "pinyin": "rújīn", "english": "nowadays"},
    {"hanzi": "从此", "pinyin": "cóngcǐ", "english": "from now on; henceforth"},
    {"hanzi": "当代", "pinyin": "dāngdài", "english": "contemporary; modern era"},
    {"hanzi": "世纪", "pinyin": "shìjì", "english": "century"},
    {"hanzi": "时刻", "pinyin": "shíkè", "english": "moment; constantly"},
    {"hanzi": "时光", "pinyin": "shíguāng", "english": "time; years"},
    {"hanzi": "岁月", "pinyin": "suìyuè", "english": "years; passage of time"},
    {"hanzi": "媒体", "pinyin": "méitǐ", "english": "media"},
    {"hanzi": "出版", "pinyin": "chūbǎn", "english": "to publish"},
    {"hanzi": "记者", "pinyin": "jìzhě", "english": "journalist; reporter"},
    {"hanzi": "评论", "pinyin": "pínglùn", "english": "to comment; commentary"},
    {"hanzi": "宣传", "pinyin": "xuānchuán", "english": "to publicize; propaganda"},
    {"hanzi": "播出", "pinyin": "bōchū", "english": "to broadcast"},
    {"hanzi": "转播", "pinyin": "zhuǎnbō", "english": "to relay a broadcast"},
    {"hanzi": "节目", "pinyin": "jiémù", "english": "program; show"},
    {"hanzi": "直播", "pinyin": "zhíbō", "english": "live broadcast"},
    {"hanzi": "报刊", "pinyin": "bàokān", "english": "newspapers and periodicals"},
    {"hanzi": "刊物", "pinyin": "kānwù", "english": "publication; periodical"},
    {"hanzi": "专栏", "pinyin": "zhuānlán", "english": "column (in a publication)"},
    {"hanzi": "稿件", "pinyin": "gǎojiàn", "english": "manuscript; draft"},
    {"hanzi": "摄影", "pinyin": "shèyǐng", "english": "photography"},
    {"hanzi": "录像", "pinyin": "lùxiàng", "english": "to videotape; video recording"},
    {"hanzi": "屏幕", "pinyin": "píngmù", "english": "screen; display"},
    {"hanzi": "话题", "pinyin": "huàtí", "english": "topic of conversation"},
    {"hanzi": "标题", "pinyin": "biāotí", "english": "title; headline"},
    {"hanzi": "网民", "pinyin": "wǎngmín", "english": "netizen; internet user"},
    {"hanzi": "信号", "pinyin": "xìnhào", "english": "signal"},
    {"hanzi": "航线", "pinyin": "hángxiàn", "english": "air route; shipping route"},
    {"hanzi": "车厢", "pinyin": "chēxiāng", "english": "train carriage; compartment"},
    {"hanzi": "乘客", "pinyin": "chéngkè", "english": "passenger"},
    {"hanzi": "旅途", "pinyin": "lǚtú", "english": "journey; trip"},
    {"hanzi": "目的地", "pinyin": "mùdìdì", "english": "destination"},
    {"hanzi": "景点", "pinyin": "jǐngdiǎn", "english": "scenic spot; attraction"},
    {"hanzi": "路线", "pinyin": "lùxiàn", "english": "route; itinerary"},
    {"hanzi": "候车", "pinyin": "hòuchē", "english": "to wait for a bus/train"},
    {"hanzi": "站台", "pinyin": "zhàntái", "english": "platform (train station)"},
    {"hanzi": "码头", "pinyin": "mǎtou", "english": "dock; wharf"},
    {"hanzi": "跑道", "pinyin": "pǎodào", "english": "runway; track"},
    {"hanzi": "高速", "pinyin": "gāosù", "english": "high-speed"},
    {"hanzi": "堵车", "pinyin": "dǔchē", "english": "traffic jam"},
    {"hanzi": "闯红灯", "pinyin": "chuǎng hóngdēng", "english": "to run a red light"},
    {"hanzi": "超速", "pinyin": "chāosù", "english": "to exceed the speed limit"},
    {"hanzi": "燃油", "pinyin": "rányóu", "english": "fuel oil"},
    {"hanzi": "通行", "pinyin": "tōngxíng", "english": "to pass through; passable"},
    {"hanzi": "导航", "pinyin": "dǎoháng", "english": "navigation; GPS"},
    {"hanzi": "旅客", "pinyin": "lǚkè", "english": "traveler; passenger"},
    {"hanzi": "名胜", "pinyin": "míngshèng", "english": "famous scenic spot"},
    {"hanzi": "食材", "pinyin": "shícái", "english": "food ingredient"},
    {"hanzi": "原料", "pinyin": "yuánliào", "english": "raw material"},
    {"hanzi": "烹饪", "pinyin": "pēngrèn", "english": "to cook; cooking"},
    {"hanzi": "调料", "pinyin": "tiáoliào", "english": "seasoning; condiment"},
    {"hanzi": "厨房", "pinyin": "chúfáng", "english": "kitchen"},
    {"hanzi": "菜单", "pinyin": "càidān", "english": "menu"},
    {"hanzi": "厨师", "pinyin": "chúshī", "english": "chef; cook"},
    {"hanzi": "炒菜", "pinyin": "chǎocài", "english": "to stir-fry; cooked dish"},
    {"hanzi": "煮", "pinyin": "zhǔ", "english": "to boil; to cook"},
    {"hanzi": "蒸", "pinyin": "zhēng", "english": "to steam"},
    {"hanzi": "烤", "pinyin": "kǎo", "english": "to roast; to bake"},
    {"hanzi": "炸", "pinyin": "zhá", "english": "to deep-fry"},
    {"hanzi": "切", "pinyin": "qiē", "english": "to cut; to slice"},
    {"hanzi": "拌", "pinyin": "bàn", "english": "to mix; to toss (salad)"},
    {"hanzi": "酱油", "pinyin": "jiàngyóu", "english": "soy sauce"},
    {"hanzi": "味精", "pinyin": "wèijīng", "english": "MSG; monosodium glutamate"},
    {"hanzi": "香料", "pinyin": "xiāngliào", "english": "spice"},
    {"hanzi": "食谱", "pinyin": "shípǔ", "english": "recipe; cookbook"},
    {"hanzi": "素食", "pinyin": "sùshí", "english": "vegetarian food"},
    {"hanzi": "开胃", "pinyin": "kāiwèi", "english": "appetizing"},
    {"hanzi": "服装", "pinyin": "fúzhuāng", "english": "clothing; garment"},
    {"hanzi": "面料", "pinyin": "miànliào", "english": "fabric; material"},
    {"hanzi": "时尚", "pinyin": "shíshàng", "english": "fashion; trendy"},
    {"hanzi": "款式", "pinyin": "kuǎnshì", "english": "style; design"},
    {"hanzi": "搭配", "pinyin": "dāpèi", "english": "to match; to coordinate"},
    {"hanzi": "化妆", "pinyin": "huàzhuāng", "english": "to put on makeup"},
    {"hanzi": "发型", "pinyin": "fàxíng", "english": "hairstyle"},
    {"hanzi": "首饰", "pinyin": "shǒushì", "english": "jewelry; accessories"},
    {"hanzi": "试衣间", "pinyin": "shìyījiān", "english": "fitting room"},
    {"hanzi": "布料", "pinyin": "bùliào", "english": "cloth; fabric"},
    {"hanzi": "纽扣", "pinyin": "niǔkòu", "english": "button (on clothing)"},
    {"hanzi": "领带", "pinyin": "lǐngdài", "english": "necktie"},
    {"hanzi": "围巾", "pinyin": "wéijīn", "english": "scarf"},
    {"hanzi": "手套", "pinyin": "shǒutào", "english": "gloves"},
    {"hanzi": "拉链", "pinyin": "lāliàn", "english": "zipper"},
    {"hanzi": "尺寸", "pinyin": "chǐcùn", "english": "size; dimensions"},
    {"hanzi": "剪裁", "pinyin": "jiǎncái", "english": "to tailor; to cut (fabric)"},
    {"hanzi": "熨烫", "pinyin": "yùntàng", "english": "to iron (clothes)"},
    {"hanzi": "干洗", "pinyin": "gānxǐ", "english": "dry cleaning"},
    {"hanzi": "潮流", "pinyin": "cháoliú", "english": "trend; fashion"},
    {"hanzi": "建筑", "pinyin": "jiànzhù", "english": "building; architecture"},
    {"hanzi": "装修", "pinyin": "zhuāngxiū", "english": "to renovate; decoration"},
    {"hanzi": "阳台", "pinyin": "yángtái", "english": "balcony"},
    {"hanzi": "楼梯", "pinyin": "lóutī", "english": "stairs; staircase"},
    {"hanzi": "物业", "pinyin": "wùyè", "english": "property management"},
    {"hanzi": "走廊", "pinyin": "zǒuláng", "english": "corridor; hallway"},
    {"hanzi": "地板", "pinyin": "dìbǎn", "english": "floor; floorboard"},
    {"hanzi": "天花板", "pinyin": "tiānhuābǎn", "english": "ceiling"},
    {"hanzi": "门锁", "pinyin": "ménsuǒ", "english": "door lock"},
    {"hanzi": "屋顶", "pinyin": "wūdǐng", "english": "roof; rooftop"},
    {"hanzi": "车库", "pinyin": "chēkù", "english": "garage"},
    {"hanzi": "院落", "pinyin": "yuànluò", "english": "courtyard"},
    {"hanzi": "砖", "pinyin": "zhuān", "english": "brick"},
    {"hanzi": "水泥", "pinyin": "shuǐní", "english": "cement"},
    {"hanzi": "施工", "pinyin": "shīgōng", "english": "to construct; construction"},
    {"hanzi": "地基", "pinyin": "dìjī", "english": "foundation (of a building)"},
    {"hanzi": "钢筋", "pinyin": "gāngjīn", "english": "steel bar; rebar"},
    {"hanzi": "隔音", "pinyin": "géyīn", "english": "soundproofing"},
    {"hanzi": "采光", "pinyin": "cǎiguāng", "english": "natural lighting; daylighting"},
    {"hanzi": "户型", "pinyin": "hùxíng", "english": "apartment layout; floor plan"},
    {"hanzi": "何况", "pinyin": "hékuàng", "english": "let alone; moreover"},
    {"hanzi": "况且", "pinyin": "kuàngqiě", "english": "besides; moreover"},
    {"hanzi": "否则", "pinyin": "fǒuzé", "english": "otherwise"},
    {"hanzi": "从而", "pinyin": "cóngér", "english": "thereby; thus"},
    {"hanzi": "由此", "pinyin": "yóucǐ", "english": "from this; hereby"},
    {"hanzi": "进而", "pinyin": "jìnér", "english": "furthermore; and then"},
    {"hanzi": "总之", "pinyin": "zǒngzhī", "english": "in short; in a word"},
    {"hanzi": "毕竟", "pinyin": "bìjìng", "english": "after all"},
    {"hanzi": "居然", "pinyin": "jūrán", "english": "unexpectedly; to one's surprise"},
    {"hanzi": "难免", "pinyin": "nánmiǎn", "english": "hard to avoid; inevitable"},
    {"hanzi": "未必", "pinyin": "wèibì", "english": "not necessarily"},
    {"hanzi": "不免", "pinyin": "bùmiǎn", "english": "inevitably; unavoidably"},
    {"hanzi": "宁可", "pinyin": "nìngkě", "english": "would rather"},
    {"hanzi": "即使", "pinyin": "jíshǐ", "english": "even if; even though"},
    {"hanzi": "假如", "pinyin": "jiǎrú", "english": "if; supposing"},
    {"hanzi": "一旦", "pinyin": "yīdàn", "english": "once; in case"},
    {"hanzi": "万一", "pinyin": "wànyī", "english": "just in case; if by chance"},
    {"hanzi": "并非", "pinyin": "bìngfēi", "english": "really is not; by no means"},
    {"hanzi": "以免", "pinyin": "yǐmiǎn", "english": "in order to avoid; lest"},
    {"hanzi": "以便", "pinyin": "yǐbiàn", "english": "so that; in order to"},
    {"hanzi": "于是乎", "pinyin": "yúshìhū", "english": "and so; thereupon"},
    {"hanzi": "不妨", "pinyin": "bùfáng", "english": "might as well"},
    {"hanzi": "果真", "pinyin": "guǒzhēn", "english": "really; as expected"},
    {"hanzi": "索性", "pinyin": "suǒxìng", "english": "might as well; simply"},
    {"hanzi": "好歹", "pinyin": "hǎodǎi", "english": "anyway; no matter what"},
    {"hanzi": "何必", "pinyin": "hébì", "english": "why must; there's no need"},
    {"hanzi": "至于", "pinyin": "zhìyú", "english": "as for; as to"},
    {"hanzi": "对于", "pinyin": "duìyú", "english": "regarding; with regard to"},
    {"hanzi": "关于", "pinyin": "guānyú", "english": "about; concerning"},
    {"hanzi": "既然", "pinyin": "jìrán", "english": "since; now that"},
    {"hanzi": "反正", "pinyin": "fǎnzhèng", "english": "anyway; in any case"},
    {"hanzi": "迟迟", "pinyin": "chíchí", "english": "late; delayed"},
    {"hanzi": "无非", "pinyin": "wúfēi", "english": "nothing but; only"},
    {"hanzi": "恰好", "pinyin": "qiàhǎo", "english": "just right; by chance"},
    {"hanzi": "恰恰", "pinyin": "qiàqià", "english": "exactly; precisely"},
    {"hanzi": "简直", "pinyin": "jiǎnzhí", "english": "simply; virtually"},
    {"hanzi": "固然", "pinyin": "gùrán", "english": "admittedly; of course"},
    {"hanzi": "暴风雨", "pinyin": "bàofēngyǔ", "english": "rainstorm; tempest"},
    {"hanzi": "雷", "pinyin": "léi", "english": "thunder"},
    {"hanzi": "闪电", "pinyin": "shǎndiàn", "english": "lightning"},
    {"hanzi": "彩虹", "pinyin": "cǎihóng", "english": "rainbow"},
    {"hanzi": "霜", "pinyin": "shuāng", "english": "frost"},
    {"hanzi": "露水", "pinyin": "lùshuǐ", "english": "dew"},
    {"hanzi": "季节", "pinyin": "jìjié", "english": "season"},
    {"hanzi": "气温", "pinyin": "qìwēn", "english": "air temperature"},
    {"hanzi": "降水", "pinyin": "jiàngshuǐ", "english": "precipitation; rainfall"},
    {"hanzi": "干旱期", "pinyin": "gānhànqī", "english": "drought period"},
    {"hanzi": "免疫力", "pinyin": "miǎnyìlì", "english": "immunity"},
    {"hanzi": "体温", "pinyin": "tǐwēn", "english": "body temperature"},
    {"hanzi": "脉搏", "pinyin": "màibó", "english": "pulse"},
    {"hanzi": "呼吸道", "pinyin": "hūxīdào", "english": "respiratory tract"},
    {"hanzi": "消化", "pinyin": "xiāohuà", "english": "to digest; digestion"},
    {"hanzi": "过敏原", "pinyin": "guòmǐnyuán", "english": "allergen"},
    {"hanzi": "头痛", "pinyin": "tóutòng", "english": "headache"},
    {"hanzi": "发烧", "pinyin": "fāshāo", "english": "to have a fever"},
    {"hanzi": "咳嗽", "pinyin": "késou", "english": "to cough"},
    {"hanzi": "伤口", "pinyin": "shāngkǒu", "english": "wound; cut"},
    {"hanzi": "药方", "pinyin": "yàofāng", "english": "prescription"},
    {"hanzi": "手指", "pinyin": "shǒuzhǐ", "english": "finger"},
    {"hanzi": "肩膀", "pinyin": "jiānbǎng", "english": "shoulder"},
    {"hanzi": "膝盖", "pinyin": "xīgài", "english": "knee"},
    {"hanzi": "喜悦", "pinyin": "xǐyuè", "english": "joy; delight"},
    {"hanzi": "悲伤", "pinyin": "bēishāng", "english": "sadness; grief"},
    {"hanzi": "愤怒", "pinyin": "fènnù", "english": "anger; fury"},
    {"hanzi": "忧愁", "pinyin": "yōuchóu", "english": "anxiety; worry"},
    {"hanzi": "羞耻", "pinyin": "xiūchǐ", "english": "shame; disgrace"},
    {"hanzi": "同感", "pinyin": "tónggǎn", "english": "empathy; same feeling"},
    {"hanzi": "自豪", "pinyin": "zìháo", "english": "proud; pride"},
    {"hanzi": "感慨", "pinyin": "gǎnkǎi", "english": "to sigh with emotion"},
    {"hanzi": "振作", "pinyin": "zhènzuò", "english": "to pull oneself together"},
    {"hanzi": "沉默", "pinyin": "chénmò", "english": "silence; silent"},
    {"hanzi": "论证", "pinyin": "lùnzhèng", "english": "to prove; argumentation"},
    {"hanzi": "假说", "pinyin": "jiǎshuō", "english": "hypothesis"},
    {"hanzi": "公式", "pinyin": "gōngshì", "english": "formula"},
    {"hanzi": "定理", "pinyin": "dìnglǐ", "english": "theorem"},
    {"hanzi": "推理", "pinyin": "tuīlǐ", "english": "reasoning; inference"},
    {"hanzi": "实证", "pinyin": "shízhèng", "english": "empirical evidence"},
    {"hanzi": "论点", "pinyin": "lùndiǎn", "english": "argument; thesis"},
    {"hanzi": "参考", "pinyin": "cānkǎo", "english": "reference; to consult"},
    {"hanzi": "摘要", "pinyin": "zhāiyào", "english": "abstract; summary"},
    {"hanzi": "综述", "pinyin": "zōngshù", "english": "review; overview"},
    {"hanzi": "利率", "pinyin": "lìlǜ", "english": "interest rate"},
    {"hanzi": "通货膨胀", "pinyin": "tōnghuò péngzhàng", "english": "inflation"},
    {"hanzi": "萧条", "pinyin": "xiāotiáo", "english": "economic depression"},
    {"hanzi": "繁华", "pinyin": "fánhuá", "english": "prosperous; bustling"},
    {"hanzi": "预期", "pinyin": "yùqī", "english": "to expect; expectation"},
    {"hanzi": "核算", "pinyin": "hésuàn", "english": "accounting; to calculate"},
    {"hanzi": "出纳", "pinyin": "chūnà", "english": "cashier; treasurer"},
    {"hanzi": "审核", "pinyin": "shěnhé", "english": "to audit; to review"},
    {"hanzi": "合算", "pinyin": "hésuàn", "english": "worthwhile; cost-effective"},
    {"hanzi": "配额", "pinyin": "pèié", "english": "quota; allocation"},
    {"hanzi": "礼仪", "pinyin": "lǐyí", "english": "etiquette; protocol"},
    {"hanzi": "风俗习惯", "pinyin": "fēngsú xíguàn", "english": "customs and habits"},
    {"hanzi": "仪表", "pinyin": "yíbiǎo", "english": "appearance; bearing"},
    {"hanzi": "婚礼", "pinyin": "hūnlǐ", "english": "wedding ceremony"},
    {"hanzi": "葬礼", "pinyin": "zànglǐ", "english": "funeral"},
    {"hanzi": "宴会", "pinyin": "yànhuì", "english": "banquet; feast"},
    {"hanzi": "聚会", "pinyin": "jùhuì", "english": "gathering; party"},
    {"hanzi": "庆祝", "pinyin": "qìngzhù", "english": "to celebrate"},
    {"hanzi": "纪念", "pinyin": "jìniàn", "english": "to commemorate; memorial"},
    {"hanzi": "传统节日", "pinyin": "chuántǒng jiérì", "english": "traditional festival"},
    {"hanzi": "体育场", "pinyin": "tǐyùchǎng", "english": "stadium"},
    {"hanzi": "裁判", "pinyin": "cáipàn", "english": "referee; judge"},
    {"hanzi": "冠军", "pinyin": "guànjūn", "english": "champion"},
    {"hanzi": "教练", "pinyin": "jiàoliàn", "english": "coach; trainer"},
    {"hanzi": "热身", "pinyin": "rèshēn", "english": "to warm up"},
    {"hanzi": "拉伸", "pinyin": "lāshēn", "english": "to stretch"},
    {"hanzi": "有氧", "pinyin": "yǒuyǎng", "english": "aerobic"},
    {"hanzi": "举重", "pinyin": "jǔzhòng", "english": "weightlifting"},
    {"hanzi": "田径", "pinyin": "tiánjìng", "english": "track and field"},
    {"hanzi": "决赛", "pinyin": "juésài", "english": "final (competition)"},
    {"hanzi": "音乐会", "pinyin": "yīnyuèhuì", "english": "concert"},
    {"hanzi": "歌剧", "pinyin": "gējù", "english": "opera"},
    {"hanzi": "舞台", "pinyin": "wǔtái", "english": "stage"},
    {"hanzi": "乐器", "pinyin": "yuèqì", "english": "musical instrument"},
    {"hanzi": "旋律", "pinyin": "xuánlǜ", "english": "melody"},
    {"hanzi": "节奏", "pinyin": "jiézòu", "english": "rhythm; beat"},
    {"hanzi": "雕塑", "pinyin": "diāosù", "english": "sculpture"},
    {"hanzi": "书法", "pinyin": "shūfǎ", "english": "calligraphy"},
    {"hanzi": "绘画", "pinyin": "huìhuà", "english": "painting; drawing"},
    {"hanzi": "陶瓷", "pinyin": "táocí", "english": "ceramics; pottery"},
    {"hanzi": "法庭", "pinyin": "fǎtíng", "english": "court; courtroom"},
    {"hanzi": "被告", "pinyin": "bèigào", "english": "defendant"},
    {"hanzi": "原告", "pinyin": "yuángào", "english": "plaintiff"},
    {"hanzi": "证人", "pinyin": "zhèngrén", "english": "witness"},
    {"hanzi": "罪行", "pinyin": "zuìxíng", "english": "crime; offense"},
    {"hanzi": "无罪", "pinyin": "wúzuì", "english": "not guilty; innocent"},
    {"hanzi": "上诉", "pinyin": "shàngsù", "english": "to appeal (legal)"},
    {"hanzi": "拘留所", "pinyin": "jūliúsuǒ", "english": "detention center"},
    {"hanzi": "选民", "pinyin": "xuǎnmín", "english": "voter; electorate"},
    {"hanzi": "政党", "pinyin": "zhèngdǎng", "english": "political party"},
    {"hanzi": "借鉴", "pinyin": "jièjiàn", "english": "to use as reference; to learn from"},
    {"hanzi": "开拓", "pinyin": "kāituò", "english": "to open up; to pioneer"},
    {"hanzi": "奠基", "pinyin": "diànjī", "english": "to lay a foundation"},
    {"hanzi": "塑造", "pinyin": "sùzào", "english": "to shape; to mold"},
    {"hanzi": "凸显", "pinyin": "tūxiǎn", "english": "to highlight; to stand out"},
    {"hanzi": "淡化", "pinyin": "dànhuà", "english": "to dilute; to downplay"},
    {"hanzi": "兼顾", "pinyin": "jiāngù", "english": "to give consideration to both"},
    {"hanzi": "统一", "pinyin": "tǒngyī", "english": "to unify; unified"},
    {"hanzi": "倡导", "pinyin": "chàngdǎo", "english": "to advocate; to champion"},
    {"hanzi": "体育", "pinyin": "tǐyù", "english": "sports"},
    {"hanzi": "体操", "pinyin": "tǐcāo", "english": "gymnastics"},
    {"hanzi": "拳击", "pinyin": "quánjī", "english": "boxing"},
    {"hanzi": "跳水", "pinyin": "tiàoshuǐ", "english": "diving"},
    {"hanzi": "马拉松", "pinyin": "mǎlāsōng", "english": "marathon"},
    {"hanzi": "赛季", "pinyin": "sàijì", "english": "sports season"},
    {"hanzi": "武术", "pinyin": "wǔshù", "english": "martial arts"},
    {"hanzi": "足球", "pinyin": "zúqiú", "english": "soccer"},
    {"hanzi": "篮球", "pinyin": "lánqiú", "english": "basketball"},
    {"hanzi": "棒球", "pinyin": "bàngqiú", "english": "baseball"},
    {"hanzi": "羽毛球", "pinyin": "yǔmáoqiú", "english": "badminton"},
    {"hanzi": "高尔夫", "pinyin": "gāoěrfū", "english": "golf"},
    {"hanzi": "滑雪", "pinyin": "huáxuě", "english": "skiing"},
    {"hanzi": "冲浪", "pinyin": "chōnglàng", "english": "surfing"},
    {"hanzi": "击剑", "pinyin": "jījiàn", "english": "fencing"},
    {"hanzi": "摔跤", "pinyin": "shuāijiāo", "english": "wrestling"},
    {"hanzi": "射箭", "pinyin": "shèjiàn", "english": "archery"},
    {"hanzi": "射击", "pinyin": "shèjī", "english": "shooting"},
    {"hanzi": "跆拳道", "pinyin": "táiquándào", "english": "taekwondo"},
    {"hanzi": "奥运会", "pinyin": "àoyùnhuì", "english": "Olympics"},
    {"hanzi": "健身", "pinyin": "jiànshēn", "english": "fitness"},
    {"hanzi": "球迷", "pinyin": "qiúmí", "english": "sports fan"},
    {"hanzi": "奖牌", "pinyin": "jiǎngpái", "english": "medal"},
    {"hanzi": "比分", "pinyin": "bǐfēn", "english": "score"},
    {"hanzi": "队伍", "pinyin": "duìwǔ", "english": "team"},
    {"hanzi": "联赛", "pinyin": "liánsài", "english": "league"},
    {"hanzi": "体力", "pinyin": "tǐlì", "english": "physical strength"},
    {"hanzi": "竞技", "pinyin": "jìngjì", "english": "athletics"},
    {"hanzi": "体能", "pinyin": "tǐnéng", "english": "physical fitness"},
    {"hanzi": "耐力", "pinyin": "nàilì", "english": "endurance"},
    {"hanzi": "跨栏", "pinyin": "kuàlán", "english": "hurdles"},
    {"hanzi": "铅球", "pinyin": "qiānqiú", "english": "shot put"},
    {"hanzi": "跳远", "pinyin": "tiàoyuǎn", "english": "long jump"},
    {"hanzi": "赛车", "pinyin": "sàichē", "english": "racing"},
    {"hanzi": "锦标赛", "pinyin": "jǐnbiāosài", "english": "championship"},
    {"hanzi": "拔河", "pinyin": "báhé", "english": "tug of war"},
    {"hanzi": "艺术", "pinyin": "yìshù", "english": "art"},
    {"hanzi": "画廊", "pinyin": "huàláng", "english": "gallery"},
    {"hanzi": "导演", "pinyin": "dǎoyǎn", "english": "director"},
    {"hanzi": "编剧", "pinyin": "biānjù", "english": "screenwriter"},
    {"hanzi": "小说", "pinyin": "xiǎoshuō", "english": "novel"},
    {"hanzi": "诗歌", "pinyin": "shīgē", "english": "poetry"},
    {"hanzi": "散文", "pinyin": "sǎnwén", "english": "prose"},
    {"hanzi": "舞蹈", "pinyin": "wǔdǎo", "english": "dance"},
    {"hanzi": "交响乐", "pinyin": "jiāoxiǎngyuè", "english": "symphony"},
    {"hanzi": "指挥", "pinyin": "zhǐhuī", "english": "conduct"},
    {"hanzi": "话剧", "pinyin": "huàjù", "english": "stage play"},
    {"hanzi": "喜剧", "pinyin": "xǐjù", "english": "comedy"},
    {"hanzi": "悲剧", "pinyin": "bēijù", "english": "tragedy"},
    {"hanzi": "纪录片", "pinyin": "jìlùpiàn", "english": "documentary"},
    {"hanzi": "动漫", "pinyin": "dòngmàn", "english": "anime"},
    {"hanzi": "票房", "pinyin": "piàofáng", "english": "box office"},
    {"hanzi": "乐队", "pinyin": "yuèduì", "english": "band"},
    {"hanzi": "歌手", "pinyin": "gēshǒu", "english": "singer"},
    {"hanzi": "明星", "pinyin": "míngxīng", "english": "celebrity"},
    {"hanzi": "素描", "pinyin": "sùmiáo", "english": "sketch"},
    {"hanzi": "油画", "pinyin": "yóuhuà", "english": "oil painting"},
    {"hanzi": "水彩", "pinyin": "shuǐcǎi", "english": "watercolor"},
    {"hanzi": "雕刻", "pinyin": "diāokè", "english": "carving"},
    {"hanzi": "相声", "pinyin": "xiàngsheng", "english": "crosstalk"},
    {"hanzi": "杂技", "pinyin": "zájì", "english": "acrobatics"},
    {"hanzi": "魔术", "pinyin": "móshù", "english": "magic"},
    {"hanzi": "芭蕾", "pinyin": "bālěi", "english": "ballet"},
    {"hanzi": "歌词", "pinyin": "gēcí", "english": "lyrics"},
    {"hanzi": "乐谱", "pinyin": "yuèpǔ", "english": "musical score"},
    {"hanzi": "原创", "pinyin": "yuánchuàng", "english": "original creation"},
    {"hanzi": "木偶", "pinyin": "mù'ǒu", "english": "puppet"},
    {"hanzi": "彩排", "pinyin": "cǎipái", "english": "rehearsal"},
    {"hanzi": "幕后", "pinyin": "mùhòu", "english": "behind the scenes"},
    {"hanzi": "配乐", "pinyin": "pèiyuè", "english": "soundtrack"},
    {"hanzi": "剧本", "pinyin": "jùběn", "english": "script"},
    {"hanzi": "大陆", "pinyin": "dàlù", "english": "continent"},
    {"hanzi": "半岛", "pinyin": "bàndǎo", "english": "peninsula"},
    {"hanzi": "盆地", "pinyin": "péndì", "english": "basin"},
    {"hanzi": "高原", "pinyin": "gāoyuán", "english": "plateau"},
    {"hanzi": "绿洲", "pinyin": "lǜzhōu", "english": "oasis"},
    {"hanzi": "峡谷", "pinyin": "xiágǔ", "english": "canyon"},
    {"hanzi": "瀑布", "pinyin": "pùbù", "english": "waterfall"},
    {"hanzi": "海峡", "pinyin": "hǎixiá", "english": "strait"},
    {"hanzi": "海拔", "pinyin": "hǎibá", "english": "altitude"},
    {"hanzi": "丘陵", "pinyin": "qiūlíng", "english": "hills"},
    {"hanzi": "溪流", "pinyin": "xīliú", "english": "stream"},
    {"hanzi": "湖泊", "pinyin": "húpō", "english": "lake"},
    {"hanzi": "河流", "pinyin": "héliú", "english": "river"},
    {"hanzi": "沼泽", "pinyin": "zhǎozé", "english": "swamp"},
    {"hanzi": "平原", "pinyin": "píngyuán", "english": "plain"},
    {"hanzi": "山脉", "pinyin": "shānmài", "english": "mountain range"},
    {"hanzi": "岛屿", "pinyin": "dǎoyǔ", "english": "islands"},
    {"hanzi": "热带", "pinyin": "rèdài", "english": "tropics"},
    {"hanzi": "极地", "pinyin": "jídì", "english": "polar region"},
    {"hanzi": "赤道", "pinyin": "chìdào", "english": "equator"},
    {"hanzi": "三角洲", "pinyin": "sānjiǎozhōu", "english": "delta"},
    {"hanzi": "山谷", "pinyin": "shāngǔ", "english": "valley"},
    {"hanzi": "悬崖", "pinyin": "xuányá", "english": "cliff"},
    {"hanzi": "沿海", "pinyin": "yánhǎi", "english": "coastal"},
    {"hanzi": "内陆", "pinyin": "nèilù", "english": "inland"},
    {"hanzi": "港湾", "pinyin": "gǎngwān", "english": "harbor"},
    {"hanzi": "海岸", "pinyin": "hǎiàn", "english": "coast"},
    {"hanzi": "源头", "pinyin": "yuántóu", "english": "source of river"},
    {"hanzi": "支流", "pinyin": "zhīliú", "english": "tributary"},
    {"hanzi": "地貌", "pinyin": "dìmào", "english": "landform"},
    {"hanzi": "哺乳", "pinyin": "bǔrǔ", "english": "breastfeed"},
    {"hanzi": "爬行", "pinyin": "páxíng", "english": "crawl"},
    {"hanzi": "昆虫", "pinyin": "kūnchóng", "english": "insect"},
    {"hanzi": "微生物", "pinyin": "wēishēngwù", "english": "microorganism"},
    {"hanzi": "遗传", "pinyin": "yíchuán", "english": "heredity"},
    {"hanzi": "进化", "pinyin": "jìnhuà", "english": "evolution"},
    {"hanzi": "繁殖", "pinyin": "fánzhí", "english": "reproduce"},
    {"hanzi": "栖息", "pinyin": "qīxī", "english": "inhabit"},
    {"hanzi": "天敌", "pinyin": "tiāndí", "english": "natural enemy"},
    {"hanzi": "两栖", "pinyin": "liǎngqī", "english": "amphibian"},
    {"hanzi": "食物链", "pinyin": "shíwùliàn", "english": "food chain"},
    {"hanzi": "恐龙", "pinyin": "kǒnglóng", "english": "dinosaur"},
    {"hanzi": "捕食", "pinyin": "bǔshí", "english": "prey on"},
    {"hanzi": "候鸟", "pinyin": "hòuniǎo", "english": "migratory bird"},
    {"hanzi": "家畜", "pinyin": "jiāchù", "english": "livestock"},
    {"hanzi": "野兽", "pinyin": "yěshòu", "english": "wild beast"},
    {"hanzi": "脊椎", "pinyin": "jǐzhuī", "english": "spine"},
    {"hanzi": "翅膀", "pinyin": "chìbǎng", "english": "wing"},
    {"hanzi": "羽毛", "pinyin": "yǔmáo", "english": "feather"},
    {"hanzi": "蝴蝶", "pinyin": "húdié", "english": "butterfly"},
    {"hanzi": "蜜蜂", "pinyin": "mìfēng", "english": "bee"},
    {"hanzi": "蚂蚁", "pinyin": "mǎyǐ", "english": "ant"},
    {"hanzi": "鲸鱼", "pinyin": "jīngyú", "english": "whale"},
    {"hanzi": "海豚", "pinyin": "hǎitún", "english": "dolphin"},
    {"hanzi": "企鹅", "pinyin": "qǐé", "english": "penguin"},
    {"hanzi": "幼虫", "pinyin": "yòuchóng", "english": "larva"},
    {"hanzi": "卵", "pinyin": "luǎn", "english": "egg (biology)"},
    {"hanzi": "标本", "pinyin": "biāoběn", "english": "specimen"},
    {"hanzi": "化石", "pinyin": "huàshí", "english": "fossil"},
    {"hanzi": "甲壳", "pinyin": "jiǎké", "english": "carapace"},
    {"hanzi": "宇宙", "pinyin": "yǔzhòu", "english": "universe"},
    {"hanzi": "星球", "pinyin": "xīngqiú", "english": "celestial body"},
    {"hanzi": "轨道", "pinyin": "guǐdào", "english": "orbit"},
    {"hanzi": "太空", "pinyin": "tàikōng", "english": "outer space"},
    {"hanzi": "天文", "pinyin": "tiānwén", "english": "astronomy"},
    {"hanzi": "星座", "pinyin": "xīngzuò", "english": "constellation"},
    {"hanzi": "黑洞", "pinyin": "hēidòng", "english": "black hole"},
    {"hanzi": "银河", "pinyin": "yínhé", "english": "Milky Way"},
    {"hanzi": "月球", "pinyin": "yuèqiú", "english": "moon"},
    {"hanzi": "恒星", "pinyin": "héngxīng", "english": "fixed star"},
    {"hanzi": "行星", "pinyin": "xíngxīng", "english": "planet"},
    {"hanzi": "彗星", "pinyin": "huìxīng", "english": "comet"},
    {"hanzi": "流星", "pinyin": "liúxīng", "english": "meteor"},
    {"hanzi": "星云", "pinyin": "xīngyún", "english": "nebula"},
    {"hanzi": "太阳系", "pinyin": "tàiyángxì", "english": "solar system"},
    {"hanzi": "光年", "pinyin": "guāngnián", "english": "light year"},
    {"hanzi": "宇航员", "pinyin": "yǔhángyuán", "english": "astronaut"},
    {"hanzi": "发射", "pinyin": "fāshè", "english": "launch"},
    {"hanzi": "着陆", "pinyin": "zhuólù", "english": "landing"},
    {"hanzi": "飞船", "pinyin": "fēichuán", "english": "spaceship"},
    {"hanzi": "天体", "pinyin": "tiāntǐ", "english": "celestial object"},
    {"hanzi": "星系", "pinyin": "xīngxì", "english": "galaxy"},
    {"hanzi": "日食", "pinyin": "rìshí", "english": "solar eclipse"},
    {"hanzi": "月食", "pinyin": "yuèshí", "english": "lunar eclipse"},
    {"hanzi": "引力波", "pinyin": "yǐnlìbō", "english": "gravitational wave"},
    {"hanzi": "军队", "pinyin": "jūnduì", "english": "military"},
    {"hanzi": "武器", "pinyin": "wǔqì", "english": "weapon"},
    {"hanzi": "战争", "pinyin": "zhànzhēng", "english": "war"},
    {"hanzi": "情报", "pinyin": "qíngbào", "english": "intelligence"},
    {"hanzi": "战略", "pinyin": "zhànlüè", "english": "strategy"},
    {"hanzi": "部队", "pinyin": "bùduì", "english": "troops"},
    {"hanzi": "士兵", "pinyin": "shìbīng", "english": "soldier"},
    {"hanzi": "将军", "pinyin": "jiāngjūn", "english": "general"},
    {"hanzi": "战役", "pinyin": "zhànyì", "english": "battle"},
    {"hanzi": "防御", "pinyin": "fángyù", "english": "defense"},
    {"hanzi": "侦察", "pinyin": "zhēnchá", "english": "reconnaissance"},
    {"hanzi": "导弹", "pinyin": "dǎodàn", "english": "missile"},
    {"hanzi": "坦克", "pinyin": "tǎnkè", "english": "tank"},
    {"hanzi": "舰队", "pinyin": "jiànduì", "english": "fleet"},
    {"hanzi": "空军", "pinyin": "kōngjūn", "english": "air force"},
    {"hanzi": "海军", "pinyin": "hǎijūn", "english": "navy"},
    {"hanzi": "陆军", "pinyin": "lùjūn", "english": "army"},
    {"hanzi": "火药", "pinyin": "huǒyào", "english": "gunpowder"},
    {"hanzi": "炮弹", "pinyin": "pàodàn", "english": "cannonball"},
    {"hanzi": "战术", "pinyin": "zhànshù", "english": "tactics"},
    {"hanzi": "巡逻", "pinyin": "xúnluó", "english": "patrol"},
    {"hanzi": "军备", "pinyin": "jūnbèi", "english": "armament"},
    {"hanzi": "炸弹", "pinyin": "zhàdàn", "english": "bomb"},
    {"hanzi": "堡垒", "pinyin": "bǎolěi", "english": "fortress"},
    {"hanzi": "哨兵", "pinyin": "shàobīng", "english": "sentinel"},
    {"hanzi": "套", "pinyin": "tào", "english": "set"},
    {"hanzi": "栋", "pinyin": "dòng", "english": "MW for buildings"},
    {"hanzi": "堆", "pinyin": "duī", "english": "pile"},
    {"hanzi": "批", "pinyin": "pī", "english": "batch"},
    {"hanzi": "系列", "pinyin": "xìliè", "english": "series"},
    {"hanzi": "角度", "pinyin": "jiǎodù", "english": "angle"},
    {"hanzi": "幅", "pinyin": "fú", "english": "MW for paintings"},
    {"hanzi": "盏", "pinyin": "zhǎn", "english": "MW for lamps"},
    {"hanzi": "轮", "pinyin": "lún", "english": "round"},
    {"hanzi": "颗", "pinyin": "kē", "english": "MW for small items"},
    {"hanzi": "册", "pinyin": "cè", "english": "volume"},
    {"hanzi": "届", "pinyin": "jiè", "english": "session"},
    {"hanzi": "阵", "pinyin": "zhèn", "english": "burst"},
    {"hanzi": "笔", "pinyin": "bǐ", "english": "pen"},
    {"hanzi": "艘", "pinyin": "sōu", "english": "MW for ships"},
    {"hanzi": "辆", "pinyin": "liàng", "english": "MW for vehicles"},
    {"hanzi": "匹", "pinyin": "pǐ", "english": "MW for horses"},
    {"hanzi": "枚", "pinyin": "méi", "english": "MW for coins"},
    {"hanzi": "剂", "pinyin": "jì", "english": "dose"},
    {"hanzi": "丛", "pinyin": "cóng", "english": "cluster"},
    {"hanzi": "桩", "pinyin": "zhuāng", "english": "stake"},
    {"hanzi": "摊", "pinyin": "tān", "english": "stall"},
    {"hanzi": "株", "pinyin": "zhū", "english": "MW for plants"},
    {"hanzi": "缕", "pinyin": "lǚ", "english": "wisp"},
    {"hanzi": "暴雪", "pinyin": "bàoxuě", "english": "blizzard"},
    {"hanzi": "飓风", "pinyin": "jùfēng", "english": "hurricane"},
    {"hanzi": "龙卷风", "pinyin": "lóngjuǎnfēng", "english": "tornado"},
    {"hanzi": "冰雹", "pinyin": "bīngbáo", "english": "hail"},
    {"hanzi": "海啸", "pinyin": "hǎixiào", "english": "tsunami"},
    {"hanzi": "泥石流", "pinyin": "níshíliú", "english": "mudslide"},
    {"hanzi": "地热", "pinyin": "dìrè", "english": "geothermal"},
    {"hanzi": "坦然", "pinyin": "tǎnrán", "english": "composed"},
    {"hanzi": "惶恐", "pinyin": "huángkǒng", "english": "terrified"},
    {"hanzi": "欣喜", "pinyin": "xīnxǐ", "english": "delighted"},
    {"hanzi": "惋惜", "pinyin": "wǎnxī", "english": "feel sorry"},
    {"hanzi": "邻里", "pinyin": "línlǐ", "english": "neighborhood"},
    {"hanzi": "帐篷", "pinyin": "zhàngpeng", "english": "tent"},
    {"hanzi": "篝火", "pinyin": "gōuhuǒ", "english": "bonfire"},
    {"hanzi": "野营", "pinyin": "yěyíng", "english": "camping"},
    {"hanzi": "郊游", "pinyin": "jiāoyóu", "english": "outing"},
    {"hanzi": "佐料", "pinyin": "zuǒliào", "english": "seasoning"},
    {"hanzi": "腌制", "pinyin": "yānzhì", "english": "pickle"},
    {"hanzi": "蒸笼", "pinyin": "zhēnglóng", "english": "steamer"},
    {"hanzi": "棉花", "pinyin": "miánhua", "english": "cotton"},
    {"hanzi": "羊毛", "pinyin": "yángmáo", "english": "wool"},
    {"hanzi": "亚麻", "pinyin": "yàmá", "english": "linen"},
    {"hanzi": "刺绣", "pinyin": "cìxiù", "english": "embroidery"},
    {"hanzi": "地毯", "pinyin": "dìtǎn", "english": "carpet"},
    {"hanzi": "花瓶", "pinyin": "huāpíng", "english": "vase"},
    {"hanzi": "壁炉", "pinyin": "bìlú", "english": "fireplace"},
    {"hanzi": "烟囱", "pinyin": "yāncōng", "english": "chimney"},
    {"hanzi": "窗台", "pinyin": "chuāngtái", "english": "windowsill"},
    {"hanzi": "鼓", "pinyin": "gǔ", "english": "drum"},
    {"hanzi": "笛子", "pinyin": "dízi", "english": "flute"},
    {"hanzi": "琵琶", "pinyin": "pípá", "english": "pipa"},
    {"hanzi": "二胡", "pinyin": "èrhú", "english": "erhu"},
    {"hanzi": "吊车", "pinyin": "diàochē", "english": "crane"},
    {"hanzi": "隧道", "pinyin": "suìdào", "english": "tunnel"},
    {"hanzi": "铝", "pinyin": "lǚ", "english": "aluminum"},
    {"hanzi": "铜", "pinyin": "tóng", "english": "copper"},
    {"hanzi": "韧带", "pinyin": "rèndài", "english": "ligament"},
    {"hanzi": "肌肉", "pinyin": "jīròu", "english": "muscle"},
    {"hanzi": "骨骼", "pinyin": "gǔgé", "english": "skeleton"},
    {"hanzi": "讲义", "pinyin": "jiǎngyì", "english": "lecture notes"},
    {"hanzi": "学徒", "pinyin": "xuétú", "english": "apprentice"},
    {"hanzi": "拼图", "pinyin": "pīntú", "english": "jigsaw puzzle"},
    {"hanzi": "棋", "pinyin": "qí", "english": "chess"},
    {"hanzi": "骰子", "pinyin": "tóuzi", "english": "dice"},
    {"hanzi": "扑克", "pinyin": "pūkè", "english": "poker"},
    {"hanzi": "软骨", "pinyin": "ruǎngǔ", "english": "cartilage"},
    {"hanzi": "渡轮", "pinyin": "dùlún", "english": "ferry"},
    {"hanzi": "游艇", "pinyin": "yóutǐng", "english": "yacht"},
    {"hanzi": "潜艇", "pinyin": "qiántǐng", "english": "submarine"},
    {"hanzi": "灯塔", "pinyin": "dēngtǎ", "english": "lighthouse"},
    {"hanzi": "罗盘", "pinyin": "luópán", "english": "compass"},
    {"hanzi": "帆船", "pinyin": "fānchuán", "english": "sailboat"},
    {"hanzi": "锚", "pinyin": "máo", "english": "anchor"},
    {"hanzi": "琥珀", "pinyin": "hǔpò", "english": "amber"},
    {"hanzi": "陀螺", "pinyin": "tuóluó", "english": "gyroscope"},
    {"hanzi": "婚姻", "pinyin": "hūnyīn", "english": "marriage"},
    {"hanzi": "后代", "pinyin": "hòudài", "english": "descendant"},
    {"hanzi": "祖先", "pinyin": "zǔxiān", "english": "ancestor"},
    {"hanzi": "养育", "pinyin": "yǎngyù", "english": "raise; nurture"},
    {"hanzi": "离婚", "pinyin": "líhūn", "english": "divorce"},
    {"hanzi": "嫂子", "pinyin": "sǎozi", "english": "sister-in-law (elder brother's wife)"},
    {"hanzi": "姑娘", "pinyin": "gūniang", "english": "girl; young woman"},
    {"hanzi": "侄子", "pinyin": "zhízi", "english": "nephew"},
    {"hanzi": "岳父", "pinyin": "yuèfù", "english": "father-in-law (wife's father)"},
    {"hanzi": "婆婆", "pinyin": "pópó", "english": "mother-in-law; grandmother"},
    {"hanzi": "媳妇", "pinyin": "xífù", "english": "daughter-in-law; wife"},
    {"hanzi": "新娘", "pinyin": "xīnniáng", "english": "bride"},
    {"hanzi": "新郎", "pinyin": "xīnláng", "english": "groom"},
    {"hanzi": "孝顺", "pinyin": "xiàoshùn", "english": "filial piety"},
    {"hanzi": "抚养", "pinyin": "fǔyǎng", "english": "foster; raise"},
    {"hanzi": "订婚", "pinyin": "dìnghūn", "english": "get engaged"},
    {"hanzi": "继承", "pinyin": "jìchéng", "english": "inherit; succeed"},
    {"hanzi": "寡妇", "pinyin": "guǎfù", "english": "widow"},
    {"hanzi": "固执", "pinyin": "gùzhí", "english": "stubborn"},
    {"hanzi": "善良", "pinyin": "shànliáng", "english": "kind-hearted"},
    {"hanzi": "坦率", "pinyin": "tǎnshuài", "english": "frank; candid"},
    {"hanzi": "自私", "pinyin": "zìsī", "english": "selfish"},
    {"hanzi": "害羞", "pinyin": "hàixiū", "english": "shy"},
    {"hanzi": "温柔", "pinyin": "wēnróu", "english": "gentle; tender"},
    {"hanzi": "虚伪", "pinyin": "xūwěi", "english": "hypocritical"},
    {"hanzi": "贪婪", "pinyin": "tānlán", "english": "greedy"},
    {"hanzi": "懦弱", "pinyin": "nuòruò", "english": "cowardly"},
    {"hanzi": "慷慨", "pinyin": "kāngkǎi", "english": "generous"},
    {"hanzi": "忠诚", "pinyin": "zhōngchéng", "english": "loyal; faithful"},
    {"hanzi": "狡猾", "pinyin": "jiǎohuá", "english": "sly; cunning"},
    {"hanzi": "爽快", "pinyin": "shuǎngkuài", "english": "straightforward; frank"},
    {"hanzi": "和蔼", "pinyin": "hé'ǎi", "english": "kindly; amiable"},
    {"hanzi": "沉着", "pinyin": "chénzhuó", "english": "calm; composed"},
    {"hanzi": "刻苦", "pinyin": "kèkǔ", "english": "hardworking; assiduous"},
    {"hanzi": "机灵", "pinyin": "jīling", "english": "clever; quick-witted"},
    {"hanzi": "协调", "pinyin": "xiétiáo", "english": "coordinate"},
    {"hanzi": "审查", "pinyin": "shěnchá", "english": "examine; review"},
    {"hanzi": "归纳", "pinyin": "guīnà", "english": "summarize; induce"},
    {"hanzi": "概括", "pinyin": "gàikuò", "english": "generalize; summarize"},
    {"hanzi": "核实", "pinyin": "héshí", "english": "verify; confirm"},
    {"hanzi": "妥协", "pinyin": "tuǒxié", "english": "compromise"},
    {"hanzi": "嘱咐", "pinyin": "zhǔfù", "english": "instruct; enjoin"},
    {"hanzi": "辨别", "pinyin": "biànbié", "english": "distinguish; differentiate"},
    {"hanzi": "领悟", "pinyin": "lǐngwù", "english": "comprehend; grasp"},
    {"hanzi": "抵制", "pinyin": "dǐzhì", "english": "boycott; resist"},
    {"hanzi": "耽误", "pinyin": "dānwù", "english": "delay; hold up"},
    {"hanzi": "逮捕", "pinyin": "dàibǔ", "english": "arrest"},
    {"hanzi": "挣扎", "pinyin": "zhēngzhá", "english": "struggle"},
    {"hanzi": "崇拜", "pinyin": "chóngbài", "english": "worship; admire"},
    {"hanzi": "抛弃", "pinyin": "pāoqì", "english": "abandon; discard"},
    {"hanzi": "挽救", "pinyin": "wǎnjiù", "english": "rescue; save"},
    {"hanzi": "蔓延", "pinyin": "mànyán", "english": "spread; extend"},
    {"hanzi": "驾驶", "pinyin": "jiàshǐ", "english": "drive; pilot"},
    {"hanzi": "颤抖", "pinyin": "chàndǒu", "english": "tremble; shiver"},
    {"hanzi": "弥漫", "pinyin": "mímàn", "english": "fill; pervade"},
    {"hanzi": "酝酿", "pinyin": "yùnniàng", "english": "brew; deliberate"},
    {"hanzi": "笼罩", "pinyin": "lǒngzhào", "english": "envelop; shroud"},
    {"hanzi": "搁置", "pinyin": "gēzhì", "english": "shelve; set aside"},
    {"hanzi": "掩饰", "pinyin": "yǎnshì", "english": "conceal; cover up"},
    {"hanzi": "憧憬", "pinyin": "chōngjǐng", "english": "look forward to; yearn for"},
    {"hanzi": "窥探", "pinyin": "kuītàn", "english": "spy on; peek"},
    {"hanzi": "呕吐", "pinyin": "ǒutù", "english": "vomit"},
    {"hanzi": "喧嚣", "pinyin": "xuānxiāo", "english": "noisy; clamorous"},
    {"hanzi": "篡改", "pinyin": "cuàngǎi", "english": "tamper with; falsify"},
    {"hanzi": "斡旋", "pinyin": "wòxuán", "english": "mediate"},
    {"hanzi": "拼搏", "pinyin": "pīnbó", "english": "struggle hard; strive"},
    {"hanzi": "鞭策", "pinyin": "biāncè", "english": "spur on; urge"},
    {"hanzi": "诠释", "pinyin": "quánshì", "english": "interpret; explain"},
    {"hanzi": "铸造", "pinyin": "zhùzào", "english": "cast; forge"},
    {"hanzi": "遏止", "pinyin": "èzhǐ", "english": "check; hold back"},
    {"hanzi": "钢铁", "pinyin": "gāngtiě", "english": "steel"},
    {"hanzi": "纤维", "pinyin": "xiānwéi", "english": "fiber"},
    {"hanzi": "混凝土", "pinyin": "hùnníngtǔ", "english": "concrete"},
    {"hanzi": "橡胶", "pinyin": "xiàngjiāo", "english": "rubber"},
    {"hanzi": "煤炭", "pinyin": "méitàn", "english": "coal"},
    {"hanzi": "合金", "pinyin": "héjīn", "english": "alloy"},
    {"hanzi": "沥青", "pinyin": "lìqīng", "english": "asphalt"},
    {"hanzi": "瓷器", "pinyin": "cíqì", "english": "porcelain"},
    {"hanzi": "石膏", "pinyin": "shígāo", "english": "plaster; gypsum"},
    {"hanzi": "涂料", "pinyin": "túliào", "english": "coating; paint"},
    {"hanzi": "石灰", "pinyin": "shíhuī", "english": "lime"},
    {"hanzi": "大理石", "pinyin": "dàlǐshí", "english": "marble"},
    {"hanzi": "庄稼", "pinyin": "zhuāngjia", "english": "crops"},
    {"hanzi": "收割", "pinyin": "shōugē", "english": "harvest; reap"},
    {"hanzi": "灌溉", "pinyin": "guàngài", "english": "irrigate"},
    {"hanzi": "肥料", "pinyin": "féiliào", "english": "fertilizer"},
    {"hanzi": "种植", "pinyin": "zhòngzhí", "english": "plant; cultivate"},
    {"hanzi": "牧场", "pinyin": "mùchǎng", "english": "pasture; ranch"},
    {"hanzi": "渔业", "pinyin": "yúyè", "english": "fishing industry"},
    {"hanzi": "耕地", "pinyin": "gēngdì", "english": "arable land"},
    {"hanzi": "播种", "pinyin": "bōzhǒng", "english": "sow seeds"},
    {"hanzi": "谷物", "pinyin": "gǔwù", "english": "grain; cereal"},
    {"hanzi": "饲养", "pinyin": "sìyǎng", "english": "raise; breed"},
    {"hanzi": "杂草", "pinyin": "zácǎo", "english": "weeds"},
    {"hanzi": "丰收", "pinyin": "fēngshōu", "english": "bumper harvest"},
    {"hanzi": "哲学", "pinyin": "zhéxué", "english": "philosophy"},
    {"hanzi": "佛教", "pinyin": "fójiào", "english": "Buddhism"},
    {"hanzi": "基督", "pinyin": "jīdū", "english": "Christ"},
    {"hanzi": "伊斯兰", "pinyin": "yīsīlán", "english": "Islam"},
    {"hanzi": "灵魂", "pinyin": "línghún", "english": "soul; spirit"},
    {"hanzi": "命运", "pinyin": "mìngyùn", "english": "fate; destiny"},
    {"hanzi": "信念", "pinyin": "xìnniàn", "english": "faith; belief"},
    {"hanzi": "祈祷", "pinyin": "qídǎo", "english": "pray"},
    {"hanzi": "寺庙", "pinyin": "sìmiào", "english": "temple"},
    {"hanzi": "僧侣", "pinyin": "sēnglǚ", "english": "monk"},
    {"hanzi": "修行", "pinyin": "xiūxíng", "english": "spiritual practice"},
    {"hanzi": "冥想", "pinyin": "míngxiǎng", "english": "meditate"},
    {"hanzi": "教堂", "pinyin": "jiàotáng", "english": "church"},
    {"hanzi": "天堂", "pinyin": "tiāntáng", "english": "heaven; paradise"},
    {"hanzi": "地狱", "pinyin": "dìyù", "english": "hell"},
    {"hanzi": "启示", "pinyin": "qǐshì", "english": "revelation; inspiration"},
    {"hanzi": "一帆风顺", "pinyin": "yīfānfēngshùn", "english": "smooth sailing"},
    {"hanzi": "自言自语", "pinyin": "zìyánzìyǔ", "english": "talk to oneself"},
    {"hanzi": "迫不及待", "pinyin": "pòbùjídài", "english": "can't wait"},
    {"hanzi": "理所当然", "pinyin": "lǐsuǒdāngrán", "english": "take for granted"},
    {"hanzi": "不知不觉", "pinyin": "bùzhībùjué", "english": "unconsciously"},
    {"hanzi": "一目了然", "pinyin": "yīmùliǎorán", "english": "clear at a glance"},
    {"hanzi": "恍然大悟", "pinyin": "huǎngrándàwù", "english": "suddenly realize"},
    {"hanzi": "半途而废", "pinyin": "bàntúérfèi", "english": "give up halfway"},
    {"hanzi": "津津有味", "pinyin": "jīnjīnyǒuwèi", "english": "with great relish"},
    {"hanzi": "不可思议", "pinyin": "bùkěsīyì", "english": "incredible; unbelievable"},
    {"hanzi": "脱颖而出", "pinyin": "tuōyǐngérchū", "english": "stand out"},
    {"hanzi": "心甘情愿", "pinyin": "xīngānqíngyuàn", "english": "willingly"},
    {"hanzi": "异想天开", "pinyin": "yìxiǎngtiānkāi", "english": "whimsical fantasy"},
    {"hanzi": "无可奈何", "pinyin": "wúkěnàihé", "english": "helpless; no choice"},
    {"hanzi": "名副其实", "pinyin": "míngfùqíshí", "english": "live up to the name"},
    {"hanzi": "随心所欲", "pinyin": "suíxīnsuǒyù", "english": "do as one pleases"},
    {"hanzi": "得不偿失", "pinyin": "débùchángshī", "english": "not worth the cost"},
    {"hanzi": "一无所知", "pinyin": "yīwúsuǒzhī", "english": "know nothing about"},
    {"hanzi": "叹为观止", "pinyin": "tànwéiguānzhǐ", "english": "gasp in amazement"},
    {"hanzi": "自作自受", "pinyin": "zìzuòzìshòu", "english": "reap what one sows"},
    {"hanzi": "爱不释手", "pinyin": "àibùshìshǒu", "english": "can't put it down"},
    {"hanzi": "刻不容缓", "pinyin": "kèbùrónghuǎn", "english": "brook no delay"},
    {"hanzi": "情不自禁", "pinyin": "qíngbùzìjīn", "english": "can't help oneself"},
    {"hanzi": "毫无疑问", "pinyin": "háowúyíwèn", "english": "without a doubt"},
    {"hanzi": "微不足道", "pinyin": "wēibùzúdào", "english": "insignificant"},
    {"hanzi": "器官", "pinyin": "qìguān", "english": "organ (body)"},
    {"hanzi": "穴位", "pinyin": "xuéwèi", "english": "acupuncture point"},
    {"hanzi": "昏迷", "pinyin": "hūnmí", "english": "coma; unconscious"},
    {"hanzi": "食欲", "pinyin": "shíyù", "english": "appetite"},
    {"hanzi": "视力", "pinyin": "shìlì", "english": "eyesight; vision"},
    {"hanzi": "听力", "pinyin": "tīnglì", "english": "hearing"},
    {"hanzi": "骨头", "pinyin": "gǔtou", "english": "bone"},
    {"hanzi": "手腕", "pinyin": "shǒuwàn", "english": "wrist"},
    {"hanzi": "脚踝", "pinyin": "jiǎohuái", "english": "ankle"},
    {"hanzi": "嗓子", "pinyin": "sǎngzi", "english": "throat; voice"},
    {"hanzi": "伤疤", "pinyin": "shāngbā", "english": "scar"},
    {"hanzi": "处方药", "pinyin": "chǔfāngyào", "english": "prescription drug"},
    {"hanzi": "雾", "pinyin": "wù", "english": "fog; mist"},
    {"hanzi": "彩霞", "pinyin": "cǎixiá", "english": "colorful clouds"},
    {"hanzi": "山坡", "pinyin": "shānpō", "english": "hillside; slope"},
    {"hanzi": "峰", "pinyin": "fēng", "english": "peak; summit"},
    {"hanzi": "树荫", "pinyin": "shùyīn", "english": "shade of a tree"},
    {"hanzi": "苔藓", "pinyin": "táixiǎn", "english": "moss"},
    {"hanzi": "礁石", "pinyin": "jiāoshí", "english": "reef"},
    {"hanzi": "泉水", "pinyin": "quánshuǐ", "english": "spring water"},
    {"hanzi": "峭壁", "pinyin": "qiàobì", "english": "cliff; precipice"},
    {"hanzi": "田野", "pinyin": "tiányě", "english": "field; open country"},
    {"hanzi": "宪章", "pinyin": "xiànzhāng", "english": "charter"},
    {"hanzi": "条例", "pinyin": "tiáolì", "english": "regulation; ordinance"},
    {"hanzi": "仲裁员", "pinyin": "zhòngcáiyuán", "english": "arbitrator"},
    {"hanzi": "豁免", "pinyin": "huòmiǎn", "english": "exemption; immunity"},
    {"hanzi": "管辖", "pinyin": "guǎnxiá", "english": "jurisdiction"},
    {"hanzi": "赦免", "pinyin": "shèmiǎn", "english": "pardon; amnesty"},
    {"hanzi": "颁布", "pinyin": "bānbù", "english": "promulgate; issue"},
    {"hanzi": "修订", "pinyin": "xiūdìng", "english": "revise; amend"},
    {"hanzi": "垄断", "pinyin": "lǒngduàn", "english": "monopoly"},
    {"hanzi": "通胀", "pinyin": "tōngzhàng", "english": "inflation"},
    {"hanzi": "萧索", "pinyin": "xiāosuǒ", "english": "bleak; desolate"},
    {"hanzi": "拍卖", "pinyin": "pāimài", "english": "auction"},
    {"hanzi": "零钱", "pinyin": "língqián", "english": "change (money)"},
    {"hanzi": "佣金", "pinyin": "yōngjīn", "english": "commission"},
    {"hanzi": "清算", "pinyin": "qīngsuàn", "english": "liquidate; settle"},
    {"hanzi": "担保人", "pinyin": "dānbǎorén", "english": "guarantor"},
    {"hanzi": "辅导员", "pinyin": "fǔdǎoyuán", "english": "counselor; tutor"},
    {"hanzi": "学徒制", "pinyin": "xuétúzhì", "english": "apprenticeship"},
    {"hanzi": "奖惩", "pinyin": "jiǎngchéng", "english": "reward and punishment"},
    {"hanzi": "辍学", "pinyin": "chuòxué", "english": "drop out of school"},
    {"hanzi": "启蒙", "pinyin": "qǐméng", "english": "enlighten; initiate"},
    {"hanzi": "绝望", "pinyin": "juéwàng", "english": "despair; hopeless"},
    {"hanzi": "宽慰", "pinyin": "kuānwèi", "english": "relieved; comforted"},
    {"hanzi": "厌恶", "pinyin": "yànwù", "english": "loathe; detest"},
    {"hanzi": "眷恋", "pinyin": "juànliàn", "english": "be sentimentally attached"},
    {"hanzi": "惭愧", "pinyin": "cánkuì", "english": "ashamed"},
    {"hanzi": "委婉", "pinyin": "wěiwǎn", "english": "tactful; euphemistic"},
    {"hanzi": "侥幸", "pinyin": "jiǎoxìng", "english": "lucky; by fluke"},
    {"hanzi": "踌躇", "pinyin": "chóuchú", "english": "hesitate"},
    {"hanzi": "窗帘布", "pinyin": "chuānglián bù", "english": "curtain fabric"},
    {"hanzi": "剪刀", "pinyin": "jiǎndāo", "english": "scissors"},
    {"hanzi": "梳子", "pinyin": "shūzi", "english": "comb"},
    {"hanzi": "枕头", "pinyin": "zhěntou", "english": "pillow"},
    {"hanzi": "被褥", "pinyin": "bèirù", "english": "bedding; quilts"},
    {"hanzi": "抽屉", "pinyin": "chōuti", "english": "drawer"},
    {"hanzi": "扫帚", "pinyin": "sàozhou", "english": "broom"},
    {"hanzi": "拖把", "pinyin": "tuōbǎ", "english": "mop"},
    {"hanzi": "锅", "pinyin": "guō", "english": "pot; wok"},
    {"hanzi": "勺", "pinyin": "sháo", "english": "spoon; ladle"},
    {"hanzi": "筷子", "pinyin": "kuàizi", "english": "chopsticks"},
    {"hanzi": "胶带", "pinyin": "jiāodài", "english": "adhesive tape"},
    {"hanzi": "绳子", "pinyin": "shéngzi", "english": "rope; string"},
    {"hanzi": "钉子", "pinyin": "dīngzi", "english": "nail"},
    {"hanzi": "锤子", "pinyin": "chuízi", "english": "hammer"},
    {"hanzi": "货车", "pinyin": "huòchē", "english": "truck; freight vehicle"},
    {"hanzi": "摩托车", "pinyin": "mótuōchē", "english": "motorcycle"},
    {"hanzi": "帆", "pinyin": "fān", "english": "sail"},
    {"hanzi": "船舶", "pinyin": "chuánbó", "english": "ship; vessel"},
    {"hanzi": "码头工", "pinyin": "mǎtóugōng", "english": "dock worker"},
    {"hanzi": "寒暄", "pinyin": "hánxuān", "english": "exchange greetings"},
    {"hanzi": "恭维", "pinyin": "gōngwéi", "english": "compliment; flatter"},
    {"hanzi": "唠叨", "pinyin": "láodao", "english": "nag; chatter"},
    {"hanzi": "嘲笑", "pinyin": "cháoxiào", "english": "mock; ridicule"},
    {"hanzi": "诽谤", "pinyin": "fěibàng", "english": "slander; defame"},
    {"hanzi": "辟谣", "pinyin": "pìyáo", "english": "refute a rumor"},
    {"hanzi": "吹嘘", "pinyin": "chuīxū", "english": "boast; brag"},
    {"hanzi": "黎明", "pinyin": "límíng", "english": "dawn; daybreak"},
    {"hanzi": "黄昏", "pinyin": "huánghūn", "english": "dusk; twilight"},
    {"hanzi": "拂晓", "pinyin": "fúxiǎo", "english": "daybreak"},
    {"hanzi": "午夜", "pinyin": "wǔyè", "english": "midnight"},
    {"hanzi": "旬", "pinyin": "xún", "english": "ten-day period"},
    {"hanzi": "境界", "pinyin": "jìngjiè", "english": "realm; level"},
    {"hanzi": "眉目", "pinyin": "méimù", "english": "features; outline"},
    {"hanzi": "端倪", "pinyin": "duānní", "english": "clue; inkling"},
    {"hanzi": "症结", "pinyin": "zhēngjié", "english": "crux; key issue"},
    {"hanzi": "棘手", "pinyin": "jíshǒu", "english": "thorny; knotty"},
    {"hanzi": "隐患", "pinyin": "yǐnhuàn", "english": "hidden danger"},
    {"hanzi": "弊端", "pinyin": "bìduān", "english": "drawback; malpractice"},
    {"hanzi": "风波", "pinyin": "fēngbō", "english": "disturbance; storm"},
    {"hanzi": "舆情", "pinyin": "yúqíng", "english": "public sentiment"},
    {"hanzi": "共赢", "pinyin": "gòngyíng", "english": "win-win"},
    {"hanzi": "福祉", "pinyin": "fúzhǐ", "english": "well-being; welfare"},
    {"hanzi": "底蕴深", "pinyin": "dǐyùn shēn", "english": "rich heritage"},
    {"hanzi": "凝练", "pinyin": "níngliàn", "english": "concise; refined"},
    {"hanzi": "领口", "pinyin": "lǐngkǒu", "english": "collar; neckline"},
    {"hanzi": "袖子", "pinyin": "xiùzi", "english": "sleeve"},
    {"hanzi": "纽扣眼", "pinyin": "niǔkòuyǎn", "english": "buttonhole"},
    {"hanzi": "腰带", "pinyin": "yāodài", "english": "belt"},
    {"hanzi": "围裙", "pinyin": "wéiqún", "english": "apron"},
    {"hanzi": "骆驼", "pinyin": "luòtuo", "english": "camel"},
    {"hanzi": "刺猬", "pinyin": "cìwei", "english": "hedgehog"},
    {"hanzi": "松鼠", "pinyin": "sōngshǔ", "english": "squirrel"},
    {"hanzi": "海鸥", "pinyin": "hǎiōu", "english": "seagull"},
    {"hanzi": "鸽子", "pinyin": "gēzi", "english": "pigeon; dove"},
    {"hanzi": "蟋蟀", "pinyin": "xīshuài", "english": "cricket"},
    {"hanzi": "蜻蜓", "pinyin": "qīngtíng", "english": "dragonfly"},
    {"hanzi": "蒸馏", "pinyin": "zhēngliù", "english": "distill"},
    {"hanzi": "腌菜", "pinyin": "yāncài", "english": "pickled vegetables"},
    {"hanzi": "馅", "pinyin": "xiàn", "english": "filling; stuffing"},
    {"hanzi": "卤", "pinyin": "lǔ", "english": "braised in soy sauce"},
    {"hanzi": "旋转", "pinyin": "xuánzhuǎn", "english": "rotate; spin"},
    {"hanzi": "素材", "pinyin": "sùcái", "english": "source material"},
    {"hanzi": "色泽", "pinyin": "sèzé", "english": "color and luster"},
    {"hanzi": "镶嵌", "pinyin": "xiāngqiàn", "english": "inlay; embed"},
    {"hanzi": "窍门", "pinyin": "qiàomén", "english": "knack; trick"},
    {"hanzi": "嗜好", "pinyin": "shìhào", "english": "hobby; addiction"},
    {"hanzi": "奢侈", "pinyin": "shēchǐ", "english": "extravagant; luxury"},
    {"hanzi": "朦胧", "pinyin": "ménglóng", "english": "hazy; dim"},
    {"hanzi": "斑斓", "pinyin": "bānlán", "english": "gorgeous; colorful"},
    {"hanzi": "璀璨", "pinyin": "cuǐcàn", "english": "resplendent; brilliant"},
    {"hanzi": "蕴藏", "pinyin": "yùncáng", "english": "contain; hold in store"},
    {"hanzi": "翱翔", "pinyin": "áoxiáng", "english": "soar; glide"},
]
